/**
 * Self-contained admin UI for OCRProxy EdgeOne.
 *
 *   Generated by scripts/build-admin.mjs from admin.{html,css,js}
 *   Do not edit this file directly.
 */

function pageHtml() {
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>OCRProxy EdgeOne 控制台</title>
  <style>
/* ═══════════════════════════════════════════════════════════════
   KHC Web Design System — OCRProxy EdgeOne Admin Stylesheet
   ═══════════════════════════════════════════════════════════════ */

:root {
  /* Primary Brand (KHC Blue) */
  --khc-primary-50: #E6EEFF;
  --khc-primary-100: #C5D7FF;
  --khc-primary-200: #98B8FF;
  --khc-primary-300: #6B99FF;
  --khc-primary-400: #3F7AFF;
  --khc-primary-500: #1664FF;
  --khc-primary-600: #0F54E0;
  --khc-primary-700: #0B43B8;
  --khc-primary-800: #083185;
  --khc-primary-900: #06205C;

  /* Neutral / Slate Grays */
  --khc-neutral-50: #F8FAFC;
  --khc-neutral-100: #F1F5F9;
  --khc-neutral-200: #E2E8F0;
  --khc-neutral-300: #CBD5E1;
  --khc-neutral-400: #94A3B8;
  --khc-neutral-500: #64748B;
  --khc-neutral-600: #475569;
  --khc-neutral-700: #334155;
  --khc-neutral-800: #1E293B;
  --khc-neutral-900: #0F172A;

  /* Semantic State Colors */
  --khc-success-50: #ECFDF5;
  --khc-success-100: #D1FAE5;
  --khc-success-200: #A7F3D0;
  --khc-success-500: #10B981;
  --khc-success-600: #059669;
  --khc-success-700: #047857;

  --khc-warning-50: #FFFBEB;
  --khc-warning-100: #FEF3C7;
  --khc-warning-200: #FDE68A;
  --khc-warning-500: #F59E0B;
  --khc-warning-600: #D97706;
  --khc-warning-700: #B45309;

  --khc-danger-50: #FEF2F2;
  --khc-danger-100: #FEE2E2;
  --khc-danger-200: #FECACA;
  --khc-danger-500: #EF4444;
  --khc-danger-600: #DC2626;
  --khc-danger-700: #B91C1C;

  --khc-info-50: #ECFEFF;
  --khc-info-100: #CFFAFE;
  --khc-info-200: #A5F3FC;
  --khc-info-500: #06B6D4;
  --khc-info-700: #0E7490;

  /* Text Aliases */
  --color-text-1: var(--khc-neutral-900);
  --color-text-2: var(--khc-neutral-600);
  --color-text-3: var(--khc-neutral-400);
  --color-text-inverse: #FFFFFF;

  /* Surface Aliases */
  --color-bg-page: var(--khc-neutral-50);
  --color-bg-card: #FFFFFF;
  --color-bg-hover: var(--khc-neutral-100);

  /* Border Aliases */
  --color-border: var(--khc-neutral-200);
  --color-border-strong: var(--khc-neutral-300);

  /* Semantic Aliases */
  --color-primary: var(--khc-primary-500);
  --color-primary-hover: var(--khc-primary-400);
  --color-primary-active: var(--khc-primary-600);
  --color-success: var(--khc-success-500);
  --color-warning: var(--khc-warning-500);
  --color-danger: var(--khc-danger-500);
  --color-info: var(--khc-info-500);

  /* Legacy error aliases used by inline error boxes */
  --error: var(--color-danger);
  --error-soft: var(--khc-danger-50);
  --error-border: var(--khc-danger-200);

  /* Typography */
  --font-body: 'PingFang SC', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  --font-mono: 'SF Mono', 'Roboto Mono', Menlo, Consolas, Monaco, monospace;
  --font-size-display: 32px;
  --font-size-h1: 24px;
  --font-size-h2: 20px;
  --font-size-h3: 16px;
  --font-size-body: 14px;
  --font-size-caption: 12px;

  /* Spacing */
  --space-1: 4px;
  --space-2: 8px;
  --space-3: 12px;
  --space-4: 16px;
  --space-5: 24px;
  --space-6: 32px;

  /* Radius */
  --radius-sm: 2px;
  --radius-md: 4px;
  --radius-lg: 8px;
  --radius-xl: 12px;

  /* Shadows */
  --shadow-1: 0 1px 2px rgba(15, 23, 42, 0.04);
  --shadow-2: 0 2px 4px rgba(15, 23, 42, 0.06);
  --shadow-3: 0 4px 8px rgba(15, 23, 42, 0.08);
  --shadow-4: 0 8px 16px rgba(15, 23, 42, 0.10);
  --shadow-5: 0 12px 24px rgba(15, 23, 42, 0.12);
}

/* ── Reset & Base ── */
*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: var(--font-body);
  font-size: var(--font-size-body);
  line-height: 1.5;
  color: var(--color-text-1);
  background-color: var(--color-bg-page);
  -webkit-font-smoothing: antialiased;
}

button, input, select, textarea {
  font-family: inherit;
  font-size: inherit;
  color: inherit;
}

a {
  color: var(--color-primary);
  text-decoration: none;
}
a:hover {
  color: var(--color-primary-hover);
}

.mono {
  font-family: var(--font-mono);
}

.tabular {
  font-variant-numeric: tabular-nums;
}

/* ── App Shell & Navigation ── */
.app {
  display: none;
  min-height: 100vh;
  flex-direction: column;
}

.appbar {
  position: sticky;
  top: 0;
  z-index: 100;
  height: 48px;
  padding: 0 20px;
  background: var(--color-bg-card);
  border-bottom: 1px solid var(--color-border);
  box-shadow: var(--shadow-1);
  display: flex;
  align-items: center;
  gap: var(--space-4);
}

.brand-title {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  font-size: var(--font-size-h3);
  font-weight: 700;
  color: var(--color-text-1);
  white-space: nowrap;
}

.brand-logo {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  border-radius: var(--radius-sm);
  background: linear-gradient(135deg, var(--khc-primary-500), var(--khc-primary-700));
  color: var(--color-text-inverse);
  font-weight: 700;
  font-size: 15px;
}

.brand-badge {
  font-size: 11px;
  font-weight: 500;
  padding: 2px 8px;
  border-radius: 10px;
  background: var(--khc-primary-50);
  color: var(--color-primary);
  border: 1px solid var(--khc-primary-100);
}

nav#topNav {
  display: inline-flex;
  align-items: center;
  gap: var(--space-1);
  margin-left: auto;
}

nav#topNav button {
  appearance: none;
  border: none;
  background: transparent;
  padding: 6px 14px;
  font-size: 13px;
  font-weight: 500;
  color: var(--color-text-2);
  border-radius: var(--radius-sm);
  cursor: pointer;
  white-space: nowrap;
  transition: background 0.15s, color 0.15s;
}

nav#topNav button:hover {
  background: var(--color-bg-hover);
  color: var(--color-text-1);
}

nav#topNav button.active {
  background: var(--khc-primary-50);
  color: var(--color-primary);
  font-weight: 600;
}

.appbar .actions {
  display: flex;
  align-items: center;
  gap: var(--space-2);
}

/* ── Main Content Container ── */
.main {
  width: 100%;
  max-width: 1184px;
  margin: 0 auto;
  padding: var(--space-5) var(--space-4);
  flex: 1;
}

.panel {
  display: none;
}
.panel.active {
  display: block;
  animation: fadeIn 0.15s ease-out;
}

@keyframes fadeIn {
  from { opacity: 0; transform: translateY(3px); }
  to { opacity: 1; transform: translateY(0); }
}

/* ── Section & Headers ── */
.section {
  margin-bottom: var(--space-5);
}

.section-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: var(--space-3);
  gap: var(--space-3);
}

.section-title {
  font-size: var(--font-size-h3);
  font-weight: 600;
  color: var(--color-text-1);
  display: flex;
  align-items: center;
  gap: var(--space-2);
}

.section-desc {
  font-size: 12px;
  color: var(--color-text-2);
  margin-top: 2px;
}

/* ── Cards & Stats ── */
.card {
  background: var(--color-bg-card);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  box-shadow: var(--shadow-1);
  overflow: hidden;
  margin-bottom: var(--space-4);
  transition: box-shadow 0.15s;
}

.card:hover {
  box-shadow: var(--shadow-2);
}

.card-pad {
  padding: 20px 24px;
}

.card-head {
  padding: 14px 20px;
  border-bottom: 1px solid var(--color-border);
  background: var(--khc-neutral-50);
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-3);
}

.card-head h3 {
  font-size: 14px;
  font-weight: 600;
  color: var(--color-text-1);
}

.card-head .meta {
  font-size: 12px;
  color: var(--color-text-2);
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: var(--space-3);
  margin-bottom: var(--space-4);
}

.stat-card, .stat {
  background: var(--color-bg-card);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  padding: 16px 20px;
  box-shadow: var(--shadow-1);
}

.stat-label {
  display: block;
  font-size: var(--font-size-caption);
  color: var(--color-text-3);
  font-weight: 500;
  margin-bottom: var(--space-1);
}

.stat-value {
  display: block;
  font-size: 24px;
  font-weight: 700;
  color: var(--color-text-1);
  font-variant-numeric: tabular-nums;
  line-height: 1.2;
}

.stat-sub {
  display: block;
  font-size: 11px;
  color: var(--color-text-3);
  margin-top: 4px;
}

/* ── Buttons ── */
.btn {
  box-sizing: border-box;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  border: 1px solid transparent;
  border-radius: var(--radius-sm);
  height: 32px;
  padding: 6px 14px;
  font-family: var(--font-body);
  font-size: 13px;
  font-weight: 500;
  line-height: 1;
  white-space: nowrap;
  cursor: pointer;
  flex-shrink: 0;
  user-select: none;
  transition: filter 0.15s, background 0.15s, border-color 0.15s;
}

.btn-primary {
  background: var(--color-primary);
  color: #fff;
  border-color: var(--color-primary);
}
.btn-primary:not(:disabled):hover {
  filter: brightness(1.08);
}
.btn-primary:not(:disabled):active {
  filter: brightness(0.92);
}

.btn-secondary, .btn-ghost-border {
  background: #fff;
  color: var(--color-text-2);
  border-color: var(--color-border);
}
.btn-secondary:not(:disabled):hover, .btn-ghost-border:not(:disabled):hover {
  background: var(--color-bg-hover);
  border-color: var(--color-border-strong);
  color: var(--color-text-1);
}

.btn-danger {
  background: var(--color-danger);
  color: #fff;
  border-color: var(--color-danger);
}
.btn-danger:not(:disabled):hover {
  filter: brightness(1.08);
}
.btn-danger:not(:disabled):active {
  filter: brightness(0.92);
}

.btn-ghost {
  background: transparent;
  color: var(--color-text-2);
  border-color: transparent;
  box-shadow: none;
}
.btn-ghost:not(:disabled):hover {
  background: var(--color-bg-hover);
  color: var(--color-text-1);
}

.btn-sm, .btn-small {
  height: 28px;
  padding: 4px 10px;
  font-size: 12px;
}

.btn-icon {
  width: 32px;
  height: 32px;
  padding: 0;
  border-radius: var(--radius-sm);
  background: #fff;
  border: 1px solid var(--color-border);
  color: var(--color-text-2);
}
.btn-icon:hover {
  background: var(--color-bg-hover);
  color: var(--color-text-1);
}

.btn:disabled {
  opacity: 0.45;
  cursor: not-allowed;
  pointer-events: none;
}

/* ── Badges ── */
.badge {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 2px 10px;
  font-size: 12px;
  font-weight: 500;
  line-height: 1.5;
  border-radius: 10px;
  white-space: nowrap;
  flex-shrink: 0;
}

.badge-success, .b-done {
  background: var(--khc-success-50);
  color: var(--color-success);
}

.badge-primary, .b-running {
  background: var(--khc-primary-50);
  color: var(--color-primary);
}

.badge-warning, .b-canceled {
  background: var(--khc-warning-50);
  color: var(--color-warning);
}

.badge-danger, .badge-error, .b-failed {
  background: var(--khc-danger-50);
  color: var(--color-danger);
}

.badge-neutral, .b-queued {
  background: var(--khc-neutral-100);
  color: var(--color-text-2);
}

.badge-info, .b-info {
  background: var(--khc-info-50);
  color: var(--color-info);
}

/* ── Forms ── */
.form-group, .form-field {
  margin-bottom: var(--space-4);
}

.form-label {
  display: block;
  font-size: 12px;
  font-weight: 500;
  color: var(--color-text-2);
  margin-bottom: var(--space-1);
}

.form-control, input[type="text"], input[type="password"], input[type="search"], select, textarea {
  width: 100%;
  height: 40px;
  padding: 8px 12px;
  border: 1px solid var(--color-border-strong);
  border-radius: var(--radius-sm);
  font-size: 13px;
  color: var(--color-text-1);
  background: #fff;
  outline: none;
  transition: border-color 0.15s, box-shadow 0.15s;
}

textarea.form-control {
  height: auto;
  min-height: 80px;
}

.form-control:focus, input:focus, select:focus, textarea:focus {
  border-color: var(--color-primary);
  box-shadow: 0 0 0 3px rgba(22, 100, 255, 0.12);
}

.form-control:disabled, input:disabled, select:disabled {
  background: var(--color-bg-page);
  color: var(--color-text-3);
  cursor: not-allowed;
}

.checkbox {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  user-select: none;
  font-size: 13px;
}

.checkbox input[type="checkbox"] {
  width: 16px;
  height: 16px;
  margin: 0;
  accent-color: var(--color-primary);
  cursor: pointer;
}

/* ── Tables ── */
.table-wrap {
  width: 100%;
  overflow-x: auto;
}

table, .tbl {
  width: 100%;
  border-collapse: collapse;
  background: var(--color-bg-card);
  font-size: 13px;
}

th, .tbl th {
  background: var(--khc-neutral-50);
  color: var(--color-text-2);
  font-size: 12px;
  font-weight: 500;
  text-align: left;
  padding: 10px 12px;
  border-bottom: 1px solid var(--color-border);
  white-space: nowrap;
}

td, .tbl td {
  padding: 10px 12px;
  color: var(--color-text-1);
  border-bottom: 1px solid var(--color-border);
  transition: background 0.15s;
  vertical-align: middle;
}

tr:last-child td, .tbl tbody tr:last-child td {
  border-bottom: none;
}

tr:hover td, .tbl tbody tr:hover td {
  background: var(--color-bg-hover);
}

/* ── Provider Rows & Chips ── */
.provider-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 20px;
  border-bottom: 1px solid var(--color-border);
  background: #fff;
  transition: background 0.15s;
}
.provider-row:last-child {
  border-bottom: none;
}
.provider-row:hover {
  background: var(--color-bg-hover);
}

.key-chip {
  display: inline-block;
  padding: 2px 8px;
  border-radius: var(--radius-sm);
  background: var(--khc-neutral-100);
  font-family: var(--font-mono);
  font-size: 12px;
  color: var(--color-text-2);
  border: 1px solid var(--color-border);
}

/* ── Code Blocks ── */
.code-block {
  position: relative;
  background: var(--khc-neutral-900);
  color: #E2E8F0;
  border-radius: var(--radius-md);
  padding: 16px 20px;
  font-family: var(--font-mono);
  font-size: 12px;
  line-height: 1.6;
  overflow-x: auto;
  margin-bottom: var(--space-4);
}

.code-block pre {
  margin: 0;
  white-space: pre-wrap;
  word-break: break-all;
}

.copy-btn {
  position: absolute;
  top: 10px;
  right: 12px;
  background: rgba(255, 255, 255, 0.12);
  color: #fff;
  border: 1px solid rgba(255, 255, 255, 0.2);
  border-radius: var(--radius-sm);
  padding: 3px 8px;
  font-size: 11px;
  cursor: pointer;
  transition: background 0.15s;
}
.copy-btn:hover {
  background: rgba(255, 255, 255, 0.25);
}

/* ── Modals & Overlays ── */
.modal, .login-overlay {
  position: fixed;
  inset: 0;
  display: none;
  align-items: center;
  justify-content: center;
  background: rgba(15, 23, 42, 0.6);
  backdrop-filter: blur(4px);
  z-index: 1000;
  padding: 16px;
}

.modal.show, .login-overlay.show {
  display: flex;
}

.modal-box, .login-box {
  width: 440px;
  max-width: 100%;
  background: var(--color-bg-card);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-4);
  overflow: hidden;
  animation: modalIn 0.2s ease-out;
}

@keyframes modalIn {
  from { opacity: 0; transform: scale(0.96) translateY(-4px); }
  to { opacity: 1; transform: scale(1) translateY(0); }
}

.modal-head {
  padding: 16px 20px;
  border-bottom: 1px solid var(--color-border);
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.modal-head h3 {
  font-size: 15px;
  font-weight: 600;
  color: var(--color-text-1);
}
.modal-close {
  background: none;
  border: none;
  font-size: 12px;
  color: var(--color-text-3);
  cursor: pointer;
  line-height: 1;
  padding: 4px 6px;
  border-radius: var(--radius-sm);
}
.modal-close:hover {
  color: var(--color-text-1);
  background: var(--color-bg-hover);
}

.modal-body {
  padding: 20px;
}

.modal-foot {
  padding: 12px 20px;
  border-top: 1px solid var(--color-border);
  background: var(--khc-neutral-50);
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: var(--space-2);
}

/* ── Login Box Custom ── */
.login-box {
  padding: 36px 32px;
}
.login-box h2 {
  font-size: var(--font-size-h1);
  font-weight: 700;
  color: var(--color-text-1);
  margin-bottom: 6px;
  display: flex;
  align-items: center;
  gap: 8px;
}
.login-box p {
  color: var(--color-text-2);
  font-size: 13px;
  margin-bottom: 24px;
}

/* ── Toast Notifications ── */
.toast-container {
  position: fixed;
  bottom: 24px;
  right: 24px;
  z-index: 2000;
  display: flex;
  flex-direction: column;
  gap: 8px;
  pointer-events: none;
}

.toast {
  background: var(--khc-neutral-900);
  color: #fff;
  padding: 10px 16px;
  border-radius: var(--radius-md);
  font-size: 13px;
  box-shadow: var(--shadow-3);
  opacity: 0;
  transform: translateY(12px);
  transition: opacity 0.2s, transform 0.2s;
  pointer-events: auto;
  max-width: 380px;
  border-left: 4px solid var(--color-primary);
}

.toast.show {
  opacity: 1;
  transform: translateY(0);
}

.toast.ok {
  border-left-color: var(--color-success);
}

.toast.err {
  border-left-color: var(--color-danger);
}

/* ── Helpers ── */
.flex-between {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.text-secondary {
  color: var(--color-text-2);
}
.text-sm {
  font-size: 12px;
}
.mt-1 { margin-top: 4px; }
.mt-2 { margin-top: 8px; }
.mb-2 { margin-bottom: 8px; }
.mb-3 { margin-bottom: 12px; }
.mb-4 { margin-bottom: 16px; }
.empty {
  text-align: center;
  padding: 28px;
  color: var(--color-text-3);
  font-size: 13px;
}

/* ── Responsive ── */
@media (max-width: 860px) {
  .stats-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
  .appbar {
    padding: 0 16px;
    gap: 12px;
  }
  nav#topNav button {
    padding: 4px 8px;
    font-size: 12px;
  }
}

</style>
</head>
<body>

<!-- Login Overlay -->
<div id="loginOverlay" class="login-overlay">
  <div class="login-box">
    <h2>OCRProxy</h2>
    <p>OCRProxy EdgeOne 控制台</p>
    <div class="form-group">
      <label class="form-label">管理员凭证 (PROXY_API_KEY)</label>
      <input type="password" id="loginKey" class="form-control" placeholder="请输入 PROXY_API_KEY" onkeydown="if(event.key==='Enter')doLogin()">
    </div>
    <button class="btn btn-primary" style="width:100%;padding:10px;" onclick="doLogin()">进入控制台</button>
    <div id="loginErr" style="display:none;margin-top:14px;padding:10px;border-radius:var(--radius-sm);background:var(--error-soft);border:1px solid var(--error-border);color:var(--error);font-size:12px;text-align:center;"></div>
  </div>
</div>

<!-- App -->
<div id="app" class="app">
  <header class="appbar">
    <div class="brand-title">
      <span class="brand-logo">O</span>
      <span>OCRProxy</span>
      <span class="brand-badge">EdgeOne 边缘版</span>
    </div>
    <nav id="topNav">
      <button class="active" onclick="switchTab('dashboard')">概览</button>
      <button onclick="switchTab('agents')">Agent 模型</button>
      <button onclick="switchTab('providers')">供应商</button>
      <button onclick="switchTab('state')">状态</button>
      <button onclick="switchTab('raw')">JSON 配置</button>
      <button onclick="switchTab('access')">接入说明</button>
    </nav>
    <div class="actions">
      <button class="btn btn-secondary btn-sm" onclick="exportConfigJson()" title="导出当前完整配置为 JSON 备份文件">导出备份</button>
      <button class="btn btn-secondary btn-sm" onclick="triggerImportConfig()" title="从本地 JSON 备份文件恢复配置">导入配置</button>
      <button class="btn btn-secondary btn-sm" onclick="clearAllCooldowns()" title="清除当前所有 Key 的冷却与失败状态">清除冷却</button>
      <button class="btn btn-secondary btn-sm" onclick="loadAllData()" title="刷新数据">刷新</button>
      <button class="btn btn-ghost btn-sm" onclick="doLogout()">退出</button>
    </div>
    <input type="file" id="configFileImportInput" accept=".json,application/json" style="display:none;" onchange="handleConfigFileImport(event)">
  </header>

  <main class="main">
    <!-- Panel 1: Dashboard -->
    <div id="panel-dashboard" class="panel active">
      <div class="section mb-4">
        <div class="section-head">
          <div class="section-title">状态总览</div>
          <span id="configSourceBadge" class="badge badge-success">KV 同步中</span>
        </div>
        <div class="stats-grid">
          <div class="stat-card">
            <div class="stat-label">已配置 Agent 模型</div>
            <div class="stat-value" id="statModelCount">0</div>
            <div class="stat-sub">OpenAI 兼容路由</div>
          </div>
          <div class="stat-card">
            <div class="stat-label">候选 Key 总数</div>
            <div class="stat-value" id="statTotalKeys">0</div>
            <div class="stat-sub">多 Key 轮询池</div>
          </div>
          <div class="stat-card">
            <div class="stat-label">冷却中 Key</div>
            <div class="stat-value" id="statCooldowns" style="color:var(--color-primary);">0</div>
            <div class="stat-sub">故障避让与恢复</div>
          </div>
          <div class="stat-card">
            <div class="stat-label">运行模式</div>
            <div class="stat-value" style="font-size:20px;color:var(--color-success);" id="statRuntime">Edge V8</div>
            <div class="stat-sub" id="statLastModified">3200+ 边缘节点</div>
          </div>
        </div>
      </div>

      <!-- Quick Models Overview -->
      <div class="section">
        <div class="section-head">
          <div class="section-title">模型状态</div>
          <button class="btn btn-primary btn-sm" onclick="switchTab('agents')">管理全部模型</button>
        </div>
        <div class="card table-wrap">
          <table>
            <thead><tr><th>模型名称</th><th>候选 Key 数量</th><th>供应商</th><th>上游映射</th></tr></thead>
            <tbody id="quickModelsBody"></tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Panel 2: Agent Models -->
    <div id="panel-agents" class="panel">
      <div class="section">
        <div class="section-head">
          <div>
            <div class="section-title">Agent 模型</div>
            <div class="section-desc">配置 Agent 模型与候选 Key 绑定</div>
          </div>
          <button class="btn btn-primary btn-sm" onclick="openAddModelModal()">新增模型</button>
        </div>
        <div id="agentModelsBox"></div>
      </div>
    </div>

    <!-- Panel 3: Providers & Keys -->
    <div id="panel-providers" class="panel">
      <div class="section">
        <div class="section-head">
          <div>
            <div class="section-title">供应商</div>
            <div class="section-desc">配置上游 Base URL 与 API Key</div>
          </div>
          <button class="btn btn-primary btn-sm" onclick="openAddProviderModal()">新增供应商</button>
        </div>
        <div id="providersBox"></div>
      </div>
    </div>

    <!-- Panel 4: KV State & IP Check -->
    <div id="panel-state" class="panel">
      <div class="section">
        <div class="section-head">
          <div>
            <div class="section-title">出口 IP</div>
            <div class="section-desc">探测边缘节点出口公网 IP</div>
          </div>
          <button class="btn btn-primary btn-sm" onclick="probeEgressIp()">探测 IP</button>
        </div>
        <div class="card card-pad mb-3" id="egressIpBox">
          <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:16px;">
            <div><span class="text-secondary text-sm">客户端 IP</span><div class="mono mt-2" id="ipClient">—</div></div>
            <div><span class="text-secondary text-sm">出口 IP</span><div class="mono mt-2" style="font-weight:700;color:var(--color-primary);" id="ipEgress">—</div></div>
            <div><span class="text-secondary text-sm">节点 UUID</span><div class="mono mt-2" id="ipNode">—</div></div>
            <div><span class="text-secondary text-sm">地理位置</span><div class="mono mt-2" id="ipGeo">—</div></div>
          </div>
        </div>
      </div>

      <div class="section">
        <div class="section-head">
          <div>
            <div class="section-title">Key 冷却状态</div>
            <div class="section-desc">展示 Key 冷却状态与连续失败计数</div>
          </div>
          <button class="btn btn-danger btn-sm" onclick="clearAllCooldowns()">清空冷却</button>
        </div>
        <div class="card table-wrap">
          <table>
            <thead><tr><th>供应商</th><th>Key 别名</th><th>状态</th><th>连续失败</th><th>冷却到期时间</th></tr></thead>
            <tbody id="stateTableBody"></tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Panel 5: Raw JSON Editor -->
    <div id="panel-raw" class="panel">
      <div class="section">
        <div class="section-head">
          <div>
            <div class="section-title">JSON 配置</div>
            <div class="section-desc">编辑完整路由与凭证 JSON，保存后写入 KV 生效</div>
          </div>
          <div style="display:flex;gap:8px;flex-wrap:wrap;">
            <button class="btn btn-ghost btn-sm" onclick="exportConfigJson()">导出备份</button>
            <button class="btn btn-ghost btn-sm" onclick="triggerImportConfig()">导入配置</button>
            <button class="btn btn-ghost btn-sm" onclick="formatRawJson()">格式化 JSON</button>
            <button class="btn btn-primary btn-sm" onclick="saveRawJson()">保存配置</button>
          </div>
        </div>
        <div class="card card-pad">
          <textarea id="rawJsonText" class="form-control" spellcheck="false" style="min-height:480px;font-family:var(--font-mono);font-size:12px;"></textarea>
          <div id="rawJsonErr" style="display:none;margin-top:10px;color:var(--error);font-size:12px;"></div>
        </div>
      </div>
    </div>

    <!-- Panel 6: Access & Docs -->
    <div id="panel-access" class="panel">
      <div class="section">
        <div class="section-title mb-2">接入网关</div>
        <div class="card card-pad mb-3">
          <div class="flex-between mb-2"><span class="text-secondary">Base URL 接口地址</span><span class="mono" id="accBaseUrl">—</span></div>
          <div class="flex-between"><span class="text-secondary">已配置 Agent 模型</span><span class="mono" id="accModelsList">—</span></div>
        </div>
        <div class="section-title mb-2">Python SDK 示例</div>
        <div class="code-block"><button class="copy-btn" onclick="copySnippet('accPy')">复制</button><pre id="accPy"></pre></div>
        <div class="section-title mb-2">cURL 示例</div>
        <div class="code-block"><button class="copy-btn" onclick="copySnippet('accCurl')">复制</button><pre id="accCurl"></pre></div>
      </div>
    </div>
  </main>
</div>

<!-- Modal: Provider -->
<div id="providerModal" class="modal">
  <div class="modal-box" style="width:560px;max-height:90vh;overflow-y:auto;">
    <div class="modal-head">
      <h3 id="providerModalTitle">新增供应商</h3>
      <button class="modal-close" onclick="closeModal('providerModal')">关闭</button>
    </div>
    <div class="modal-body">
      <div class="form-group" id="presetSelectGroup">
        <label class="form-label">预置模板</label>
        <select id="m_prov_preset" class="form-control" onchange="onPresetSelected()">
          <option value="">-- 自定义配置 (手动输入) --</option>
          <option value="google">Google AI Studio (Gemini 2.5 / 3 / 3.5 系列)</option>
          <option value="sensenova">商汤日日新 (SenseNova GLM-5.2 / DeepSeek)</option>
          <option value="stepfun">阶跃星辰 (StepFun Step-3.7-Flash / Step-2)</option>
          <option value="siliconflow">硅基流动 (SiliconFlow DeepSeek / Qwen)</option>
          <option value="tokenrhythm">TokenRhythm (Claude / GPT 系列)</option>
          <option value="deepseek">DeepSeek 官方开放平台</option>
          <option value="openai">OpenAI 官方 / 标准中转</option>
        </select>
        <div id="m_prov_desc" style="display:none;margin-top:6px;font-size:12px;color:var(--color-text-2);padding:6px 10px;background:var(--color-bg-page);border-radius:var(--radius-sm);"></div>
      </div>

      <div class="form-group">
        <label class="form-label">供应商标识 (英文标识，如 google, sensenova)</label>
        <input type="text" id="m_prov_name" class="form-control" placeholder="如 google">
      </div>
      <div class="form-group">
        <label class="form-label">Base URL (API 端点地址)</label>
        <input type="text" id="m_prov_url" class="form-control" placeholder="如 https://generativelanguage.googleapis.com/v1beta/openai">
      </div>

      <div id="m_prov_init_key_wrap" class="form-group" style="margin-top:14px;">
        <label class="form-label">初始 API Key（可选）</label>
        <div style="display:grid;grid-template-columns:120px 1fr;gap:8px;">
          <input type="text" id="m_prov_key_label" class="form-control" placeholder="别名(如主账号)" value="default">
          <input type="text" id="m_prov_key_val" class="form-control" placeholder="API Key 密钥明文 (sk-...)">
        </div>
      </div>

      <div id="m_prov_models_wrap" class="form-group" style="display:none;margin-top:16px;">
        <label class="form-label">自动创建并绑定推荐模型</label>
        <div id="m_prov_models_list" style="display:flex;flex-direction:column;gap:6px;max-height:180px;overflow-y:auto;background:var(--color-bg-page);padding:10px;border-radius:var(--radius-sm);border:1px solid var(--color-border);"></div>
      </div>
    </div>
    <div class="modal-foot">
      <button class="btn btn-ghost" onclick="closeModal('providerModal')">取消</button>
      <button class="btn btn-primary" onclick="saveProviderModal()">保存配置</button>
    </div>
  </div>
</div>

<!-- Modal: Key -->
<div id="keyModal" class="modal">
  <div class="modal-box">
    <div class="modal-head">
      <h3 id="keyModalTitle">新增 API Key</h3>
      <button class="modal-close" onclick="closeModal('keyModal')">关闭</button>
    </div>
    <div class="modal-body">
      <input type="hidden" id="m_key_prov">
      <div class="form-group">
        <label class="form-label">Key 别名</label>
        <input type="text" id="m_key_label" class="form-control" placeholder="如 自己">
      </div>
      <div class="form-group">
        <label class="form-label">API Key 密钥明文 (sk-...)</label>
        <input type="text" id="m_key_val" class="form-control" placeholder="sk-...">
      </div>
    </div>
    <div class="modal-foot">
      <button class="btn btn-ghost" onclick="closeModal('keyModal')">取消</button>
      <button class="btn btn-primary" onclick="saveKeyModal()">保存 Key</button>
    </div>
  </div>
</div>

<!-- Modal: Agent Model -->
<div id="agentModal" class="modal">
  <div class="modal-box" style="width:540px;">
    <div class="modal-head">
      <h3 id="agentModalTitle">新增模型</h3>
      <button class="modal-close" onclick="closeModal('agentModal')">关闭</button>
    </div>
    <div class="modal-body">
      <div class="form-group">
        <label class="form-label">模型名称 (如 glm-5.2, step-3.7-flash, gemini-3.5-flash)</label>
        <input type="text" id="m_model_name" class="form-control" placeholder="如 glm-5.2">
      </div>
      <div class="form-group">
        <label class="form-label">上游模型 (可选，留空则与模型名称一致)</label>
        <input type="text" id="m_upstream_model" class="form-control" placeholder="如 deepseek-v4-flash-0731">
      </div>
      <div class="form-group">
        <label class="form-label">候选 Key 绑定序列 (勾选要参与该模型轮换的 Key)</label>
        <div id="m_bindings_container" style="max-height:200px;overflow-y:auto;border:1px solid var(--color-border);border-radius:var(--radius-sm);padding:10px;background:var(--color-bg-page);"></div>
      </div>
    </div>
    <div class="modal-foot">
      <button class="btn btn-ghost" onclick="closeModal('agentModal')">取消</button>
      <button class="btn btn-primary" onclick="saveAgentModal()">保存模型</button>
    </div>
  </div>
</div>

<!-- Toast Container -->
<div id="toastContainer" class="toast-container"></div>

<script>
/**
 * admin.js — OCRProxy EdgeOne Admin UI Controller (VM-grade parity + Presets & Export/Import)
 */

let cfg = { providers: {}, agent_models: {} };
let cfgMeta = {};
let healthData = {};
let stateData = [];
let ipData = {};
let activeTab = 'dashboard';
let modelLatencyCache = {}; // { "provider:key": { latency_ms, status } }

const TOKEN_KEY = 'ocrproxy_edge_token';

// ---- Provider Presets Database -------------------------------------------
const PRESET_DEFINITIONS = {
  google: {
    id: 'google',
    name: 'Google AI Studio (Gemini)',
    base_url: 'https://generativelanguage.googleapis.com/v1beta/openai',
    description: 'Google 官方 Gemini 系列大模型，支持 Gemini 2.5 / 3 / 3.5+，已内置 Thinking Config 思考等级映射与 Schema 裁剪适配',
    recommended_models: [
      { name: 'gemini-3.5-flash', upstream: 'gemini-3.5-flash', desc: '最新高性价比推理模型 (支持 low/medium/high 思考等级)', checked: true },
      { name: 'gemini-3.5-pro', upstream: 'gemini-3.5-pro', desc: '最新旗舰强推理模型 (支持 low/high 思考等级)', checked: true },
      { name: 'gemini-2.5-flash', upstream: 'gemini-2.5-flash', desc: '经典多模态快速模型', checked: false },
      { name: 'gemini-2.5-pro', upstream: 'gemini-2.5-pro', desc: '经典多模态深度思考模型', checked: false },
    ]
  },
  sensenova: {
    id: 'sensenova',
    name: '商汤日日新 (SenseNova)',
    base_url: 'https://token.sensenova.cn/v1',
    description: '商汤日日新大模型开放平台，支持 GLM-5.2、DeepSeek-V3/R1 等，原生支持 reasoning_effort 思考控制',
    recommended_models: [
      { name: 'glm-5.2', upstream: 'GLM-5.2', desc: '智谱/商汤最新 GLM-5.2 旗舰推理大模型', checked: true },
      { name: 'deepseek-v3', upstream: 'DeepSeek-V3', desc: 'DeepSeek-V3 基础推理模型', checked: false },
      { name: 'deepseek-r1', upstream: 'DeepSeek-R1', desc: 'DeepSeek-R1 深度思考推理模型', checked: false },
    ]
  },
  stepfun: {
    id: 'stepfun',
    name: '阶跃星辰 (StepFun)',
    base_url: 'https://api.stepfun.com/step_plan',
    description: '阶跃星辰大模型平台，已自动适配 reasoning_effort none->low 降级与 deepseek-style 思考格式注入',
    recommended_models: [
      { name: 'step-3.7-flash', upstream: 'step-3.7-flash', desc: '阶跃最新闪电高速推理大模型', checked: true },
      { name: 'step-2-16k', upstream: 'step-2-16k', desc: '阶跃 Step-2 旗舰大模型', checked: false },
    ]
  },
  siliconflow: {
    id: 'siliconflow',
    name: '硅基流动 (SiliconFlow)',
    base_url: 'https://api.siliconflow.cn/v1',
    description: '硅基流动高并发推理平台，包含 DeepSeek-V3/R1、Qwen2.5 等海量开源模型',
    recommended_models: [
      { name: 'deepseek-ai/DeepSeek-V3', upstream: 'deepseek-ai/DeepSeek-V3', desc: 'DeepSeek-V3 全尺寸旗舰模型', checked: true },
      { name: 'deepseek-ai/DeepSeek-R1', upstream: 'deepseek-ai/DeepSeek-R1', desc: 'DeepSeek-R1 全尺寸深度思考模型', checked: false },
      { name: 'Qwen/Qwen2.5-72B-Instruct', upstream: 'Qwen/Qwen2.5-72B-Instruct', desc: '通义千问 72B Instruct 指令模型', checked: false },
    ]
  },
  tokenrhythm: {
    id: 'tokenrhythm',
    name: 'TokenRhythm',
    base_url: 'https://api.tokenrhythm.com/v1',
    description: 'TokenRhythm 聚合大模型路由网关，已自动适配 tool_choice 格式转换',
    recommended_models: [
      { name: 'claude-3-5-sonnet-20241022', upstream: 'claude-3-5-sonnet-20241022', desc: 'Claude 3.5 Sonnet 强编程模型', checked: true },
      { name: 'gpt-4o', upstream: 'gpt-4o', desc: 'OpenAI GPT-4o 旗舰全能模型', checked: false },
    ]
  },
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek 官方开放平台',
    base_url: 'https://api.deepseek.com/v1',
    description: 'DeepSeek 官方 API，原生支持 reasoning_content 深度思考与前缀缓存',
    recommended_models: [
      { name: 'deepseek-chat', upstream: 'deepseek-chat', desc: 'DeepSeek-V3 快速对话大模型', checked: true },
      { name: 'deepseek-reasoner', upstream: 'deepseek-reasoner', desc: 'DeepSeek-R1 深度思考推理大模型', checked: true },
    ]
  },
  openai: {
    id: 'openai',
    name: 'OpenAI 官方 / 标准中转',
    base_url: 'https://api.openai.com/v1',
    description: 'OpenAI 官方 API 或标准兼容中转网关',
    recommended_models: [
      { name: 'gpt-4o', upstream: 'gpt-4o', desc: 'OpenAI GPT-4o 旗舰全能大模型', checked: true },
      { name: 'gpt-4o-mini', upstream: 'gpt-4o-mini', desc: 'OpenAI GPT-4o-mini 高性价比快速模型', checked: true },
      { name: 'o3-mini', upstream: 'o3-mini', desc: 'OpenAI 最新 o3-mini 快速推理思考模型', checked: false },
      { name: 'o1', upstream: 'o1', desc: 'OpenAI o1 深度思考推理旗舰模型', checked: false },
    ]
  }
};

function getKey() {
  return localStorage.getItem(TOKEN_KEY) || '';
}

function setKey(k) {
  localStorage.setItem(TOKEN_KEY, k);
}

function clearKey() {
  localStorage.removeItem(TOKEN_KEY);
}

function toast(msg, type = 'ok') {
  const container = document.getElementById('toastContainer');
  if (!container) return;
  const el = document.createElement('div');
  el.className = \`toast \${type}\`;
  el.textContent = msg;
  container.appendChild(el);
  setTimeout(() => el.classList.add('show'), 10);
  setTimeout(() => {
    el.classList.remove('show');
    setTimeout(() => el.remove(), 300);
  }, 3000);
}

function copySnippet(elementId) {
  const el = document.getElementById(elementId);
  if (!el) return;
  const text = el.textContent || '';
  navigator.clipboard.writeText(text).then(() => {
    toast('已复制到剪贴板', 'ok');
  }).catch(() => {
    toast('复制失败，请手动复制', 'err');
  });
}

// ---- API wrapper ---------------------------------------------------------
async function api(method, path, body = null) {
  const token = getKey();
  const headers = { 'Content-Type': 'application/json' };
  if (token) headers['Authorization'] = \`Bearer \${token}\`;

  const res = await fetch(path, {
    method,
    headers,
    body: body ? JSON.stringify(body) : null,
  });

  const text = await res.text();
  let data = null;
  try {
    data = JSON.parse(text);
  } catch {
    data = { raw: text };
  }

  if (res.status === 401) {
    clearKey();
    showLoginOverlay('凭证无效或已过期，请重新登录');
    throw new Error('未授权 (401)');
  }
  if (!res.ok) {
    throw new Error(data?.error?.message || data?.error || \`HTTP \${res.status}\`);
  }
  return data;
}

// ---- Navigation / Tabs ---------------------------------------------------
function switchTab(tabId) {
  activeTab = tabId;
  document.querySelectorAll('#topNav button').forEach(b => b.classList.remove('active'));
  const btn = Array.from(document.querySelectorAll('#topNav button')).find(b => b.getAttribute('onclick')?.includes(tabId));
  if (btn) btn.classList.add('active');

  document.querySelectorAll('.panel').forEach(p => p.classList.remove('active'));
  const panel = document.getElementById(\`panel-\${tabId}\`);
  if (panel) panel.classList.add('active');

  if (tabId === 'raw') renderRawJson();
  if (tabId === 'access') renderAccess();
  if (tabId === 'state') probeEgressIp();
}

// ---- Login Flow ----------------------------------------------------------
function showLoginOverlay(errText = '') {
  document.getElementById('loginOverlay').style.display = 'flex';
  document.getElementById('app').style.display = 'none';
  const err = document.getElementById('loginErr');
  if (errText) {
    err.textContent = errText;
    err.style.display = 'block';
  } else {
    err.style.display = 'none';
  }
}

function hideLoginOverlay() {
  document.getElementById('loginOverlay').style.display = 'none';
  document.getElementById('app').style.display = 'flex';
}

async function doLogin() {
  const input = document.getElementById('loginKey').value.trim();
  if (!input && !getKey()) {
    showLoginOverlay('请输入 PROXY_API_KEY');
    return;
  }
  if (input) setKey(input);

  try {
    await loadAllData();
    hideLoginOverlay();
    toast('登录成功', 'ok');
  } catch (e) {
    showLoginOverlay('验证失败: ' + (e?.message || e));
  }
}

function doLogout() {
  clearKey();
  showLoginOverlay();
}

// ---- Data Fetching -------------------------------------------------------
async function loadAllData() {
  try {
    const [cfgRes, healthRes, stateRes] = await Promise.all([
      api('GET', '/api/config'),
      api('GET', '/health').catch(() => ({})),
      api('GET', '/api/state').catch(() => ({ cooldowns: [] })),
    ]);

    cfg = cfgRes.config || cfgRes;
    cfgMeta = {
      source: cfgRes.source || 'EdgeOne KV',
      lastModified: cfgRes.last_modified,
    };
    healthData = healthRes;
    stateData = stateRes.cooldowns || [];

    renderAll();
  } catch (e) {
    console.error('Failed to load data', e);
    throw e;
  }
}

// ---- Egress IP probe -----------------------------------------------------
async function probeEgressIp() {
  const clientEl = document.getElementById('ipClient');
  const egressEl = document.getElementById('ipEgress');
  const nodeEl = document.getElementById('ipNode');
  const geoEl = document.getElementById('ipGeo');

  if (clientEl) clientEl.textContent = '探测中...';
  if (egressEl) egressEl.textContent = '探测中...';

  try {
    const data = await api('GET', '/check-ip');
    ipData = data;
    if (clientEl) clientEl.textContent = data.client_ip || '—';
    if (egressEl) egressEl.textContent = data.egress_ip || '—';
    if (nodeEl) nodeEl.textContent = data.node_uuid || '—';
    if (geoEl) geoEl.textContent = \`\${data.geo?.country || ''} \${data.geo?.region || ''} \${data.geo?.city || ''}\`.trim() || '边缘节点网络';
  } catch (e) {
    if (clientEl) clientEl.textContent = '获取失败';
    if (egressEl) egressEl.textContent = '获取失败';
  }
}

// ---- Rendering -----------------------------------------------------------
function renderAll() {
  renderDashboard();
  renderAgentModels();
  renderProviders();
  renderStateTable();
  renderRawJson();
  renderAccess();
}

function renderDashboard() {
  const models = Object.keys(cfg.agent_models || {});
  const providers = cfg.providers || {};
  let totalKeys = 0;
  for (const p of Object.values(providers)) {
    totalKeys += Object.keys(p.keys || {}).length;
  }

  const activeCooldowns = stateData.filter(s => s.expiresAt > Date.now());

  document.getElementById('statModelCount').textContent = models.length;
  document.getElementById('statTotalKeys').textContent = totalKeys;
  document.getElementById('statCooldowns').textContent = activeCooldowns.length;

  const badge = document.getElementById('configSourceBadge');
  if (badge) {
    badge.textContent = \`\${cfgMeta.source || 'KV'} 同步中\`;
  }

  // Quick models table
  const tbody = document.getElementById('quickModelsBody');
  if (tbody) {
    tbody.innerHTML = '';
    if (models.length === 0) {
      tbody.innerHTML = '<tr><td colspan="4" class="text-secondary" style="text-align:center;padding:24px;">暂未配置 Agent 模型</td></tr>';
      return;
    }

    for (const m of models) {
      const item = cfg.agent_models[m];
      const keys = item.keys || [];
      const tr = document.createElement('tr');
      tr.innerHTML = \`
        <td style="font-weight:600;"><span class="mono">\${m}</span></td>
        <td class="mono text-secondary">\${item.upstream_model || m}</td>
        <td><span class="badge badge-neutral">\${keys.length} 个候选 Key</span></td>
        <td>
          <button class="btn btn-ghost btn-sm" onclick="switchTab('agents')">查看</button>
        </td>
      \`;
      tbody.appendChild(tr);
    }
  }
}

function renderStateTable() {
  const tbody = document.getElementById('stateTableBody');
  if (!tbody) return;
  tbody.innerHTML = '';

  if (!stateData || stateData.length === 0) {
    tbody.innerHTML = '<tr><td colspan="5" class="text-secondary" style="text-align:center;padding:24px;">无冷却记录</td></tr>';
    return;
  }

  const now = Date.now();
  for (const c of stateData) {
    const isCooling = c.expiresAt > now;
    const remainingSec = isCooling ? Math.round((c.expiresAt - now) / 1000) : 0;
    const expStr = isCooling ? \`\${remainingSec}s 后恢复\` : '已解冻';
    const badgeHtml = isCooling
      ? \`<span class="badge badge-warning">冷却中 (\${c.cooldownSec || remainingSec}s)</span>\`
      : \`<span class="badge badge-success">正常就绪</span>\`;

    const tr = document.createElement('tr');
    tr.innerHTML = \`
      <td style="font-weight:600;">\${c.provider}</td>
      <td class="mono">\${c.keyLabel}</td>
      <td>\${badgeHtml}</td>
      <td class="mono">\${c.failCount || 0} 次</td>
      <td class="mono">\${expStr}</td>
    \`;
    tbody.appendChild(tr);
  }
}

function renderAgentModels() {
  const box = document.getElementById('agentModelsBox');
  if (!box) return;
  box.innerHTML = '';
  const models = Object.keys(cfg.agent_models || {});

  if (models.length === 0) {
    box.innerHTML = '<div class="card card-pad empty">暂未配置 Agent 模型</div>';
    return;
  }

  for (const m of models) {
    const item = cfg.agent_models[m];
    const keys = item.keys || [];
    const card = document.createElement('div');
    card.className = 'card';

    let keysRowsHtml = '';
    keys.forEach((b, idx) => {
      const cacheKey = \`\${b.provider}:\${b.key}\`;
      const latInfo = modelLatencyCache[cacheKey];
      let latBadge = '';
      if (latInfo) {
        latBadge = latInfo.ok
          ? \`<span class="badge badge-success">\${latInfo.latency_ms}ms</span>\`
          : \`<span class="badge badge-error">\${latInfo.status}</span>\`;
      }

      keysRowsHtml += \`
        <div class="provider-row" style="padding:10px 16px;">
          <div style="display:flex;align-items:center;gap:10px;">
            <span class="badge badge-neutral">#\${idx+1}</span>
            <span style="font-weight:600;">\${b.provider}</span>
            <span class="key-chip">\${b.key}</span>
            \${latBadge}
          </div>
          <div style="display:flex;gap:6px;">
            <button class="btn btn-ghost btn-sm" onclick="testSingleKey('\${b.provider}', '\${b.key}')">探活</button>
            <button class="btn btn-danger btn-sm" onclick="removeModelKeyBinding('\${m}', \${idx})">移除</button>
          </div>
        </div>
      \`;
    });

    card.innerHTML = \`
      <div class="card-head">
        <div>
          <h3>\${m}</h3>
        <div class="meta mono mt-2">上游映射: \${item.upstream_model || m} · \${keys.length} 个 Key</div>
        </div>
        <div style="display:flex;gap:8px;">
          <button class="btn btn-primary btn-sm" onclick="openEditModelModal('\${m}')">编辑</button>
          <button class="btn btn-danger btn-sm" onclick="deleteModel('\${m}')">删除</button>
        </div>
      </div>
      <div style="background:var(--color-bg-page);">\${keysRowsHtml || '<div class="empty">暂未绑定 Key</div>'}</div>
    \`;
    box.appendChild(card);
  }
}

function renderProviders() {
  const box = document.getElementById('providersBox');
  if (!box) return;
  box.innerHTML = '';
  const providers = cfg.providers || {};
  const provNames = Object.keys(providers);

  if (provNames.length === 0) {
    box.innerHTML = '<div class="card card-pad empty">暂未配置供应商</div>';
    return;
  }

  for (const p of provNames) {
    const prov = providers[p];
    const keysObj = prov.keys || {};
    const keyLabels = Object.keys(keysObj);
    const card = document.createElement('div');
    card.className = 'card';

    let keysListHtml = '';
    keyLabels.forEach(k => {
      const val = keysObj[k];
      const masked = val ? \`\${val.slice(0, 6)}...\${val.slice(-4)}\` : '';
      const cacheKey = \`\${p}:\${k}\`;
      const latInfo = modelLatencyCache[cacheKey];
      let latBadge = '';
      if (latInfo) {
        latBadge = latInfo.ok
          ? \`<span class="badge badge-success">\${latInfo.latency_ms}ms</span>\`
          : \`<span class="badge badge-error">\${latInfo.status}</span>\`;
      }

      keysListHtml += \`
        <div class="provider-row" style="padding:10px 16px;">
          <div style="display:flex;align-items:center;gap:10px;">
            <span style="font-weight:600;">\${k}</span>
            <span class="mono text-secondary" style="font-size:12px;">\${masked}</span>
            \${latBadge}
          </div>
          <div style="display:flex;gap:6px;">
            <button class="btn btn-ghost btn-sm" onclick="testSingleKey('\${p}', '\${k}')">测试</button>
            <button class="btn btn-ghost btn-sm" onclick="openEditKeyModal('\${p}', '\${k}', '\${val}')">编辑</button>
            <button class="btn btn-danger btn-sm" onclick="deleteKey('\${p}', '\${k}')">删除</button>
          </div>
        </div>
      \`;
    });

    card.innerHTML = \`
      <div class="card-head">
        <div>
          <h3>\${p}</h3>
        <div class="meta mono mt-2">\${prov.base_url || '—'} · \${keyLabels.length} 个 Key</div>
        </div>
        <div style="display:flex;gap:8px;">
          <button class="btn btn-primary btn-sm" onclick="openAddKeyModal('\${p}')">+ 新增 Key</button>
          <button class="btn btn-danger btn-sm" onclick="deleteProvider('\${p}')">删除供应商</button>
        </div>
      </div>
      <div style="background:var(--color-bg-page);">\${keysListHtml || '<div class="empty">暂无 Key</div>'}</div>
    \`;
    box.appendChild(card);
  }
}

function renderRawJson() {
  const ta = document.getElementById('rawJsonText');
  if (ta) ta.value = JSON.stringify(cfg, null, 2);
}

function renderAccess() {
  const origin = window.location.origin;
  document.getElementById('accBaseUrl').textContent = \`\${origin}/v1\`;
  const models = Object.keys(cfg.agent_models || {});
  document.getElementById('accModelsList').textContent = models.join(', ') || '—';

  const pySample = \`from openai import OpenAI

client = OpenAI(
    api_key="\${getKey() || 'YOUR_PROXY_API_KEY'}",
    base_url="\${origin}/v1"
)

response = client.chat.completions.create(
    model="\${models[0] || 'glm-5.2'}",
    messages=[{"role": "user", "content": "你好，请介绍你自己。"}],
    stream=True
)

for chunk in response:
    content = chunk.choices[0].delta.content or ""
    print(content, end="", flush=True)
\`;
  document.getElementById('accPy').textContent = pySample;

  const curlSample = \`curl -X POST \${origin}/v1/chat/completions \\\\
  -H "Authorization: Bearer \${getKey() || 'YOUR_PROXY_API_KEY'}" \\\\
  -H "Content-Type: application/json" \\\\
  -d '{
    "model": "\${models[0] || 'glm-5.2'}",
    "messages": [{"role": "user", "content": "1+1="}],
    "stream": true
  }'\`;
  document.getElementById('accCurl').textContent = curlSample;
}

// ---- Key Test ------------------------------------------------------------
async function testSingleKey(provider, key) {
  toast(\`探活 \${provider}/\${key}...\`, 'ok');
  try {
    const res = await api('GET', \`/api/config?action=test&provider=\${encodeURIComponent(provider)}&key=\${encodeURIComponent(key)}\`);
    modelLatencyCache[\`\${provider}:\${key}\`] = res;
    renderAgentModels();
    renderProviders();
    if (res.ok) {
      toast(\`\${provider}/\${key} 连接成功 (\${res.latency_ms}ms)\`, 'ok');
    } else {
      toast(\`\${provider}/\${key} 探活异常 (HTTP \${res.status || 'ERR'})\`, 'err');
    }
  } catch (e) {
    toast(\`探活异常: \${e?.message || e}\`, 'err');
  }
}

// ---- Modals & Actions ----------------------------------------------------
function openModal(id) {
  document.getElementById(id).classList.add('show');
}
function closeModal(id) {
  document.getElementById(id).classList.remove('show');
}

// Preset Selection Handler
function onPresetSelected() {
  const presetId = document.getElementById('m_prov_preset').value;
  const nameInput = document.getElementById('m_prov_name');
  const urlInput = document.getElementById('m_prov_url');
  const descEl = document.getElementById('m_prov_desc');
  const modelsWrap = document.getElementById('m_prov_models_wrap');
  const modelsList = document.getElementById('m_prov_models_list');

  if (!presetId || !PRESET_DEFINITIONS[presetId]) {
    nameInput.value = '';
    urlInput.value = '';
    descEl.style.display = 'none';
    modelsWrap.style.display = 'none';
    modelsList.innerHTML = '';
    return;
  }

  const preset = PRESET_DEFINITIONS[presetId];
  nameInput.value = preset.id;
  urlInput.value = preset.base_url;
  descEl.textContent = preset.description || '';
  descEl.style.display = 'block';

  // Render recommended models checklist
  modelsList.innerHTML = '';
  if (preset.recommended_models && preset.recommended_models.length > 0) {
    modelsWrap.style.display = 'block';
    preset.recommended_models.forEach((rm) => {
      const row = document.createElement('div');
      row.style.marginBottom = '6px';
      row.innerHTML = \`
        <label class="checkbox" style="align-items:flex-start;">
          <input type="checkbox" data-model="\${rm.name}" data-upstream="\${rm.upstream}" \${rm.checked ? 'checked' : ''}>
          <div style="font-size:12px;">
            <div style="font-weight:600;color:var(--color-text-1);">\${rm.name} <span class="mono text-secondary" style="font-weight:normal;">(映射: \${rm.upstream})</span></div>
            <div class="text-secondary" style="font-size:11px;margin-top:2px;">\${rm.desc || ''}</div>
          </div>
        </label>
      \`;
      modelsList.appendChild(row);
    });
  } else {
    modelsWrap.style.display = 'none';
  }
}

function openAddProviderModal() {
  document.getElementById('providerModalTitle').textContent = '新增供应商';
  document.getElementById('presetSelectGroup').style.display = 'block';
  document.getElementById('m_prov_preset').value = '';
  document.getElementById('m_prov_name').value = '';
  document.getElementById('m_prov_name').disabled = false;
  document.getElementById('m_prov_url').value = '';
  document.getElementById('m_prov_key_label').value = 'default';
  document.getElementById('m_prov_key_val').value = '';
  document.getElementById('m_prov_init_key_wrap').style.display = 'block';
  document.getElementById('m_prov_desc').style.display = 'none';
  document.getElementById('m_prov_models_wrap').style.display = 'none';
  openModal('providerModal');
}

async function saveProviderModal() {
  const name = document.getElementById('m_prov_name').value.trim();
  const url = document.getElementById('m_prov_url').value.trim();
  if (!name || !url) { toast('请填写供应商与 Base URL', 'err'); return; }

  cfg.providers = cfg.providers || {};
  cfg.providers[name] = cfg.providers[name] || { keys: {} };
  cfg.providers[name].base_url = url;

  const keyLabel = document.getElementById('m_prov_key_label').value.trim() || 'default';
  const keyVal = document.getElementById('m_prov_key_val').value.trim();

  // If initial API Key provided, save it
  if (keyVal) {
    cfg.providers[name].keys = cfg.providers[name].keys || {};
    cfg.providers[name].keys[keyLabel] = keyVal;
  }

  // If recommended models were checked, auto-register / bind them
  const checkedModels = document.querySelectorAll('#m_prov_models_list input[type="checkbox"]:checked');
  if (checkedModels.length > 0) {
    cfg.agent_models = cfg.agent_models || {};
    const keyToBind = keyVal ? keyLabel : Object.keys(cfg.providers[name].keys || {})[0] || 'default';

    checkedModels.forEach((cb) => {
      const modelName = cb.dataset.model;
      const upstream = cb.dataset.upstream || modelName;

      if (!cfg.agent_models[modelName]) {
        cfg.agent_models[modelName] = {
          upstream_model: upstream,
          keys: [{ provider: name, key: keyToBind }],
        };
      } else {
        const existingKeys = cfg.agent_models[modelName].keys || [];
        if (!existingKeys.some((b) => b.provider === name && b.key === keyToBind)) {
          existingKeys.push({ provider: name, key: keyToBind });
          cfg.agent_models[modelName].keys = existingKeys;
        }
      }
    });
  }

  closeModal('providerModal');
  await persistConfig();
}

async function deleteProvider(name) {
  if (!confirm(\`删除供应商「\${name}」及其全部 Key？\`)) return;
  delete cfg.providers[name];
  await persistConfig();
}

function openAddKeyModal(prov) {
  document.getElementById('keyModalTitle').textContent = \`为 \${prov} 新增 Key\`;
  document.getElementById('m_key_prov').value = prov;
  document.getElementById('m_key_label').value = '';
  document.getElementById('m_key_val').value = '';
  openModal('keyModal');
}

function openEditKeyModal(prov, label, val) {
  document.getElementById('keyModalTitle').textContent = \`编辑 \${prov} Key: \${label}\`;
  document.getElementById('m_key_prov').value = prov;
  document.getElementById('m_key_label').value = label;
  document.getElementById('m_key_val').value = val;
  openModal('keyModal');
}

async function saveKeyModal() {
  const prov = document.getElementById('m_key_prov').value;
  const label = document.getElementById('m_key_label').value.trim();
  const val = document.getElementById('m_key_val').value.trim();
  if (!label || !val) { toast('请填写 Key 别名与密钥明文', 'err'); return; }

  cfg.providers[prov] = cfg.providers[prov] || { keys: {} };
  cfg.providers[prov].keys = cfg.providers[prov].keys || {};
  cfg.providers[prov].keys[label] = val;

  closeModal('keyModal');
  await persistConfig();
}

async function deleteKey(prov, label) {
  if (!confirm(\`删除 Key「\${label}」？\`)) return;
  delete cfg.providers[prov].keys[label];
  await persistConfig();
}

function openAddModelModal() {
  document.getElementById('agentModalTitle').textContent = '新增 Agent 模型';
  document.getElementById('m_model_name').value = '';
  document.getElementById('m_model_name').disabled = false;
  document.getElementById('m_upstream_model').value = '';
  renderBindingsCheckboxes([]);
  openModal('agentModal');
}

function openEditModelModal(m) {
  document.getElementById('agentModalTitle').textContent = \`编辑 Agent 模型: \${m}\`;
  document.getElementById('m_model_name').value = m;
  document.getElementById('m_model_name').disabled = true;
  const item = cfg.agent_models[m] || {};
  document.getElementById('m_upstream_model').value = item.upstream_model || '';
  renderBindingsCheckboxes(item.keys || []);
  openModal('agentModal');
}

function renderBindingsCheckboxes(existingKeys = []) {
  const container = document.getElementById('m_bindings_container');
  container.innerHTML = '';
  const providers = cfg.providers || {};

  let count = 0;
  for (const [p, prov] of Object.entries(providers)) {
    for (const k of Object.keys(prov.keys || {})) {
      count++;
      const isChecked = existingKeys.some(b => b.provider === p && b.key === k);
      const div = document.createElement('div');
      div.style.marginBottom = '6px';
      div.innerHTML = \`
        <label class="checkbox">
          <input type="checkbox" data-provider="\${p}" data-key="\${k}" \${isChecked ? 'checked' : ''}>
          <span><b>\${p}</b> / \${k}</span>
        </label>
      \`;
      container.appendChild(div);
    }
  }
  if (count === 0) {
    container.innerHTML = '<div class="text-secondary" style="font-size:12px;">暂无可用的 Key，请先添加供应商与 Key</div>';
  }
}

async function saveAgentModal() {
  const name = document.getElementById('m_model_name').value.trim();
  const upstream = document.getElementById('m_upstream_model').value.trim();
  if (!name) { toast('请输入模型名称', 'err'); return; }

  const checkedBoxes = document.querySelectorAll('#m_bindings_container input[type="checkbox"]:checked');
  const keys = Array.from(checkedBoxes).map(cb => ({
    provider: cb.dataset.provider,
    key: cb.dataset.key,
  }));

  if (keys.length === 0) {
    toast('请至少勾选一个候选 Key 绑定', 'err');
    return;
  }

  cfg.agent_models = cfg.agent_models || {};
  cfg.agent_models[name] = { keys };
  if (upstream) cfg.agent_models[name].upstream_model = upstream;

  closeModal('agentModal');
  await persistConfig();
}

async function removeModelKeyBinding(modelName, index) {
  if (cfg.agent_models?.[modelName]?.keys) {
    cfg.agent_models[modelName].keys.splice(index, 1);
    await persistConfig();
  }
}

async function deleteModel(name) {
  if (!confirm(\`删除模型「\${name}」？\`)) return;
  delete cfg.agent_models[name];
  await persistConfig();
}

// ---- Clear Cooldowns -----------------------------------------------------
async function clearAllCooldowns() {
  if (!confirm('清空全部 Key 冷却与失败计数？')) return;
  try {
    await api('DELETE', '/api/state');
    toast('冷却已清空', 'ok');
    await loadAllData();
  } catch (e) {
    toast('操作失败: ' + (e?.message || e), 'err');
  }
}

// ---- Config Export & Import (JSON / Blob) --------------------------------
function exportConfigJson() {
  try {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const filename = \`ocrproxy_edgeone_config_\${timestamp}.json\`;
    const jsonStr = JSON.stringify(cfg, null, 2);

    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast(\`配置已导出: \${filename}\`, 'ok');
  } catch (e) {
    toast('导出失败: ' + (e?.message || e), 'err');
  }
}

function triggerImportConfig() {
  const fileInput = document.getElementById('configFileImportInput');
  if (fileInput) {
    fileInput.value = '';
    fileInput.click();
  }
}

function handleConfigFileImport(event) {
  const file = event.target.files?.[0];
  if (!file) return;

  const reader = new FileReader();
  reader.onload = async (e) => {
    try {
      const content = e.target.result;
      const parsed = JSON.parse(content);

      if (!parsed || typeof parsed !== 'object') {
        throw new Error('导入文件不是有效的 JSON 对象');
      }

      if (!parsed.providers && !parsed.agent_models) {
        throw new Error('未检测到 providers 或 agent_models 配置节点');
      }

      const countProv = Object.keys(parsed.providers || {}).length;
      const countModels = Object.keys(parsed.agent_models || {}).length;

      if (!confirm(\`导入配置包含 \${countProv} 个供应商与 \${countModels} 个模型，覆盖当前 KV 配置？\`)) {
        return;
      }

      cfg = parsed;
      await persistConfig();
      toast('配置已导入', 'ok');
    } catch (err) {
      toast('导入失败: ' + err.message, 'err');
    }
  };
  reader.readAsText(file);
}

// ---- Raw JSON ------------------------------------------------------------
function formatRawJson() {
  const ta = document.getElementById('rawJsonText');
  try {
    const parsed = JSON.parse(ta.value);
    ta.value = JSON.stringify(parsed, null, 2);
    document.getElementById('rawJsonErr').style.display = 'none';
  } catch (e) {
    const errEl = document.getElementById('rawJsonErr');
    errEl.textContent = 'JSON 格式错误: ' + e.message;
    errEl.style.display = 'block';
  }
}

async function saveRawJson() {
  const ta = document.getElementById('rawJsonText');
  const errEl = document.getElementById('rawJsonErr');
  try {
    const parsed = JSON.parse(ta.value);
    errEl.style.display = 'none';
    cfg = parsed;
    await persistConfig();
  } catch (e) {
    errEl.textContent = 'JSON 格式解析失败: ' + e.message;
    errEl.style.display = 'block';
  }
}

async function persistConfig() {
  try {
    const res = await api('POST', '/api/config', cfg);
    cfgMeta = res;
    renderAll();
    toast('配置已保存', 'ok');
  } catch (e) {
    toast('保存失败: ' + (e?.message || e), 'err');
  }
}

// ---- Init ----------------------------------------------------------------
window.addEventListener('DOMContentLoaded', () => {
  if (getKey()) {
    doLogin();
  } else {
    showLoginOverlay();
  }
});

</script>
</body>
</html>
`;
}

export function onRequestGet(context) {
  return new Response(pageHtml(), {
    status: 200,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
    },
  });
}
