/**
 * Self-contained admin UI for OCRProxy EdgeOne.
 *
 *   Generated by scripts/build-admin.mjs from admin.{html,css,js}
 *   Do not edit this file directly.
 */

function pageHtml() {
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>OCRProxy EdgeOne 控制台</title>
  <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><rect width='32' height='32' rx='6' fill='%231664FF'/><text x='16' y='22' font-family='sans-serif' font-size='18' font-weight='bold' fill='white' text-anchor='middle'>O</text></svg>">
  <style>
/* ═══════════════════════════════════════════════════════════════
   KHC Web Design System — OCRProxy EdgeOne Admin Stylesheet
   ═══════════════════════════════════════════════════════════════ */

:root {
  /* Primary Brand (KHC Blue) */
  --khc-primary-50: #E6EEFF;
  --khc-primary-100: #C5D7FF;
  --khc-primary-200: #98B8FF;
  --khc-primary-300: #6B99FF;
  --khc-primary-400: #3F7AFF;
  --khc-primary-500: #1664FF;
  --khc-primary-600: #0F54E0;
  --khc-primary-700: #0B43B8;
  --khc-primary-800: #083185;
  --khc-primary-900: #06205C;

  /* Neutral / Slate Grays */
  --khc-neutral-50: #F8FAFC;
  --khc-neutral-100: #F1F5F9;
  --khc-neutral-200: #E2E8F0;
  --khc-neutral-300: #CBD5E1;
  --khc-neutral-400: #94A3B8;
  --khc-neutral-500: #64748B;
  --khc-neutral-600: #475569;
  --khc-neutral-700: #334155;
  --khc-neutral-800: #1E293B;
  --khc-neutral-900: #0F172A;

  /* Semantic State Colors */
  --khc-success-50: #ECFDF5;
  --khc-success-100: #D1FAE5;
  --khc-success-200: #A7F3D0;
  --khc-success-500: #10B981;
  --khc-success-600: #059669;
  --khc-success-700: #047857;

  --khc-warning-50: #FFFBEB;
  --khc-warning-100: #FEF3C7;
  --khc-warning-200: #FDE68A;
  --khc-warning-500: #F59E0B;
  --khc-warning-600: #D97706;
  --khc-warning-700: #B45309;

  --khc-danger-50: #FEF2F2;
  --khc-danger-100: #FEE2E2;
  --khc-danger-200: #FECACA;
  --khc-danger-500: #EF4444;
  --khc-danger-600: #DC2626;
  --khc-danger-700: #B91C1C;

  --khc-info-50: #ECFEFF;
  --khc-info-100: #CFFAFE;
  --khc-info-200: #A5F3FC;
  --khc-info-500: #06B6D4;
  --khc-info-700: #0E7490;

  /* Text Aliases */
  --color-text-1: var(--khc-neutral-900);
  --color-text-2: var(--khc-neutral-600);
  --color-text-3: var(--khc-neutral-400);
  --color-text-inverse: #FFFFFF;

  /* Surface Aliases */
  --color-bg-page: var(--khc-neutral-50);
  --color-bg-card: #FFFFFF;
  --color-bg-hover: var(--khc-neutral-100);

  /* Border Aliases */
  --color-border: var(--khc-neutral-200);
  --color-border-strong: var(--khc-neutral-300);

  /* Semantic Aliases */
  --color-primary: var(--khc-primary-500);
  --color-primary-hover: var(--khc-primary-400);
  --color-primary-active: var(--khc-primary-600);
  --color-success: var(--khc-success-500);
  --color-warning: var(--khc-warning-500);
  --color-danger: var(--khc-danger-500);
  --color-info: var(--khc-info-500);

  /* Legacy error aliases used by inline error boxes */
  --error: var(--color-danger);
  --error-soft: var(--khc-danger-50);
  --error-border: var(--khc-danger-200);

  /* Typography */
  --font-body: 'PingFang SC', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  --font-mono: 'SF Mono', 'Roboto Mono', Menlo, Consolas, Monaco, monospace;
  --font-size-display: 32px;
  --font-size-h1: 24px;
  --font-size-h2: 20px;
  --font-size-h3: 16px;
  --font-size-body: 14px;
  --font-size-caption: 12px;

  /* Spacing */
  --space-1: 4px;
  --space-2: 8px;
  --space-3: 12px;
  --space-4: 16px;
  --space-5: 24px;
  --space-6: 32px;

  /* Radius */
  --radius-sm: 2px;
  --radius-md: 4px;
  --radius-lg: 8px;
  --radius-xl: 12px;

  /* Shadows */
  --shadow-1: 0 1px 2px rgba(15, 23, 42, 0.04);
  --shadow-2: 0 2px 4px rgba(15, 23, 42, 0.06);
  --shadow-3: 0 4px 8px rgba(15, 23, 42, 0.08);
  --shadow-4: 0 8px 16px rgba(15, 23, 42, 0.10);
  --shadow-5: 0 12px 24px rgba(15, 23, 42, 0.12);
}

/* ── Reset & Base ── */
*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: var(--font-body);
  font-size: var(--font-size-body);
  line-height: 1.5;
  color: var(--color-text-1);
  background-color: var(--color-bg-page);
  -webkit-font-smoothing: antialiased;
}

button, input, select, textarea {
  font-family: inherit;
  font-size: inherit;
  color: inherit;
}

a {
  color: var(--color-primary);
  text-decoration: none;
}
a:hover {
  color: var(--color-primary-hover);
}

.mono {
  font-family: var(--font-mono);
}

.tabular {
  font-variant-numeric: tabular-nums;
}

/* ── App Shell & Navigation ── */
.app {
  display: none;
  min-height: 100vh;
  flex-direction: column;
}

.appbar {
  position: sticky;
  top: 0;
  z-index: 100;
  height: 48px;
  padding: 0 20px;
  background: var(--color-bg-card);
  border-bottom: 1px solid var(--color-border);
  box-shadow: var(--shadow-1);
  display: flex;
  align-items: center;
  gap: var(--space-4);
}

.brand-title {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  font-size: var(--font-size-h3);
  font-weight: 700;
  color: var(--color-text-1);
  white-space: nowrap;
}

.brand-logo {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  border-radius: var(--radius-sm);
  background: linear-gradient(135deg, var(--khc-primary-500), var(--khc-primary-700));
  color: var(--color-text-inverse);
  font-weight: 700;
  font-size: 15px;
}

.brand-badge {
  font-size: 11px;
  font-weight: 500;
  padding: 2px 8px;
  border-radius: 10px;
  background: var(--khc-primary-50);
  color: var(--color-primary);
  border: 1px solid var(--khc-primary-100);
}

nav#topNav {
  display: inline-flex;
  align-items: center;
  gap: var(--space-1);
  margin-left: auto;
}

nav#topNav button {
  appearance: none;
  border: none;
  background: transparent;
  padding: 6px 14px;
  font-size: 13px;
  font-weight: 500;
  color: var(--color-text-2);
  border-radius: var(--radius-sm);
  cursor: pointer;
  white-space: nowrap;
  transition: background 0.15s, color 0.15s;
}

nav#topNav button:hover {
  background: var(--color-bg-hover);
  color: var(--color-text-1);
}

nav#topNav button.active {
  background: var(--khc-primary-50);
  color: var(--color-primary);
  font-weight: 600;
}

.appbar .actions {
  display: flex;
  align-items: center;
  gap: var(--space-2);
}

/* ── Main Content Container ── */
.main {
  width: 100%;
  max-width: 1184px;
  margin: 0 auto;
  padding: var(--space-5) var(--space-4);
  flex: 1;
}

.panel {
  display: none;
}
.panel.active {
  display: block;
  animation: fadeIn 0.15s ease-out;
}

@keyframes fadeIn {
  from { opacity: 0; transform: translateY(3px); }
  to { opacity: 1; transform: translateY(0); }
}

/* ── Section & Headers ── */
.section {
  margin-bottom: var(--space-5);
}

.section-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: var(--space-3);
  gap: var(--space-3);
}

.section-title {
  font-size: var(--font-size-h3);
  font-weight: 600;
  color: var(--color-text-1);
  display: flex;
  align-items: center;
  gap: var(--space-2);
}

.section-desc {
  font-size: 12px;
  color: var(--color-text-2);
  margin-top: 2px;
}

/* ── Cards & Stats ── */
.card {
  background: var(--color-bg-card);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  box-shadow: var(--shadow-1);
  overflow: hidden;
  margin-bottom: var(--space-4);
  transition: box-shadow 0.15s;
}

.card:hover {
  box-shadow: var(--shadow-2);
}

.card-pad {
  padding: 20px 24px;
}

.card-head {
  padding: 14px 20px;
  border-bottom: 1px solid var(--color-border);
  background: var(--khc-neutral-50);
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-3);
}

.card-head h3 {
  font-size: 14px;
  font-weight: 600;
  color: var(--color-text-1);
}

.card-head .meta {
  font-size: 12px;
  color: var(--color-text-2);
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: var(--space-3);
  margin-bottom: var(--space-4);
}

.stat-card, .stat {
  background: var(--color-bg-card);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  padding: 16px 20px;
  box-shadow: var(--shadow-1);
}

.stat-label {
  display: block;
  font-size: var(--font-size-caption);
  color: var(--color-text-3);
  font-weight: 500;
  margin-bottom: var(--space-1);
}

.stat-value {
  display: block;
  font-size: 24px;
  font-weight: 700;
  color: var(--color-text-1);
  font-variant-numeric: tabular-nums;
  line-height: 1.2;
}

.stat-sub {
  display: block;
  font-size: 11px;
  color: var(--color-text-3);
  margin-top: 4px;
}

/* ── Buttons ── */
.btn {
  box-sizing: border-box;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  border: 1px solid transparent;
  border-radius: var(--radius-sm);
  height: 32px;
  padding: 6px 14px;
  font-family: var(--font-body);
  font-size: 13px;
  font-weight: 500;
  line-height: 1;
  white-space: nowrap;
  cursor: pointer;
  flex-shrink: 0;
  user-select: none;
  transition: filter 0.15s, background 0.15s, border-color 0.15s;
}

.btn-primary {
  background: var(--color-primary);
  color: #fff;
  border-color: var(--color-primary);
}
.btn-primary:not(:disabled):hover {
  filter: brightness(1.08);
}
.btn-primary:not(:disabled):active {
  filter: brightness(0.92);
}

.btn-secondary, .btn-ghost-border {
  background: #fff;
  color: var(--color-text-2);
  border-color: var(--color-border);
}
.btn-secondary:not(:disabled):hover, .btn-ghost-border:not(:disabled):hover {
  background: var(--color-bg-hover);
  border-color: var(--color-border-strong);
  color: var(--color-text-1);
}

.btn-danger {
  background: var(--color-danger);
  color: #fff;
  border-color: var(--color-danger);
}
.btn-danger:not(:disabled):hover {
  filter: brightness(1.08);
}
.btn-danger:not(:disabled):active {
  filter: brightness(0.92);
}

.btn-ghost {
  background: transparent;
  color: var(--color-text-2);
  border-color: transparent;
  box-shadow: none;
}
.btn-ghost:not(:disabled):hover {
  background: var(--color-bg-hover);
  color: var(--color-text-1);
}

.btn-sm, .btn-small {
  height: 28px;
  padding: 4px 10px;
  font-size: 12px;
}

.btn-icon {
  width: 32px;
  height: 32px;
  padding: 0;
  border-radius: var(--radius-sm);
  background: #fff;
  border: 1px solid var(--color-border);
  color: var(--color-text-2);
}
.btn-icon:hover {
  background: var(--color-bg-hover);
  color: var(--color-text-1);
}

.btn:disabled {
  opacity: 0.45;
  cursor: not-allowed;
  pointer-events: none;
}

/* ── Badges ── */
.badge {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 2px 10px;
  font-size: 12px;
  font-weight: 500;
  line-height: 1.5;
  border-radius: 10px;
  white-space: nowrap;
  flex-shrink: 0;
}

.badge-success, .b-done {
  background: var(--khc-success-50);
  color: var(--color-success);
}

.badge-primary, .b-running {
  background: var(--khc-primary-50);
  color: var(--color-primary);
}

.badge-warning, .b-canceled {
  background: var(--khc-warning-50);
  color: var(--color-warning);
}

.badge-danger, .badge-error, .b-failed {
  background: var(--khc-danger-50);
  color: var(--color-danger);
}

.badge-neutral, .b-queued {
  background: var(--khc-neutral-100);
  color: var(--color-text-2);
}

.badge-info, .b-info {
  background: var(--khc-info-50);
  color: var(--color-info);
}

.badge-purple {
  background: #f3e8ff;
  color: #7e22ce;
  border: 1px solid rgba(126,34,206,0.2);
}

/* ── Forms ── */
.form-group, .form-field {
  margin-bottom: var(--space-4);
}

.form-label {
  display: block;
  font-size: 12px;
  font-weight: 500;
  color: var(--color-text-2);
  margin-bottom: var(--space-1);
}

.form-control, input[type="text"], input[type="password"], input[type="search"], select, textarea {
  width: 100%;
  height: 40px;
  padding: 8px 12px;
  border: 1px solid var(--color-border-strong);
  border-radius: var(--radius-sm);
  font-size: 13px;
  color: var(--color-text-1);
  background: #fff;
  outline: none;
  transition: border-color 0.15s, box-shadow 0.15s;
}

textarea.form-control {
  height: auto;
  min-height: 80px;
}

.form-control:focus, input:focus, select:focus, textarea:focus {
  border-color: var(--color-primary);
  box-shadow: 0 0 0 3px rgba(22, 100, 255, 0.12);
}

.form-control:disabled, input:disabled, select:disabled {
  background: var(--color-bg-page);
  color: var(--color-text-3);
  cursor: not-allowed;
}

.checkbox {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  user-select: none;
  font-size: 13px;
}

.checkbox input[type="checkbox"] {
  width: 16px;
  height: 16px;
  margin: 0;
  accent-color: var(--color-primary);
  cursor: pointer;
}

/* ── Tables ── */
.table-wrap {
  width: 100%;
  overflow-x: auto;
}

table, .tbl {
  width: 100%;
  border-collapse: collapse;
  background: var(--color-bg-card);
  font-size: 13px;
}

th, .tbl th {
  background: var(--khc-neutral-50);
  color: var(--color-text-2);
  font-size: 12px;
  font-weight: 500;
  text-align: left;
  padding: 10px 12px;
  border-bottom: 1px solid var(--color-border);
  white-space: nowrap;
}

td, .tbl td {
  padding: 10px 12px;
  color: var(--color-text-1);
  border-bottom: 1px solid var(--color-border);
  transition: background 0.15s;
  vertical-align: middle;
}

tr:last-child td, .tbl tbody tr:last-child td {
  border-bottom: none;
}

tr:hover td, .tbl tbody tr:hover td {
  background: var(--color-bg-hover);
}

/* ── Provider Rows & Chips ── */
.provider-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 20px;
  border-bottom: 1px solid var(--color-border);
  background: #fff;
  transition: background 0.15s;
}
.provider-row:last-child {
  border-bottom: none;
}
.provider-row:hover {
  background: var(--color-bg-hover);
}

.key-chip {
  display: inline-block;
  padding: 2px 8px;
  border-radius: var(--radius-sm);
  background: var(--khc-neutral-100);
  font-family: var(--font-mono);
  font-size: 12px;
  color: var(--color-text-2);
  border: 1px solid var(--color-border);
}

/* ── Code Blocks ── */
.code-block {
  position: relative;
  background: var(--khc-neutral-900);
  color: #E2E8F0;
  border-radius: var(--radius-md);
  padding: 16px 20px;
  font-family: var(--font-mono);
  font-size: 12px;
  line-height: 1.6;
  overflow-x: auto;
  margin-bottom: var(--space-4);
}

.code-block pre {
  margin: 0;
  white-space: pre-wrap;
  word-break: break-all;
}

.copy-btn {
  position: absolute;
  top: 10px;
  right: 12px;
  background: rgba(255, 255, 255, 0.12);
  color: #fff;
  border: 1px solid rgba(255, 255, 255, 0.2);
  border-radius: var(--radius-sm);
  padding: 3px 8px;
  font-size: 11px;
  cursor: pointer;
  transition: background 0.15s;
}
.copy-btn:hover {
  background: rgba(255, 255, 255, 0.25);
}

/* ── Modals & Overlays ── */
.modal, .login-overlay {
  position: fixed;
  inset: 0;
  display: none;
  align-items: center;
  justify-content: center;
  background: rgba(15, 23, 42, 0.6);
  backdrop-filter: blur(4px);
  z-index: 1000;
  padding: 16px;
}

.modal.show, .login-overlay.show {
  display: flex;
}

.modal-box, .login-box {
  width: 440px;
  max-width: 100%;
  background: var(--color-bg-card);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-4);
  overflow: hidden;
  animation: modalIn 0.2s ease-out;
}

@keyframes modalIn {
  from { opacity: 0; transform: scale(0.96) translateY(-4px); }
  to { opacity: 1; transform: scale(1) translateY(0); }
}

.modal-head {
  padding: 16px 20px;
  border-bottom: 1px solid var(--color-border);
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.modal-head h3 {
  font-size: 15px;
  font-weight: 600;
  color: var(--color-text-1);
}
.modal-close {
  background: none;
  border: none;
  font-size: 12px;
  color: var(--color-text-3);
  cursor: pointer;
  line-height: 1;
  padding: 4px 6px;
  border-radius: var(--radius-sm);
}
.modal-close:hover {
  color: var(--color-text-1);
  background: var(--color-bg-hover);
}

.modal-body {
  padding: 20px;
}

.modal-foot {
  padding: 12px 20px;
  border-top: 1px solid var(--color-border);
  background: var(--khc-neutral-50);
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: var(--space-2);
}

/* ── Login Box Custom ── */
.login-box {
  padding: 36px 32px;
}
.login-box h2 {
  font-size: var(--font-size-h1);
  font-weight: 700;
  color: var(--color-text-1);
  margin-bottom: 6px;
  display: flex;
  align-items: center;
  gap: 8px;
}
.login-box p {
  color: var(--color-text-2);
  font-size: 13px;
  margin-bottom: 24px;
}

/* ── Toast Notifications ── */
.toast-container {
  position: fixed;
  bottom: 24px;
  right: 24px;
  z-index: 2000;
  display: flex;
  flex-direction: column;
  gap: 8px;
  pointer-events: none;
}

.toast {
  background: var(--khc-neutral-900);
  color: #fff;
  padding: 10px 16px;
  border-radius: var(--radius-md);
  font-size: 13px;
  box-shadow: var(--shadow-3);
  opacity: 0;
  transform: translateY(12px);
  transition: opacity 0.2s, transform 0.2s;
  pointer-events: auto;
  max-width: 380px;
  border-left: 4px solid var(--color-primary);
}

.toast.show {
  opacity: 1;
  transform: translateY(0);
}

.toast.ok {
  border-left-color: var(--color-success);
}

.toast.err {
  border-left-color: var(--color-danger);
}

/* ── Helpers ── */
.flex-between {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.text-secondary {
  color: var(--color-text-2);
}
.text-sm {
  font-size: 12px;
}
.mt-1 { margin-top: 4px; }
.mt-2 { margin-top: 8px; }
.mb-2 { margin-bottom: 8px; }
.mb-3 { margin-bottom: 12px; }
.mb-4 { margin-bottom: 16px; }
.empty {
  text-align: center;
  padding: 28px;
  color: var(--color-text-3);
  font-size: 13px;
}

/* ── Responsive ── */
@media (max-width: 860px) {
  .stats-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
  .appbar {
    padding: 0 16px;
    gap: 12px;
  }
  nav#topNav button {
    padding: 4px 8px;
    font-size: 12px;
  }
}

</style>
</head>
<body>

<!-- Login Overlay -->
<div id="loginOverlay" class="login-overlay">
  <form class="login-box" onsubmit="event.preventDefault(); doLogin();">
    <h2>OCRProxy</h2>
    <p>OCRProxy EdgeOne 控制台</p>
    <div class="form-group">
      <label class="form-label" for="loginKey">管理员凭证 (PROXY_API_KEY)</label>
      <input type="password" id="loginKey" class="form-control" placeholder="请输入 PROXY_API_KEY" autocomplete="current-password">
    </div>
    <button type="submit" class="btn btn-primary" style="width:100%;padding:10px;">进入控制台</button>
    <div id="loginErr" style="display:none;margin-top:14px;padding:10px;border-radius:var(--radius-md);background:var(--color-danger-50);border:1px solid var(--color-danger-500);color:var(--color-danger-500);font-size:12px;text-align:center;"></div>
  </form>
</div>

<!-- App -->
<div id="app" class="app">
  <header class="appbar">
    <div class="brand-title">
      <span class="brand-logo">O</span>
      <span>OCRProxy</span>
      <span class="brand-badge">EdgeOne 边缘版</span>
    </div>
    <nav id="topNav">
      <button class="active" onclick="switchTab('dashboard')">概览</button>
      <button onclick="switchTab('agents')">Agent 模型</button>
      <button onclick="switchTab('providers')">供应商</button>
      <button onclick="switchTab('settings')">全局策略</button>
      <button onclick="switchTab('raw')">JSON 配置</button>
      <button onclick="switchTab('access')">接入说明</button>
    </nav>
    <div class="actions">
      <button class="btn btn-secondary btn-sm" onclick="exportConfigJson()" title="导出当前完整配置为 JSON 备份文件">导出备份</button>
      <button class="btn btn-secondary btn-sm" onclick="triggerImportConfig()" title="从本地 JSON 备份文件恢复配置">导入配置</button>
      <button class="btn btn-secondary btn-sm" onclick="loadAllData()" title="刷新数据">刷新</button>
      <button class="btn btn-ghost btn-sm" onclick="doLogout()">退出</button>
    </div>
    <input type="file" id="configFileImportInput" accept=".json,application/json" style="display:none;" onchange="handleConfigFileImport(event)">
  </header>

  <main class="main">
    <!-- Panel 1: Dashboard -->
    <div id="panel-dashboard" class="panel active">
      <div class="section mb-4">
        <div class="section-head">
          <div class="section-title">状态总览</div>
          <span id="configSourceBadge" class="badge badge-success">KV 同步中</span>
        </div>
        <div class="stats-grid" style="grid-template-columns: repeat(3, 1fr);">
          <div class="stat-card">
            <div class="stat-label">已配置 Agent 模型</div>
            <div class="stat-value" id="statModelCount">0</div>
            <div class="stat-sub">OpenAI 兼容路由</div>
          </div>
          <div class="stat-card">
            <div class="stat-label">候选 Key 总数</div>
            <div class="stat-value" id="statTotalKeys">0</div>
            <div class="stat-sub">多 Key 轮询池</div>
          </div>
          <div class="stat-card">
            <div class="stat-label">运行模式</div>
            <div class="stat-value" style="font-size:20px;color:var(--color-success);" id="statRuntime">Edge V8</div>
            <div class="stat-sub" id="statLastModified">3200+ 边缘节点</div>
          </div>
        </div>
      </div>

      <!-- Quick Models Overview -->
      <div class="section">
        <div class="section-head">
          <div class="section-title">模型状态</div>
          <button class="btn btn-primary btn-sm" onclick="switchTab('agents')">管理全部模型</button>
        </div>
        <div class="card table-wrap">
          <table>
            <thead><tr><th>模型名称</th><th>上游映射</th><th>候选 Key 数量</th><th>操作</th></tr></thead>
            <tbody id="quickModelsBody"></tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Panel 2: Agent Models -->
    <div id="panel-agents" class="panel">
      <div class="section">
        <div class="section-head">
          <div>
            <div class="section-title">Agent 模型</div>
            <div class="section-desc">配置 Agent 模型与候选 Key 绑定</div>
          </div>
          <button class="btn btn-primary btn-sm" onclick="openAddModelModal()">新增模型</button>
        </div>
        <div id="agentModelsBox"></div>
      </div>
    </div>

    <!-- Panel 3: Providers & Keys -->
    <div id="panel-providers" class="panel">
      <div class="section">
        <div class="section-head">
          <div>
            <div class="section-title">供应商</div>
            <div class="section-desc">配置上游 Base URL 与 API Key</div>
          </div>
          <button class="btn btn-primary btn-sm" onclick="openAddProviderModal()">新增供应商</button>
        </div>
        <div id="providersBox"></div>
      </div>
    </div>

    <!-- Panel: Global Settings -->
    <div id="panel-settings" class="panel">
      <div class="section">
        <div class="section-head">
          <div>
            <div class="section-title">全局策略与超时控制</div>
            <div class="section-desc">统一配置大模型路由算法、全局硬超时预算与跨厂商熔断策略</div>
          </div>
          <div style="display:flex;gap:8px;">
            <button class="btn btn-ghost btn-sm" onclick="resetSettingsToDefault()">恢复推荐默认值</button>
            <button class="btn btn-primary btn-sm" onclick="saveSettings()">保存策略设置</button>
          </div>
        </div>
        <div class="card card-pad mb-4">
          <h4 style="margin:0 0 16px 0;font-size:15px;color:var(--color-text-1);">分流算法与超时预算</h4>
          <div style="display:grid;grid-template-columns:repeat(2,1fr);gap:20px;">
            <div class="form-group">
              <label class="form-label">路由分流算法 (agent_routing_strategy)</label>
              <select id="set_routing_strategy" class="form-control">
                <option value="sticky_failover">粘性故障转移 (sticky_failover) — 默认推荐，稳定高效</option>
                <option value="round_robin">原子轮询 (round_robin) — 均衡摊销各个 Key</option>
                <option value="priority_fallback">优先级优先 (priority_fallback) — 严格按顺序尝试</option>
                <option value="random">随机散列 (random) — 随机挑选候选 Key</option>
              </select>
              <div class="text-secondary text-sm mt-1">控制多个候选 Key 之间的主备切换与负载均衡方式</div>
            </div>
            <div class="form-group">
              <label class="form-label">全局请求硬超时预算 (request_total_budget_sec)</label>
              <div style="display:flex;align-items:center;gap:12px;">
                <input type="number" id="set_request_total_budget_sec" class="form-control" min="10" max="120" step="1" value="25" style="width:140px;">
                <span class="text-secondary">秒 (EdgeOne 建议 25s 以规避平台 30s 强杀；VM 建议 45~60s)</span>
              </div>
              <div class="text-secondary text-sm mt-1">单次客户端请求的最大总时钟，超时立即主动返回 504，彻底杜绝 4 分钟死锁</div>
            </div>
            <div class="form-group">
              <label class="form-label">单 Key 上游超时时间 (upstream_timeout_sec)</label>
              <div style="display:flex;align-items:center;gap:12px;">
                <input type="number" id="set_upstream_timeout_sec" class="form-control" min="5" max="60" step="1" value="15" style="width:140px;">
                <span class="text-secondary">秒 (默认 15s)</span>
              </div>
              <div class="text-secondary text-sm mt-1">向上游单一 Key 发起请求的等待上限，超时后无缝切换下一候选 Key</div>
            </div>
            <div class="form-group">
              <label class="form-label">单请求最大重试次数 (schedule_total_budget)</label>
              <div style="display:flex;align-items:center;gap:12px;">
                <input type="number" id="set_schedule_total_budget" class="form-control" min="1" max="5" step="1" value="3" style="width:140px;">
                <span class="text-secondary">次 (默认 3 次)</span>
              </div>
              <div class="text-secondary text-sm mt-1">单次请求最多允许尝试的候选 Key 数量上限</div>
            </div>
          </div>
        </div>

        <div class="card card-pad">
          <h4 style="margin:0 0 16px 0;font-size:15px;color:var(--color-text-1);">智能故障熔断与冷却避让</h4>
          <div style="display:grid;grid-template-columns:repeat(2,1fr);gap:20px;">
            <div class="form-group">
              <label class="form-label">单厂商尝试次数上限 (max_attempts_per_provider)</label>
              <div style="display:flex;align-items:center;gap:12px;">
                <input type="number" id="set_max_attempts_per_provider" class="form-control" min="1" max="5" step="1" value="2" style="width:140px;">
                <span class="text-secondary">次 (默认 2 次)</span>
              </div>
              <div class="text-secondary text-sm mt-1">防止同一厂商（如7个商汤Key）源站宕机时在同一厂商上死等7次超时</div>
            </div>
            <div class="form-group">
              <label class="form-label">跨厂商快速熔断 (fast_failover_provider_down)</label>
              <div style="display:flex;align-items:center;gap:12px;margin-top:8px;">
                <label class="checkbox" style="font-size:14px;cursor:pointer;">
                  <input type="checkbox" id="set_fast_failover_provider_down" checked>
                  <span style="font-weight:600;">开启跨厂商快速熔断</span>
                </label>
              </div>
              <div class="text-secondary text-sm mt-1">遇 502/504/超时且存在其他备用厂商时，直接跳过当前厂商所有 Key，秒级切走</div>
            </div>
            <div class="form-group">
              <label class="form-label">429 限流冷却时长 (cooldown_429_sec)</label>
              <div style="display:flex;align-items:center;gap:12px;">
                <input type="number" id="set_cooldown_429_sec" class="form-control" min="10" max="600" step="1" value="60" style="width:140px;">
                <span class="text-secondary">秒 (默认 60s)</span>
              </div>
              <div class="text-secondary text-sm mt-1">命中 RPM / TPM 限流时的临时避让冷却时长</div>
            </div>
            <div class="form-group">
              <label class="form-label">5xx 故障冷却时长 (cooldown_5xx_sec)</label>
              <div style="display:flex;align-items:center;gap:12px;">
                <input type="number" id="set_cooldown_5xx_sec" class="form-control" min="5" max="300" step="1" value="30" style="width:140px;">
                <span class="text-secondary">秒 (默认 30s)</span>
              </div>
              <div class="text-secondary text-sm mt-1">上游源站抛出 500/502/503/504 错误时的避让冷却时长</div>
            </div>
            <div class="form-group">
              <label class="form-label">连续失败熔断阈值 (circuit_break_threshold)</label>
              <div style="display:flex;align-items:center;gap:12px;">
                <input type="number" id="set_circuit_break_threshold" class="form-control" min="1" max="10" step="1" value="3" style="width:140px;">
                <span class="text-secondary">次 (默认 3 次)</span>
              </div>
              <div class="text-secondary text-sm mt-1">某个 Key 连续失败达到该次数后触发断路器熔断</div>
            </div>
            <div class="form-group">
              <label class="form-label">403 鉴权失败隔离时长 (cooldown_403_sec)</label>
              <div style="display:flex;align-items:center;gap:12px;">
                <input type="number" id="set_cooldown_403_sec" class="form-control" min="60" max="3600" step="1" value="600" style="width:140px;">
                <span class="text-secondary">秒 (默认 600s)</span>
              </div>
              <div class="text-secondary text-sm mt-1">Key 无效或欠费被拒时的主动隔离时间</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Panel 5: Raw JSON Editor -->
    <div id="panel-raw" class="panel">
      <div class="section">
        <div class="section-head">
          <div>
            <div class="section-title">JSON 配置</div>
            <div class="section-desc">编辑完整路由与凭证 JSON，保存后写入 KV 生效</div>
          </div>
          <div style="display:flex;gap:8px;flex-wrap:wrap;">
            <button class="btn btn-ghost btn-sm" onclick="exportConfigJson()">导出备份</button>
            <button class="btn btn-ghost btn-sm" onclick="triggerImportConfig()">导入配置</button>
            <button class="btn btn-ghost btn-sm" onclick="formatRawJson()">格式化 JSON</button>
            <button class="btn btn-primary btn-sm" onclick="saveRawJson()">保存配置</button>
          </div>
        </div>
        <div class="card card-pad">
          <textarea id="rawJsonText" class="form-control" spellcheck="false" style="min-height:480px;font-family:var(--font-mono);font-size:12px;"></textarea>
          <div id="rawJsonErr" style="display:none;margin-top:10px;color:var(--error);font-size:12px;"></div>
        </div>
      </div>
    </div>

    <!-- Panel 6: Access & Docs -->
    <div id="panel-access" class="panel">
      <div class="section">
        <div class="section-title mb-2">接入网关</div>
        <div class="card card-pad mb-3">
          <div class="flex-between mb-2"><span class="text-secondary">Base URL 接口地址</span><span class="mono" id="accBaseUrl">—</span></div>
          <div class="flex-between mb-2"><span class="text-secondary">已配置 Agent 模型</span><span class="mono" id="accModelsList">—</span></div>
          <div class="flex-between"><span class="text-secondary">网关已支持协议</span><span id="accProtocols" style="display:flex;gap:6px;">—</span></div>
        </div>
        <div class="section-title mb-2" style="display:flex;align-items:center;gap:8px;">
          <span>1. OpenAI 格式调用 (Chat Completions)</span>
          <span class="badge badge-success" style="font-size:11px;">OpenAI Chat</span>
        </div>
        <div class="code-block mb-3"><button class="copy-btn" onclick="copySnippet('accPy')">复制</button><pre id="accPy"></pre></div>
        
        <div class="section-title mb-2" style="display:flex;align-items:center;gap:8px;">
          <span>2. Claude 格式调用 (Anthropic Messages)</span>
          <span class="badge badge-warning" style="font-size:11px;">Anthropic Messages</span>
        </div>
        <div class="code-block mb-3"><button class="copy-btn" onclick="copySnippet('accMessagesPy')">复制</button><pre id="accMessagesPy"></pre></div>

        <div class="section-title mb-2">cURL 示例</div>
        <div class="code-block"><button class="copy-btn" onclick="copySnippet('accCurl')">复制</button><pre id="accCurl"></pre></div>
      </div>
    </div>
  </main>
</div>

<!-- Modal: Provider -->
<div id="providerModal" class="modal">
  <div class="modal-box" style="width:560px;max-height:90vh;overflow-y:auto;">
    <div class="modal-head">
      <h3 id="providerModalTitle">新增供应商</h3>
      <button class="modal-close" onclick="closeModal('providerModal')">关闭</button>
    </div>
    <div class="modal-body">
      <div class="form-group" id="presetSelectGroup">
        <label class="form-label">预置模板</label>
        <select id="m_prov_preset" class="form-control" onchange="onPresetSelected()">
          <option value="">-- 自定义配置 (手动输入) --</option>
          <option value="minimax">MiniMax</option>
          <option value="bai">B.AI</option>
          <option value="agnes">Agnes AI</option>
          <option value="google">Google AI Studio</option>
          <option value="sensenova">SenseNova</option>
          <option value="stepfun">StepFun</option>
          <option value="siliconflow">SiliconFlow</option>
          <option value="tokenrhythm">TokenRhythm</option>
        </select>
        <div id="m_prov_desc" style="display:none;margin-top:6px;font-size:12px;color:var(--color-text-2);padding:6px 10px;background:var(--color-bg-page);border-radius:var(--radius-sm);"></div>
      </div>

      <div class="form-group">
        <label class="form-label">供应商标识 (英文标识，如 google, sensenova)</label>
        <input type="text" id="m_prov_name" class="form-control" placeholder="如 google">
      </div>
      <div class="form-group">
        <label class="form-label">Base URL (API 端点地址)</label>
        <input type="text" id="m_prov_url" class="form-control" placeholder="如 https://generativelanguage.googleapis.com/v1beta/openai">
      </div>
      <div class="form-group" style="margin-top:14px;">
        <label class="form-label">支持的协议类型 (可多选，模型将自动继承生效)</label>
        <div style="display:flex;gap:16px;flex-wrap:wrap;padding:10px 14px;background:var(--color-bg-page);border-radius:var(--radius-sm);border:1px solid var(--color-border);">
          <label class="checkbox" style="font-size:13px;display:flex;align-items:center;gap:6px;cursor:pointer;">
            <input type="checkbox" id="m_prov_proto_chat" checked>
            <span class="badge badge-success" style="font-size:11px;padding:2px 6px;">OpenAI Chat</span>
            <span class="text-secondary text-sm">(/v1/chat/completions)</span>
          </label>
          <label class="checkbox" style="font-size:13px;display:flex;align-items:center;gap:6px;cursor:pointer;">
            <input type="checkbox" id="m_prov_proto_messages">
            <span class="badge badge-warning" style="font-size:11px;padding:2px 6px;">Anthropic Messages</span>
            <span class="text-secondary text-sm">(/v1/messages)</span>
          </label>
          <label class="checkbox" style="font-size:13px;display:flex;align-items:center;gap:6px;cursor:pointer;">
            <input type="checkbox" id="m_prov_proto_responses">
            <span class="badge badge-purple" style="font-size:11px;padding:2px 6px;">OpenAI Responses</span>
            <span class="text-secondary text-sm">(/v1/responses)</span>
          </label>
        </div>
      </div>
      <div class="form-group" id="m_prov_custom_url_wrap" style="margin-top:14px;">
        <label class="checkbox" style="font-size:13px;display:flex;align-items:center;gap:6px;cursor:pointer;font-weight:600;">
          <input type="checkbox" id="m_prov_custom_url_toggle" onchange="onEdgeOneCustomUrlToggleChange()">
          <span>自定义协议独立端点 / 路径 (高级配置)</span>
        </label>
        <div id="m_prov_custom_url_section" style="display:none;margin-top:8px;padding:12px;background:var(--color-bg-page);border-radius:var(--radius-sm);border:1px solid var(--color-border);">
          <label class="form-label" style="font-size:12px;color:var(--color-text-2);">Anthropic Messages 独立 Base URL</label>
          <input type="text" id="m_prov_anthropic_url" class="form-control" placeholder="例如 https://api.minimax.cn/anthropic">
          <div class="text-secondary text-xs mt-1" style="font-size:11px;">当上游的 Messages 协议与基础 Base URL 域名或路径不同时填写。</div>
        </div>
      </div>

      <div id="m_prov_models_wrap" class="form-group" style="display:none;margin-top:16px;">
        <label class="form-label">自动创建推荐模型</label>
        <div id="m_prov_models_list" style="display:flex;flex-direction:column;gap:6px;max-height:180px;overflow-y:auto;background:var(--color-bg-page);padding:10px;border-radius:var(--radius-sm);border:1px solid var(--color-border);"></div>
      </div>
    </div>
    <div class="modal-foot">
      <button class="btn btn-ghost" onclick="closeModal('providerModal')">取消</button>
      <button class="btn btn-primary" onclick="saveProviderModal()">保存配置</button>
    </div>
  </div>
</div>

<!-- Modal: Key -->
<div id="keyModal" class="modal">
  <div class="modal-box">
    <div class="modal-head">
      <h3 id="keyModalTitle">新增 API Key</h3>
      <button class="modal-close" onclick="closeModal('keyModal')">关闭</button>
    </div>
    <div class="modal-body">
      <input type="hidden" id="m_key_prov">
      <input type="hidden" id="m_key_old_label">
      <div id="m_key_proto_hint" class="mb-2" style="font-size:12px;padding:6px 10px;background:var(--color-bg-page);border-radius:var(--radius-sm);border:1px solid var(--color-border);"></div>
      <div class="form-group">
        <label class="form-label">Key 别名</label>
        <input type="text" id="m_key_label" class="form-control" placeholder="如 自己">
      </div>
      <div class="form-group">
        <label class="form-label">API Key 密钥明文 (sk-...)</label>
        <input type="text" id="m_key_val" class="form-control" placeholder="sk-...">
      </div>
      <label class="checkbox"><input type="checkbox" id="m_key_skip"> <span>跳过连通性在线校验</span></label>
      <div id="m_key_spinner" class="hint mt-2" style="display:none;"><span class="spinner"></span> 正在校验各协议连通性...</div>
      <div id="m_key_diag_box" style="display:none;margin-top:10px;padding:10px 12px;border-radius:var(--radius-sm);border:1px solid var(--color-border);background:var(--color-bg-page);"></div>
    </div>
    <div class="modal-foot">
      <button class="btn btn-ghost" onclick="closeModal('keyModal')">取消</button>
      <button class="btn btn-primary" onclick="saveKeyModal()">保存 Key</button>
    </div>
  </div>
</div>

<!-- Modal: Agent Model -->
<div id="agentModal" class="modal">
  <div class="modal-box" style="width:580px;">
    <div class="modal-head">
      <h3 id="agentModalTitle">新增 Agent 模型</h3>
      <button class="modal-close" onclick="closeModal('agentModal')">关闭</button>
    </div>
    <div class="modal-body">
      <input type="hidden" id="m_model_old_name">
      <div class="form-group">
        <label class="form-label">供应商快捷筛选与推荐模型</label>
        <select id="m_model_prov_filter" class="form-control" onchange="onModelProvFilterChange()">
          <option value="">全部供应商</option>
        </select>
        <div id="m_quick_model_tags" style="display:flex;flex-wrap:wrap;gap:6px;margin-top:8px;"></div>
      </div>
      <div class="form-group">
        <label class="form-label">模型名称 (对外 Model ID，如 glm-5.2, gemini-2.5-flash)</label>
        <input type="text" id="m_model_name" class="form-control" placeholder="如 gemini-2.5-flash">
      </div>
      <div class="form-group">
        <label class="form-label">上游模型 (可选，实际传给服务商的模型名，留空则与模型名称一致)</label>
        <input type="text" id="m_upstream_model" class="form-control" placeholder="如 deepseek-v4-flash-0731">
      </div>
      <div class="form-group">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:6px;">
          <label class="form-label" style="margin:0;">候选 Key 绑定序列 (按供应商分组勾选)</label>
          <div style="display:flex;gap:8px;">
            <button type="button" class="btn btn-ghost btn-sm" style="font-size:11px;padding:2px 8px;height:24px;" onclick="toggleSelectAllKeys(true)">全选</button>
            <button type="button" class="btn btn-ghost btn-sm" style="font-size:11px;padding:2px 8px;height:24px;" onclick="toggleSelectAllKeys(false)">清空</button>
          </div>
        </div>
        <div id="m_bindings_container" style="max-height:220px;overflow-y:auto;border:1px solid var(--color-border);border-radius:var(--radius-sm);padding:8px;background:var(--color-bg-page);display:flex;flex-direction:column;gap:8px;"></div>
      </div>
    </div>
    <div class="modal-foot">
      <button class="btn btn-ghost" onclick="closeModal('agentModal')">取消</button>
      <button class="btn btn-primary" onclick="saveAgentModal()">保存模型</button>
    </div>
  </div>
</div>

<!-- Toast Container -->
<div id="toastContainer" class="toast-container"></div>

<script>
/**
 * admin.js — OCRProxy EdgeOne Admin UI Controller (VM-grade parity + Presets & Export/Import)
 */

let cfg = { providers: {}, agent_models: {} };
let cfgMeta = {};
let healthData = {};
let stateData = [];
let ipData = {};
let activeTab = 'dashboard';
let modelLatencyCache = {}; // { "provider:key": { latency_ms, status } }

const TOKEN_KEY = 'ocrproxy_edge_token';

function esc(s) {
  if (s === null || s === undefined) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// ---- Provider Presets Database -------------------------------------------
const PRESET_DEFINITIONS = {
  minimax: {
    id: 'minimax',
    name: 'MiniMax',
    base_url: 'https://api.minimaxi.com/v1',
    anthropic_base_url: 'https://api.minimax.cn/anthropic',
    protocols: ['chat', 'messages'],
    description: 'MiniMax 官方国内订阅平台，支持 MiniMax-M3 系列，原生兼容 OpenAI Completions 与 Anthropic Messages 双协议直通',
    recommended_models: [
      { name: 'MiniMax-M3', upstream: 'MiniMax-M3', desc: 'MiniMax-M3 旗舰多模态通用模型 (支持超长思考，兼容 Messages)', checked: true },
    ]
  },
  bai: {
    id: 'bai',
    name: 'B.AI',
    base_url: 'https://api.b.ai/v1',
    anthropic_base_url: 'https://api.b.ai/v1',
    protocols: ['chat', 'messages'],
    description: 'B.AI 统一大模型中转平台，原生兼容 OpenAI Chat Completions 与 Anthropic Messages 协议双通道',
    recommended_models: [
      { name: 'deepseek-v4-flash-vision-exp', upstream: 'deepseek-v4-flash-vision-exp', desc: 'DeepSeek V4 Flash 视觉/推理增强模型', checked: true },
      { name: 'qwen3.8-flash', upstream: 'qwen3.8-flash', desc: '通义千问 3.8 Flash 高速推理模型', checked: true },
      { name: 'claude-3-5-sonnet', upstream: 'claude-3-5-sonnet', desc: 'Claude 3.5 Sonnet 编程模型', checked: false },
      { name: 'deepseek-v3', upstream: 'deepseek-v3', desc: 'DeepSeek V3 全能大模型', checked: false },
    ]
  },
  agnes: {
    id: 'agnes',
    name: 'Agnes AI',
    base_url: 'https://apihub.agnes-ai.com/v1',
    protocols: ['chat'],
    description: 'Agnes AI 平台，支持 agnes-2.5-flash 等高并发轻量 Agent 模型 (512K 上下文)',
    recommended_models: [
      { name: 'agnes-2.5-flash', upstream: 'agnes-2.5-flash', desc: 'Agnes 2.5 Flash 旗舰高速模型 (512K 上下文)', checked: true },
      { name: 'agnes-2.0-flash', upstream: 'agnes-2.0-flash', desc: 'Agnes 2.0 Flash 兼容回退模型', checked: false },
    ]
  },
  google: {
    id: 'google',
    name: 'Google AI Studio',
    base_url: 'https://generativelanguage.googleapis.com/v1beta/openai',
    protocols: ['chat'],
    description: 'Google 官方 Gemini 系列大模型，支持 Gemini 2.5 / 3 / 3.5+，已内置 Thinking Config 思考等级映射',
    recommended_models: [
      { name: 'gemini-3.5-flash', upstream: 'gemini-3.5-flash', desc: '最新高性价比推理模型 (支持 low/medium/high 思考等级)', checked: true },
      { name: 'gemini-3.5-pro', upstream: 'gemini-3.5-pro', desc: '最新旗舰强推理模型 (支持 low/high 思考等级)', checked: true },
      { name: 'gemini-2.5-flash', upstream: 'gemini-2.5-flash', desc: '经典多模态快速模型', checked: false },
      { name: 'gemini-2.5-pro', upstream: 'gemini-2.5-pro', desc: '经典多模态深度思考模型', checked: false },
    ]
  },
  sensenova: {
    id: 'sensenova',
    name: 'SenseNova',
    base_url: 'https://token.sensenova.cn/v1',
    protocols: ['chat'],
    description: '商汤 SenseNova 开放平台，支持 GLM-5.2、DeepSeek-V3/R1 等，原生支持 reasoning_effort 思考控制',
    recommended_models: [
      { name: 'glm-5.2', upstream: 'GLM-5.2', desc: '智谱/商汤最新 GLM-5.2 旗舰推理大模型', checked: true },
      { name: 'deepseek-v3', upstream: 'DeepSeek-V3', desc: 'DeepSeek-V3 基础推理模型', checked: false },
      { name: 'deepseek-r1', upstream: 'DeepSeek-R1', desc: 'DeepSeek-R1 深度思考推理模型', checked: false },
    ]
  },
  stepfun: {
    id: 'stepfun',
    name: 'StepFun',
    base_url: 'https://api.stepfun.com/v1',
    protocols: ['chat'],
    description: '阶跃星辰 StepFun 大模型平台，已自动适配 reasoning_effort none->low 降级与 deepseek 思考格式注入',
    recommended_models: [
      { name: 'step-3.7-flash', upstream: 'step-3.7-flash', desc: '阶跃最新闪电高速推理大模型', checked: true },
      { name: 'step-2-16k', upstream: 'step-2-16k', desc: '阶跃 Step-2 旗舰大模型', checked: false },
    ]
  },
  siliconflow: {
    id: 'siliconflow',
    name: 'SiliconFlow',
    base_url: 'https://api.siliconflow.cn/v1',
    protocols: ['chat'],
    description: '硅基流动 SiliconFlow 高并发推理平台，包含 DeepSeek、Qwen 等开源模型',
    recommended_models: [
      { name: 'deepseek-ai/DeepSeek-V3', upstream: 'deepseek-ai/DeepSeek-V3', desc: 'DeepSeek-V3 全尺寸旗舰模型', checked: true },
      { name: 'deepseek-ai/DeepSeek-R1', upstream: 'deepseek-ai/DeepSeek-R1', desc: 'DeepSeek-R1 全尺寸深度思考模型', checked: false },
      { name: 'Qwen/Qwen2.5-72B-Instruct', upstream: 'Qwen/Qwen2.5-72B-Instruct', desc: '通义千问 72B Instruct 指令模型', checked: false },
    ]
  },
  tokenrhythm: {
    id: 'tokenrhythm',
    name: 'TokenRhythm',
    base_url: 'https://api.tokenrhythm.com/v1',
    protocols: ['chat'],
    description: 'TokenRhythm 聚合大模型路由网关，已自动适配 tool_choice 格式转换',
    recommended_models: [
      { name: 'claude-3-5-sonnet-20241022', upstream: 'claude-3-5-sonnet-20241022', desc: 'Claude 3.5 Sonnet 强编程模型', checked: true },
      { name: 'gpt-4o', upstream: 'gpt-4o', desc: 'OpenAI GPT-4o 旗舰全能模型', checked: false },
    ]
  }
};

function getKey() {
  return localStorage.getItem(TOKEN_KEY) || '';
}

function setKey(k) {
  localStorage.setItem(TOKEN_KEY, k);
}

function clearKey() {
  localStorage.removeItem(TOKEN_KEY);
}

function toast(msg, type = 'ok') {
  const container = document.getElementById('toastContainer');
  if (!container) return;
  const el = document.createElement('div');
  el.className = \`toast \${type}\`;
  el.textContent = msg;
  container.appendChild(el);
  setTimeout(() => el.classList.add('show'), 10);
  setTimeout(() => {
    el.classList.remove('show');
    setTimeout(() => el.remove(), 300);
  }, 3000);
}

function copySnippet(elementId) {
  const el = document.getElementById(elementId);
  if (!el) return;
  const text = el.textContent || '';
  navigator.clipboard.writeText(text).then(() => {
    toast('已复制到剪贴板', 'ok');
  }).catch(() => {
    toast('复制失败，请手动复制', 'err');
  });
}

// ---- API wrapper ---------------------------------------------------------
async function api(method, path, body = null) {
  const token = getKey();
  const headers = { 'Content-Type': 'application/json' };
  if (token) headers['Authorization'] = \`Bearer \${token}\`;

  const res = await fetch(path, {
    method,
    headers,
    body: body ? JSON.stringify(body) : null,
  });

  const text = await res.text();
  let data = null;
  try {
    data = JSON.parse(text);
  } catch {
    data = { raw: text };
  }

  if (res.status === 401) {
    clearKey();
    showLoginOverlay('凭证无效或已过期，请重新登录');
    throw new Error('未授权 (401)');
  }
  if (!res.ok) {
    throw new Error(data?.error?.message || data?.error || \`HTTP \${res.status}\`);
  }
  return data;
}

// ---- Navigation / Tabs ---------------------------------------------------
function switchTab(tabId) {
  activeTab = tabId;
  document.querySelectorAll('#topNav button').forEach(b => b.classList.remove('active'));
  const btn = Array.from(document.querySelectorAll('#topNav button')).find(b => b.getAttribute('onclick')?.includes(tabId));
  if (btn) btn.classList.add('active');

  document.querySelectorAll('.panel').forEach(p => p.classList.remove('active'));
  const panel = document.getElementById(\`panel-\${tabId}\`);
  if (panel) panel.classList.add('active');

  if (tabId === 'raw') renderRawJson();
  if (tabId === 'access') renderAccess();
}

// ---- Login Flow ----------------------------------------------------------
function showLoginOverlay(errText = '') {
  document.getElementById('loginOverlay').style.display = 'flex';
  document.getElementById('app').style.display = 'none';
  const err = document.getElementById('loginErr');
  if (errText) {
    err.textContent = errText;
    err.style.display = 'block';
  } else {
    err.style.display = 'none';
  }
}

function hideLoginOverlay() {
  document.getElementById('loginOverlay').style.display = 'none';
  document.getElementById('app').style.display = 'flex';
}

async function doLogin() {
  const input = document.getElementById('loginKey').value.trim();
  if (!input && !getKey()) {
    showLoginOverlay('请输入 PROXY_API_KEY');
    return;
  }
  if (input) setKey(input);

  try {
    await loadAllData();
    hideLoginOverlay();
    toast('登录成功', 'ok');
  } catch (e) {
    showLoginOverlay('验证失败: ' + (e?.message || e));
  }
}

function doLogout() {
  clearKey();
  showLoginOverlay();
}

// ---- Data Fetching -------------------------------------------------------
async function loadAllData() {
  try {
    const [cfgRes, healthRes] = await Promise.all([
      api('GET', '/api/config'),
      api('GET', '/health').catch(() => ({})),
    ]);

    cfg = cfgRes.config || cfgRes;
    cfgMeta = {
      source: cfgRes.source || 'EdgeOne KV',
      lastModified: cfgRes.last_modified,
    };
    healthData = healthRes;

    renderAll();
  } catch (e) {
    console.error('Failed to load data', e);
    throw e;
  }
}

// ---- Rendering -----------------------------------------------------------
function renderAll() {
  renderDashboard();
  renderAgentModels();
  renderProviders();
  renderSettings();
  renderRawJson();
  renderAccess();
}

function renderSettings() {
  const s = cfg.settings || {};
  const elStrat = document.getElementById('set_routing_strategy');
  if (elStrat) elStrat.value = s.agent_routing_strategy || cfg.agent_routing_strategy || 'sticky_failover';

  const elBudget = document.getElementById('set_request_total_budget_sec');
  if (elBudget) elBudget.value = s.request_total_budget_sec || 25;

  const elUpstream = document.getElementById('set_upstream_timeout_sec');
  if (elUpstream) elUpstream.value = s.upstream_timeout_sec || 15;

  const elRetries = document.getElementById('set_schedule_total_budget');
  if (elRetries) elRetries.value = s.schedule_total_budget || 3;

  const elProvMax = document.getElementById('set_max_attempts_per_provider');
  if (elProvMax) elProvMax.value = s.max_attempts_per_provider || 2;

  const elFastFail = document.getElementById('set_fast_failover_provider_down');
  if (elFastFail) elFastFail.checked = s.fast_failover_provider_down !== false;

  const elCd429 = document.getElementById('set_cooldown_429_sec');
  if (elCd429) elCd429.value = s.cooldown_429_sec || 60;

  const elCd5xx = document.getElementById('set_cooldown_5xx_sec');
  if (elCd5xx) elCd5xx.value = s.cooldown_5xx_sec || 30;

  const elCircuit = document.getElementById('set_circuit_break_threshold');
  if (elCircuit) elCircuit.value = s.circuit_break_threshold || 3;

  const elCd403 = document.getElementById('set_cooldown_403_sec');
  if (elCd403) elCd403.value = s.cooldown_403_sec || 600;
}

async function saveSettings() {
  cfg.settings = {
    agent_routing_strategy: document.getElementById('set_routing_strategy').value,
    request_total_budget_sec: Number(document.getElementById('set_request_total_budget_sec').value) || 25,
    upstream_timeout_sec: Number(document.getElementById('set_upstream_timeout_sec').value) || 15,
    schedule_total_budget: Number(document.getElementById('set_schedule_total_budget').value) || 3,
    max_attempts_per_provider: Number(document.getElementById('set_max_attempts_per_provider').value) || 2,
    fast_failover_provider_down: document.getElementById('set_fast_failover_provider_down').checked,
    cooldown_429_sec: Number(document.getElementById('set_cooldown_429_sec').value) || 60,
    cooldown_5xx_sec: Number(document.getElementById('set_cooldown_5xx_sec').value) || 30,
    circuit_break_threshold: Number(document.getElementById('set_circuit_break_threshold').value) || 3,
    cooldown_403_sec: Number(document.getElementById('set_cooldown_403_sec').value) || 600,
  };
  const ok = await persistConfig();
  if (ok) {
    toast('全局策略设置已保存生效', 'ok');
  }
}

function resetSettingsToDefault() {
  document.getElementById('set_routing_strategy').value = 'sticky_failover';
  document.getElementById('set_request_total_budget_sec').value = 25;
  document.getElementById('set_upstream_timeout_sec').value = 15;
  document.getElementById('set_schedule_total_budget').value = 3;
  document.getElementById('set_max_attempts_per_provider').value = 2;
  document.getElementById('set_fast_failover_provider_down').checked = true;
  document.getElementById('set_cooldown_429_sec').value = 60;
  document.getElementById('set_cooldown_5xx_sec').value = 30;
  document.getElementById('set_circuit_break_threshold').value = 3;
  document.getElementById('set_cooldown_403_sec').value = 600;
  toast('已填入推荐默认值，请点击保存生效', 'ok');
}

function renderDashboard() {
  const models = Object.keys(cfg.agent_models || {});
  const providers = cfg.providers || {};
  let totalKeys = 0;
  for (const p of Object.values(providers)) {
    totalKeys += Object.keys(p.keys || {}).length;
  }

  document.getElementById('statModelCount').textContent = models.length;
  document.getElementById('statTotalKeys').textContent = totalKeys;

  const badge = document.getElementById('configSourceBadge');
  if (badge) {
    badge.textContent = \`\${cfgMeta.source || 'KV'} 同步中\`;
  }

  // Quick models table
  const tbody = document.getElementById('quickModelsBody');
  if (tbody) {
    tbody.innerHTML = '';
    if (models.length === 0) {
      tbody.innerHTML = '<tr><td colspan="4" class="text-secondary" style="text-align:center;padding:24px;">暂未配置 Agent 模型</td></tr>';
      return;
    }

    for (const m of models) {
      const item = cfg.agent_models[m];
      const keys = item.keys || [];
      const tr = document.createElement('tr');
      tr.innerHTML = \`
        <td style="font-weight:600;"><span class="mono">\${m}</span></td>
        <td class="mono text-secondary">\${item.upstream_model || m}</td>
        <td><span class="badge badge-neutral">\${keys.length} 个候选 Key</span></td>
        <td>
          <button class="btn btn-ghost btn-sm" onclick="switchTab('agents')">查看</button>
        </td>
      \`;
      tbody.appendChild(tr);
    }
  }
}

// Protocol Metadata & Helpers (Factual Badges)
const PROTOCOLS = {
  chat: { label: 'OpenAI Chat', short: 'OpenAI', badgeClass: 'badge-success', title: '支持 OpenAI Chat 格式 (/v1/chat/completions)' },
  messages: { label: 'Anthropic Messages', short: 'Messages', badgeClass: 'badge-warning', title: '支持 Anthropic Claude Messages 格式 (/v1/messages)' },
  responses: { label: 'OpenAI Responses', short: 'Responses', badgeClass: 'badge-purple', title: '支持 OpenAI Responses 格式 (/v1/responses)' }
};

function getProviderProtocols(name, provObj){
  const p = provObj || (cfg && cfg.providers && cfg.providers[name]) || {};
  if (Array.isArray(p.protocols) && p.protocols.length > 0) {
    return p.protocols;
  }
  const protos = ['chat'];
  const lower = (name || '').toLowerCase();
  const clean = lower.replace(/[^a-z0-9]/g, '');
  const preset = PRESET_DEFINITIONS[clean] || PRESET_DEFINITIONS[lower];
  if (p.anthropic_messages || clean === 'minimax' || clean === 'bai' || lower === 'b.ai' || p.anthropic_base_url || (preset && preset.anthropic_base_url)) {
    protos.push('messages');
  }
  if (p.openai_responses || p.supports_responses) {
    protos.push('responses');
  }
  return protos;
}

function getModelProtocols(modelName){
  const m = cfg && cfg.agent_models ? cfg.agent_models[modelName] : null;
  if (!m || !m.keys || !m.keys.length) return ['chat'];
  const set = new Set();
  for (const b of m.keys) {
    const provProtos = getProviderProtocols(b.provider);
    provProtos.forEach(pr => set.add(pr));
  }
  return set.size ? Array.from(set) : ['chat'];
}

function renderProtocolBadges(protoList, isShort=true){
  return (protoList || ['chat']).map(pr => {
    const meta = PROTOCOLS[pr] || { label: pr, short: pr, badgeClass: 'badge-neutral', title: pr };
    return \`<span class="badge \${meta.badgeClass}" title="\${esc(meta.title)}" style="font-weight:600;font-size:11px;padding:2px 7px;">\${esc(isShort ? meta.short : meta.label)}</span>\`;
  }).join(' ');
}

function renderAgentModels() {
  const box = document.getElementById('agentModelsBox');
  if (!box) return;
  box.innerHTML = '';
  const models = Object.keys(cfg.agent_models || {});

  if (models.length === 0) {
    box.innerHTML = '<div class="card card-pad empty">暂未配置 Agent 模型</div>';
    return;
  }

  for (const m of models) {
    const item = cfg.agent_models[m];
    const keys = item.keys || [];
    const card = document.createElement('div');
    card.className = 'card';

    let keysRowsHtml = '';
    const activeKey = item.active_key || (keys[0] ? keys[0].key : '');
    const strategy = cfg.agent_routing_strategy || 'sticky_failover';
    
    let strategyLabel = \`\${keys.length} 个 Key · 粘性故障转移 (固定当前，遇错顺延)\`;
    if(strategy === 'manual'){
      strategyLabel = \`\${keys.length} 个 Key · 🔒 纯手动直通 (当前使用: \${activeKey})\`;
    } else if(strategy === 'round_robin'){
      strategyLabel = \`\${keys.length} 个 Key · 轮询负载均衡\`;
    } else if(strategy === 'priority_fallback'){
      strategyLabel = \`\${keys.length} 个 Key · 主备优先级降级\`;
    } else if(strategy === 'latency_based'){
      strategyLabel = \`\${keys.length} 个 Key · 最低延迟优先\`;
    }

    keys.forEach((b, idx) => {
      const isActive = (b.key === activeKey);
      const cacheKey = \`model:\${m}:\${b.provider}:\${b.key}\`;
      const latInfo = modelLatencyCache[cacheKey];
      let latBadge = '';
      if (latInfo) {
        latBadge = latInfo.ok
          ? \`<span class="badge badge-success">\${latInfo.latency_ms}ms</span>\`
          : \`<span class="badge badge-error">\${latInfo.status || 'ERR'}</span>\`;
      }

      const setActiveBtn = isActive
        ? \`<span class="badge badge-success" style="font-size:11px;padding:2px 8px;font-weight:600;">使用中</span>\`
        : \`<button class="btn btn-secondary btn-sm" onclick="setActiveAgentKey('\${m}', '\${b.key}')" title="切换使用该 Key" style="font-size:11px;padding:2px 8px;">切</button>\`;

      keysRowsHtml += \`
        <div class="provider-row" style="padding:10px 16px;">
          <div style="display:flex;align-items:center;gap:10px;">
            <span class="badge badge-neutral">#\${idx+1}</span>
            <span style="font-weight:600;">\${b.provider}</span>
            <span class="key-chip">\${b.key}</span>
            \${latBadge}
          </div>
          <div style="display:flex;align-items:center;gap:6px;">
            \${setActiveBtn}
            <button class="btn btn-ghost btn-sm" onclick="moveModelKeyBinding('\${m}', \${idx}, -1)" \${idx === 0 ? 'disabled' : ''} title="上移">↑</button>
            <button class="btn btn-ghost btn-sm" onclick="moveModelKeyBinding('\${m}', \${idx}, 1)" \${idx === keys.length - 1 ? 'disabled' : ''} title="下移">↓</button>
            <button class="btn btn-ghost btn-sm" onclick="testModelKey('\${m}', '\${b.provider}', '\${b.key}')">探活</button>
            <button class="btn btn-danger btn-sm" onclick="removeModelKeyBinding('\${m}', \${idx})">移除</button>
          </div>
        </div>
      \`;
    });

    card.innerHTML = \`
      <div class="card-head">
        <div>
          <h3>\${m} <span style="display:inline-flex;gap:4px;vertical-align:middle;margin-left:4px;">\${renderProtocolBadges(getModelProtocols(m), true)}</span></h3>
        <div class="meta mono mt-2">上游映射: \${item.upstream_model || m} · \${strategyLabel}</div>
        </div>
        <div style="display:flex;gap:8px;">
          <button class="btn btn-ghost btn-sm" onclick="testAllKeysForModel('\${m}')">探活全部</button>
          <button class="btn btn-primary btn-sm" onclick="openEditModelModal('\${m}')">编辑</button>
          <button class="btn btn-danger btn-sm" onclick="deleteModel('\${m}')">删除</button>
        </div>
      </div>
      <div style="background:var(--color-bg-page);">\${keysRowsHtml || '<div class="empty">暂未绑定 Key</div>'}</div>
    \`;
    box.appendChild(card);
  }
}

function renderProviders() {
  const box = document.getElementById('providersBox');
  if (!box) return;
  box.innerHTML = '';
  const providers = cfg.providers || {};
  const provNames = Object.keys(providers);

  if (provNames.length === 0) {
    box.innerHTML = '<div class="card card-pad empty">暂未配置供应商</div>';
    return;
  }

  for (const p of provNames) {
    const prov = providers[p];
    const keysObj = prov.keys || {};
    const keyLabels = Object.keys(keysObj);
    const card = document.createElement('div');
    card.className = 'card';

    let keysListHtml = '';
    keyLabels.forEach(k => {
      const val = keysObj[k];
      const masked = val ? \`\${val.slice(0, 6)}...\${val.slice(-4)}\` : '';
      const cacheKey = \`prov:\${p}:\${k}\`;
      const latInfo = modelLatencyCache[cacheKey];
      let latBadge = '';
      if (latInfo) {
        latBadge = latInfo.ok
          ? \`<span class="badge badge-success">\${latInfo.latency_ms}ms</span>\`
          : \`<span class="badge badge-error">\${latInfo.status || 'ERR'}</span>\`;
      }

      keysListHtml += \`
        <div class="provider-row" style="padding:10px 16px;">
          <div style="display:flex;align-items:center;gap:10px;">
            <span style="font-weight:600;">\${k}</span>
            <span class="mono text-secondary" style="font-size:12px;">\${masked}</span>
            \${latBadge}
          </div>
          <div style="display:flex;gap:6px;">
            <button class="btn btn-ghost btn-sm" onclick="testSingleKey('\${p}', '\${k}')">测试</button>
            <button class="btn btn-ghost btn-sm" onclick="openEditKeyModal('\${p}', '\${k}', '\${val}')">编辑</button>
            <button class="btn btn-danger btn-sm" onclick="deleteKey('\${p}', '\${k}')">删除</button>
          </div>
        </div>
      \`;
    });

    const protos = getProviderProtocols(p, prov);
    const protoBadges = renderProtocolBadges(protos, false);
    const messagesUrlPart = (prov.anthropic_base_url && prov.anthropic_base_url !== prov.base_url) ? \` · Messages: \${prov.anthropic_base_url}\` : '';

    card.innerHTML = \`
      <div class="card-head">
        <div>
          <h3>\${p} <span style="display:inline-flex;gap:4px;vertical-align:middle;margin-left:4px;">\${protoBadges}</span></h3>
        <div class="meta mono mt-2">\${prov.base_url || '—'}\${messagesUrlPart} · \${keyLabels.length} 个 Key</div>
        </div>
        <div style="display:flex;gap:8px;">
          <button class="btn btn-primary btn-sm" onclick="openAddKeyModal('\${p}')">+ 新增 Key</button>
          <button class="btn btn-danger btn-sm" onclick="deleteProvider('\${p}')">删除供应商</button>
        </div>
      </div>
      <div style="background:var(--color-bg-page);">\${keysListHtml || '<div class="empty">暂无 Key</div>'}</div>
    \`;
    box.appendChild(card);
  }
}

function renderRawJson() {
  const ta = document.getElementById('rawJsonText');
  if (ta) ta.value = JSON.stringify(cfg, null, 2);
}

function renderAccess() {
  const origin = window.location.origin;
  const base = \`\${origin}/v1\`;
  const models = Object.keys(cfg.agent_models || {});
  const messagesModels = models.filter(m => getModelProtocols(m).includes('messages'));
  const demoMessages = messagesModels[0] || models[0] || 'qwen3.8-flash';
  const proxyKey = getKey() || 'YOUR_PROXY_API_KEY';

  const setT = (id, txt) => { const el = document.getElementById(id); if (el) el.textContent = txt; };
  setT('accBaseUrl', base);
  setT('accModelsList', models.join(', ') || '—');

  const protoContainer = document.getElementById('accProtocols');
  if (protoContainer) {
    const activeProtos = new Set(['chat']);
    if (messagesModels.length || Object.entries(cfg.providers || {}).some(([n, p]) => getProviderProtocols(n, p).includes('messages'))) {
      activeProtos.add('messages');
    }
    if (Object.entries(cfg.providers || {}).some(([n, p]) => getProviderProtocols(n, p).includes('responses'))) {
      activeProtos.add('responses');
    }
    protoContainer.innerHTML = renderProtocolBadges(Array.from(activeProtos), false);
  }

  // 1. OpenAI Chat
  const pySample = \`from openai import OpenAI

client = OpenAI(
    api_key="\${proxyKey}",
    base_url="\${base}"
)

response = client.chat.completions.create(
    model="\${models[0] || 'qwen3.8-flash'}",
    messages=[{"role": "user", "content": "你好，请介绍你自己。"}],
    stream=True
)

for chunk in response:
    content = chunk.choices[0].delta.content or ""
    print(content, end="", flush=True)
\`;
  setT('accPy', pySample);

  // 2. Anthropic Messages
  const messagesPySample = \`import anthropic

client = anthropic.Anthropic(
    api_key="\${proxyKey}",
    base_url="\${base}"  # 直连本网关
)

# 使用支持 Messages 协议的模型（当前支持：\${messagesModels.join(', ') || demoMessages}）
response = client.messages.create(
    model="\${demoMessages}",
    max_tokens=1024,
    messages=[{"role": "user", "content": "你好，请介绍你自己。"}]
)

print(response.content[0].text)
\`;
  setT('accMessagesPy', messagesPySample);

  const curlSample = \`curl -X POST \${base}/chat/completions \\\\
  -H "Authorization: Bearer \${proxyKey}" \\\\
  -H "Content-Type: application/json" \\\\
  -d '{
    "model": "\${models[0] || 'qwen3.8-flash'}",
    "messages": [{"role": "user", "content": "1+1="}],
    "stream": true
  }'\`;
  setT('accCurl', curlSample);
}

// ---- Key & Model Test ---------------------------------------------------
async function testModelKey(modelName, provider, key) {
  const item = cfg.agent_models?.[modelName];
  const upstreamModel = item?.upstream_model || modelName;
  toast(\`探活模型 \${modelName} (\${provider}/\${key})...\`, 'ok');
  try {
    const res = await api('GET', \`/api/config?action=test&provider=\${encodeURIComponent(provider)}&key=\${encodeURIComponent(key)}&model=\${encodeURIComponent(upstreamModel)}\`);
    modelLatencyCache[\`model:\${modelName}:\${provider}:\${key}\`] = res;
    renderAgentModels();
    if (res.ok) {
      toast(\`\${modelName} [\${provider}/\${key}] 成功 (\${res.latency_ms}ms)\`, 'ok');
    } else {
      toast(\`\${modelName} [\${provider}/\${key}] 异常 (HTTP \${res.status || 'ERR'} - \${res.verdict || res.error || ''})\`, 'err');
    }
  } catch (e) {
    toast(\`探活异常: \${e?.message || e}\`, 'err');
  }
}

async function testSingleKey(provider, key) {
  toast(\`测试供应商 \${provider}/\${key}...\`, 'ok');
  try {
    const res = await api('GET', \`/api/config?action=test&provider=\${encodeURIComponent(provider)}&key=\${encodeURIComponent(key)}\`);
    modelLatencyCache[\`prov:\${provider}:\${key}\`] = res;
    renderProviders();
    if (res.ok) {
      toast(\`\${provider}/\${key} 连接成功 (\${res.latency_ms}ms)\`, 'ok');
    } else {
      toast(\`\${provider}/\${key} 探活异常 (HTTP \${res.status || 'ERR'})\`, 'err');
    }
  } catch (e) {
    toast(\`探活异常: \${e?.message || e}\`, 'err');
  }
}

// ---- Modals & Actions ----------------------------------------------------
function openModal(id) {
  document.getElementById(id).classList.add('show');
}
function closeModal(id) {
  document.getElementById(id).classList.remove('show');
}

// Preset Selection Handler
function onPresetSelected() {
  const presetId = document.getElementById('m_prov_preset').value;
  const nameInput = document.getElementById('m_prov_name');
  const urlInput = document.getElementById('m_prov_url');
  const descEl = document.getElementById('m_prov_desc');
  const modelsWrap = document.getElementById('m_prov_models_wrap');
  const modelsList = document.getElementById('m_prov_models_list');

  if (!presetId || !PRESET_DEFINITIONS[presetId]) {
    nameInput.value = '';
    urlInput.value = '';
    descEl.style.display = 'none';
    modelsWrap.style.display = 'none';
    modelsList.innerHTML = '';
    return;
  }

  const preset = PRESET_DEFINITIONS[presetId];
  nameInput.value = preset.id;
  urlInput.value = preset.base_url;
  descEl.textContent = preset.description || '';
  descEl.style.display = 'block';

  // Preset protocols sync
  const presetProtos = preset.protocols || (preset.anthropic_base_url ? ['chat', 'messages'] : ['chat']);
  const cChat = document.getElementById('m_prov_proto_chat'); if(cChat) cChat.checked = presetProtos.includes('chat');
  const cMsg = document.getElementById('m_prov_proto_messages'); if(cMsg) cMsg.checked = presetProtos.includes('messages');
  const cResp = document.getElementById('m_prov_proto_responses'); if(cResp) cResp.checked = presetProtos.includes('responses');

  // Custom Anthropic URL
  const customToggle = document.getElementById('m_prov_custom_url_toggle');
  const customSection = document.getElementById('m_prov_custom_url_section');
  const customUrlInput = document.getElementById('m_prov_anthropic_url');
  if (preset.anthropic_base_url && preset.anthropic_base_url !== preset.base_url) {
    if (customToggle) customToggle.checked = true;
    if (customSection) customSection.style.display = 'block';
    if (customUrlInput) customUrlInput.value = preset.anthropic_base_url;
  } else {
    if (customToggle) customToggle.checked = false;
    if (customSection) customSection.style.display = 'none';
    if (customUrlInput) customUrlInput.value = '';
  }

  // Render recommended models checklist
  modelsList.innerHTML = '';
  if (preset.recommended_models && preset.recommended_models.length > 0) {
    modelsWrap.style.display = 'block';
    preset.recommended_models.forEach((rm) => {
      const row = document.createElement('div');
      row.style.marginBottom = '6px';
      row.innerHTML = \`
        <label class="checkbox" style="align-items:flex-start;">
          <input type="checkbox" data-model="\${rm.name}" data-upstream="\${rm.upstream}" \${rm.checked ? 'checked' : ''}>
          <div style="font-size:12px;">
            <div style="font-weight:600;color:var(--color-text-1);">\${rm.name} <span class="mono text-secondary" style="font-weight:normal;">(映射: \${rm.upstream})</span></div>
            <div class="text-secondary" style="font-size:11px;margin-top:2px;">\${rm.desc || ''}</div>
          </div>
        </label>
      \`;
      modelsList.appendChild(row);
    });
  } else {
    modelsWrap.style.display = 'none';
  }
}

function onEdgeOneCustomUrlToggleChange() {
  const isChecked = document.getElementById('m_prov_custom_url_toggle')?.checked;
  const wrap = document.getElementById('m_prov_custom_url_section');
  if (wrap) wrap.style.display = isChecked ? 'block' : 'none';
}

function openAddProviderModal() {
  document.getElementById('providerModalTitle').textContent = '新增供应商';
  document.getElementById('presetSelectGroup').style.display = 'block';
  document.getElementById('m_prov_preset').value = '';
  document.getElementById('m_prov_name').value = '';
  document.getElementById('m_prov_name').disabled = false;
  document.getElementById('m_prov_url').value = '';
  const cChat = document.getElementById('m_prov_proto_chat'); if(cChat) cChat.checked = true;
  const cMsg = document.getElementById('m_prov_proto_messages'); if(cMsg) cMsg.checked = false;
  const cResp = document.getElementById('m_prov_proto_responses'); if(cResp) cResp.checked = false;
  const customToggle = document.getElementById('m_prov_custom_url_toggle'); if(customToggle) customToggle.checked = false;
  const customSection = document.getElementById('m_prov_custom_url_section'); if(customSection) customSection.style.display = 'none';
  const uInput = document.getElementById('m_prov_anthropic_url'); if(uInput) uInput.value = '';
  document.getElementById('m_prov_desc').style.display = 'none';
  document.getElementById('m_prov_models_wrap').style.display = 'none';
  openModal('providerModal');
}

async function saveProviderModal() {
  const name = document.getElementById('m_prov_name').value.trim();
  const url = document.getElementById('m_prov_url').value.trim();
  if (!name || !url) { toast('请填写供应商与 Base URL', 'err'); return; }

  const selectedProtos = [];
  if (document.getElementById('m_prov_proto_chat')?.checked) selectedProtos.push('chat');
  if (document.getElementById('m_prov_proto_messages')?.checked) selectedProtos.push('messages');
  if (document.getElementById('m_prov_proto_responses')?.checked) selectedProtos.push('responses');
  if (!selectedProtos.length) { toast('请至少选择一种支持的协议类型', 'err'); return; }

  const backupCfg = JSON.parse(JSON.stringify(cfg));

  cfg.providers = cfg.providers || {};
  cfg.providers[name] = cfg.providers[name] || { keys: {} };
  cfg.providers[name].base_url = url;
  cfg.providers[name].protocols = selectedProtos;
  cfg.providers[name].anthropic_messages = selectedProtos.includes('messages');

  const customToggle = document.getElementById('m_prov_custom_url_toggle');
  const anthropicUrl = customToggle?.checked ? document.getElementById('m_prov_anthropic_url')?.value.trim() : '';
  if (selectedProtos.includes('messages') && anthropicUrl) {
    cfg.providers[name].anthropic_base_url = anthropicUrl;
  } else {
    delete cfg.providers[name].anthropic_base_url;
  }

  // If recommended models were checked, auto-register them
  const checkedModels = document.querySelectorAll('#m_prov_models_list input[type="checkbox"]:checked');
  if (checkedModels.length > 0) {
    cfg.agent_models = cfg.agent_models || {};
    checkedModels.forEach((cb) => {
      const modelName = cb.dataset.model;
      const upstream = cb.dataset.upstream || modelName;
      if (!cfg.agent_models[modelName]) {
        cfg.agent_models[modelName] = {
          upstream_model: upstream,
          keys: [],
        };
      }
    });
  }

  const ok = await persistConfig();
  if (ok) {
    closeModal('providerModal');
  } else {
    cfg = backupCfg;
    renderAll();
  }
}

async function deleteProvider(name) {
  if (!confirm(\`删除供应商「\${name}」及其全部 Key？\`)) return;
  delete cfg.providers[name];
  await persistConfig();
}

function openAddKeyModal(prov) {
  document.getElementById('keyModalTitle').textContent = \`为 \${prov} 新增 Key\`;
  document.getElementById('m_key_prov').value = prov;
  document.getElementById('m_key_old_label').value = '';
  document.getElementById('m_key_label').value = '';
  document.getElementById('m_key_val').value = '';
  const skipCb = document.getElementById('m_key_skip'); if (skipCb) skipCb.checked = false;
  const diagBox = document.getElementById('m_key_diag_box'); if (diagBox) { diagBox.style.display = 'none'; diagBox.innerHTML = ''; }
  const hintEl = document.getElementById('m_key_proto_hint');
  if (hintEl) {
    const protos = getProviderProtocols(prov);
    hintEl.innerHTML = \`<div style="display:flex;align-items:center;justify-content:space-between;"><span>所属供应商: <b>\${esc(prov)}</b></span><span>需校验协议: \${renderProtocolBadges(protos)}</span></div>\`;
  }
  openModal('keyModal');
}

function openEditKeyModal(prov, label, val) {
  document.getElementById('keyModalTitle').textContent = \`编辑 \${prov} Key: \${label}\`;
  document.getElementById('m_key_prov').value = prov;
  document.getElementById('m_key_old_label').value = label;
  document.getElementById('m_key_label').value = label;
  document.getElementById('m_key_val').value = val;
  const skipCb = document.getElementById('m_key_skip'); if (skipCb) skipCb.checked = true;
  const diagBox = document.getElementById('m_key_diag_box'); if (diagBox) { diagBox.style.display = 'none'; diagBox.innerHTML = ''; }
  const hintEl = document.getElementById('m_key_proto_hint');
  if (hintEl) {
    const protos = getProviderProtocols(prov);
    hintEl.innerHTML = \`<div style="display:flex;align-items:center;justify-content:space-between;"><span>所属供应商: <b>\${esc(prov)}</b></span><span>需校验协议: \${renderProtocolBadges(protos)}</span></div>\`;
  }
  openModal('keyModal');
}

async function saveKeyModal() {
  const prov = document.getElementById('m_key_prov').value;
  const oldLabel = (document.getElementById('m_key_old_label').value || '').trim();
  const label = document.getElementById('m_key_label').value.trim();
  const val = document.getElementById('m_key_val').value.trim();
  const skip = document.getElementById('m_key_skip')?.checked;
  const diagBox = document.getElementById('m_key_diag_box');
  if (diagBox) { diagBox.style.display = 'none'; diagBox.innerHTML = ''; }

  if (!label || !val) { toast('请填写 Key 别名与密钥明文', 'err'); return; }

  cfg.providers[prov] = cfg.providers[prov] || { keys: {} };
  cfg.providers[prov].keys = cfg.providers[prov].keys || {};

  if (oldLabel && oldLabel !== label) {
    if (cfg.providers[prov].keys[label] !== undefined) {
      toast(\`Key 别名「\${label}」已存在，请换一个别名\`, 'err');
      return;
    }
  }

  // If online verification not skipped, test protocols
  if (!skip) {
    const spinner = document.getElementById('m_key_spinner');
    if (spinner) spinner.style.display = 'block';
    const pObj = cfg.providers[prov] || {};
    const protos = getProviderProtocols(prov, pObj);

    try {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), 15000);
      const r = await fetch('/api/admin/verify-key', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Authorization': \`Bearer \${getKey()}\` },
        body: JSON.stringify({
          base_url: pObj.base_url,
          anthropic_base_url: pObj.anthropic_base_url,
          api_key: val,
          provider: prov,
          protocols: protos
        }),
        signal: controller.signal
      });
      clearTimeout(timer);
      const d = await r.json();

      if (d.valid) {
        const latList = [];
        for (const pr of protos) {
          const res = (d.protocols && d.protocols[pr]);
          if (res && res.latency_ms) latList.push(\`\${PROTOCOLS[pr]?.short || pr} \${res.latency_ms}ms\`);
        }
        toast(\`✅ Key 校验全部通过 (\${latList.join(' / ') || '成功'})\`, 'ok');
      } else {
        if (diagBox) {
          let html = '<div style="font-weight:700;margin-bottom:8px;color:var(--color-danger);display:flex;align-items:center;gap:6px;">⚠️ 协议连通性未完全通过 (已阻止保存)</div>';
          html += '<div style="display:flex;flex-direction:column;gap:6px;font-size:12px;">';
          for (const pr of protos) {
            const res = (d.protocols && d.protocols[pr]) || { valid: false, error: '未测试' };
            const pName = PROTOCOLS[pr] ? PROTOCOLS[pr].label : pr;
            if (res.valid) {
              html += \`<div style="display:flex;align-items:center;gap:6px;color:var(--color-success);"><span>🟢</span> <b>\${esc(pName)}</b>: 验证通过 (\${res.latency_ms || 0}ms)</div>\`;
            } else {
              html += \`<div style="display:flex;align-items:flex-start;gap:6px;color:var(--color-danger);"><span>🔴</span> <div><b>\${esc(pName)}</b>: 验证失败 (\${esc(res.error || '请求未通')})</div></div>\`;
            }
          }
          html += '</div>';
          html += '<div class="text-secondary mt-2" style="font-size:11px;border-top:1px solid var(--color-border);padding-top:6px;">提示：请核对并修改密钥；若确属受限网络，请勾选上方「跳过连通性在线校验」后重新点击保存。</div>';
          diagBox.innerHTML = html;
          diagBox.style.display = 'block';
        }
        toast('协议校验存在失败项，已阻止保存', 'err');
        return;
      }
    } catch (e) {
      if (diagBox) {
        diagBox.innerHTML = \`<div style="color:var(--color-danger);font-size:12px;">❌ 验证请求失败: \${esc(e.message)}。<br>如网络受限，可勾选上方「跳过连通性在线校验」后强制保存。</div>\`;
        diagBox.style.display = 'block';
      }
      toast('网络请求异常: ' + e.message, 'err');
      return;
    } finally {
      if (spinner) spinner.style.display = 'none';
    }
  }

  const backupCfg = JSON.parse(JSON.stringify(cfg));

  if (oldLabel && oldLabel !== label) {
    delete cfg.providers[prov].keys[oldLabel];
    if (cfg.agent_models) {
      Object.values(cfg.agent_models).forEach(m => {
        (m.keys || []).forEach(x => {
          if (x.provider === prov && x.key === oldLabel) x.key = label;
        });
      });
    }
  }

  cfg.providers[prov].keys[label] = val;
  const ok = await persistConfig();
  if (ok) {
    closeModal('keyModal');
  } else {
    cfg = backupCfg;
    renderAll();
  }
}

async function deleteKey(prov, label) {
  if (!confirm(\`删除 Key「\${label}」？\`)) return;
  if (cfg.providers && cfg.providers[prov] && cfg.providers[prov].keys) {
    delete cfg.providers[prov].keys[label];
  }
  if (cfg.agent_models) {
    Object.values(cfg.agent_models).forEach(m => {
      m.keys = (m.keys || []).filter(x => !(x.provider === prov && x.key === label));
    });
  }
  await persistConfig();
}

let currentEditingModelKeys = [];

function populateModelProvFilter() {
  const select = document.getElementById('m_model_prov_filter');
  if (!select) return;
  select.innerHTML = '<option value="">全部供应商</option>';
  const providers = cfg.providers || {};
  for (const p of Object.keys(providers)) {
    const opt = document.createElement('option');
    opt.value = p;
    opt.textContent = p;
    select.appendChild(opt);
  }
}

function onModelProvFilterChange() {
  const filterProv = document.getElementById('m_model_prov_filter').value;
  renderBindingsCheckboxes(getSelectedBindingsFromDom(), filterProv);
  renderQuickModelTags(filterProv);
}

function renderQuickModelTags(prov) {
  const tagBox = document.getElementById('m_quick_model_tags');
  if (!tagBox) return;
  tagBox.innerHTML = '';
  if (!prov) return;

  const preset = PRESETS[prov.toLowerCase()];
  if (preset && preset.models && preset.models.length > 0) {
    preset.models.forEach(m => {
      const tag = document.createElement('button');
      tag.type = 'button';
      tag.className = 'btn btn-ghost btn-sm';
      tag.style.cssText = 'font-size:11px;padding:2px 8px;height:24px;background:var(--color-bg-subtle);';
      tag.textContent = \`+ 填入 \${m.id}\`;
      tag.onclick = () => {
        document.getElementById('m_model_name').value = m.id;
        document.getElementById('m_upstream_model').value = m.upstream || '';
        toggleProviderKeys(prov, true);
      };
      tagBox.appendChild(tag);
    });
  }
}

function getSelectedBindingsFromDom() {
  const checkedBoxes = document.querySelectorAll('#m_bindings_container input[type="checkbox"]:checked');
  const list = Array.from(checkedBoxes).map(cb => ({
    provider: cb.dataset.provider,
    key: cb.dataset.key,
  }));
  if (list.length > 0) return list;
  return currentEditingModelKeys;
}

function toggleSelectAllKeys(selectAll) {
  const checkboxes = document.querySelectorAll('#m_bindings_container input[type="checkbox"]');
  checkboxes.forEach(cb => {
    cb.checked = selectAll;
  });
}

function toggleProviderKeys(prov, forceCheck = false) {
  const checkboxes = document.querySelectorAll(\`#m_bindings_container input[data-provider="\${prov}"]\`);
  const allChecked = Array.from(checkboxes).every(cb => cb.checked);
  checkboxes.forEach(cb => {
    cb.checked = forceCheck ? true : !allChecked;
  });
}

function openAddModelModal() {
  openAddAgentModal();
}

function openAddAgentModal() {
  document.getElementById('agentModalTitle').textContent = '新增 Agent 模型';
  document.getElementById('m_model_old_name').value = '';
  document.getElementById('m_model_name').value = '';
  document.getElementById('m_model_name').disabled = false;
  document.getElementById('m_upstream_model').value = '';
  currentEditingModelKeys = [];
  populateModelProvFilter();
  document.getElementById('m_model_prov_filter').value = '';
  renderBindingsCheckboxes([]);
  renderQuickModelTags('');
  openModal('agentModal');
}

function openEditModelModal(m) {
  document.getElementById('agentModalTitle').textContent = \`编辑 Agent 模型: \${m}\`;
  document.getElementById('m_model_old_name').value = m;
  document.getElementById('m_model_name').value = m;
  document.getElementById('m_model_name').disabled = false; // Allow renaming
  const item = cfg.agent_models[m] || {};
  document.getElementById('m_upstream_model').value = item.upstream_model || '';
  currentEditingModelKeys = item.keys || [];
  populateModelProvFilter();
  document.getElementById('m_model_prov_filter').value = '';
  renderBindingsCheckboxes(item.keys || []);
  renderQuickModelTags('');
  openModal('agentModal');
}

function renderBindingsCheckboxes(existingKeys = [], filterProv = '') {
  const container = document.getElementById('m_bindings_container');
  if (!container) return;
  container.innerHTML = '';
  const providers = cfg.providers || {};
  let provList = Object.keys(providers);
  if (filterProv) {
    provList = provList.filter(p => p === filterProv);
  }

  let totalKeys = 0;
  for (const p of provList) {
    const prov = providers[p];
    const keysObj = prov.keys || {};
    const keyLabels = Object.keys(keysObj);
    if (keyLabels.length === 0) continue;

    const groupDiv = document.createElement('div');
    groupDiv.className = 'provider-key-group';
    groupDiv.style.cssText = 'border:1px solid var(--color-border);border-radius:var(--radius-sm);background:#fff;padding:8px 12px;';

    let keysCheckboxesHtml = '';
    keyLabels.forEach(k => {
      totalKeys++;
      const isChecked = existingKeys.some(b => b.provider === p && b.key === k);
      keysCheckboxesHtml += \`
        <label class="checkbox" style="font-size:13px;cursor:pointer;margin:0;">
          <input type="checkbox" data-provider="\${p}" data-key="\${k}" \${isChecked ? 'checked' : ''}>
          <span><span class="key-chip" style="font-weight:600;">\${k}</span></span>
        </label>
      \`;
    });

    groupDiv.innerHTML = \`
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:6px;border-bottom:1px solid var(--color-border);padding-bottom:4px;">
        <span style="font-weight:700;font-size:13px;color:var(--color-text-primary);">\${p}</span>
        <button type="button" class="btn btn-ghost btn-sm" style="font-size:11px;padding:0 6px;height:20px;" onclick="toggleProviderKeys('\${p}')">选择该厂商</button>
      </div>
      <div style="display:flex;flex-wrap:wrap;gap:12px;">
        \${keysCheckboxesHtml}
      </div>
    \`;
    container.appendChild(groupDiv);
  }

  if (totalKeys === 0) {
    container.innerHTML = '<div class="text-secondary" style="font-size:12px;padding:8px;">暂无匹配的 Key，请先添加供应商与 Key</div>';
  }
}

async function saveAgentModal() {
  const oldName = (document.getElementById('m_model_old_name').value || '').trim();
  const name = document.getElementById('m_model_name').value.trim();
  const upstream = document.getElementById('m_upstream_model').value.trim();
  if (!name) { toast('请输入模型名称', 'err'); return; }

  const checkedBoxes = document.querySelectorAll('#m_bindings_container input[type="checkbox"]:checked');
  const keys = Array.from(checkedBoxes).map(cb => ({
    provider: cb.dataset.provider,
    key: cb.dataset.key,
  }));

  if (keys.length === 0) {
    toast('请至少勾选一个候选 Key 绑定', 'err');
    return;
  }

  const backupCfg = JSON.parse(JSON.stringify(cfg));

  cfg.agent_models = cfg.agent_models || {};
  if (oldName && oldName !== name) {
    delete cfg.agent_models[oldName];
  }
  cfg.agent_models[name] = { keys };
  if (upstream && upstream !== name) cfg.agent_models[name].upstream_model = upstream;

  const ok = await persistConfig();
  if (ok) {
    closeModal('agentModal');
  } else {
    cfg = backupCfg;
    renderAll();
  }
}

async function removeModelKeyBinding(modelName, index) {
  if (cfg.agent_models?.[modelName]?.keys) {
    cfg.agent_models[modelName].keys.splice(index, 1);
    await persistConfig();
  }
}

async function moveModelKeyBinding(modelName, index, dir) {
  if (!cfg.agent_models || !cfg.agent_models[modelName]) return;
  const list = cfg.agent_models[modelName].keys || [];
  const target = index + dir;
  if (target < 0 || target >= list.length) return;
  const [item] = list.splice(index, 1);
  list.splice(target, 0, item);
  cfg.agent_models[modelName].keys = list;
  renderAgentModels();
  await persistConfig();
  toast('已调整 Key 优先级', 'ok');
}

async function testAllKeysForModel(modelName) {
  const item = cfg.agent_models?.[modelName];
  if (!item || !item.keys || !item.keys.length) return;
  toast(\`正在并发探活 \${modelName} 的 \${item.keys.length} 个 Key...\`, 'info');
  await Promise.all(item.keys.map(b => testModelKey(modelName, b.provider, b.key)));
  toast(\`\${modelName} 探活完成\`, 'ok');
}

async function deleteModel(name) {
  if (!confirm(\`删除模型「\${name}」？\`)) return;
  delete cfg.agent_models[name];
  await persistConfig();
}

async function setActiveAgentKey(modelName, keyLabel) {
  if (!cfg.agent_models || !cfg.agent_models[modelName]) return;
  cfg.agent_models[modelName].active_key = keyLabel;
  renderAgentModels();
  await persistConfig();
  toast(\`已将模型 \${modelName} 切换至 Key: [\${keyLabel}]\`, 'ok');
}


// ---- Config Export & Import (JSON / Blob) --------------------------------
function exportConfigJson() {
  try {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const filename = \`ocrproxy_edgeone_config_\${timestamp}.json\`;
    const jsonStr = JSON.stringify(cfg, null, 2);

    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast(\`配置已导出: \${filename}\`, 'ok');
  } catch (e) {
    toast('导出失败: ' + (e?.message || e), 'err');
  }
}

function triggerImportConfig() {
  const fileInput = document.getElementById('configFileImportInput');
  if (fileInput) {
    fileInput.value = '';
    fileInput.click();
  }
}

function handleConfigFileImport(event) {
  const file = event.target.files?.[0];
  if (!file) return;

  const reader = new FileReader();
  reader.onload = async (e) => {
    try {
      const content = e.target.result;
      const parsed = JSON.parse(content);

      if (!parsed || typeof parsed !== 'object') {
        throw new Error('导入文件不是有效的 JSON 对象');
      }

      if (!parsed.providers && !parsed.agent_models) {
        throw new Error('未检测到 providers 或 agent_models 配置节点');
      }

      const countProv = Object.keys(parsed.providers || {}).length;
      const countModels = Object.keys(parsed.agent_models || {}).length;

      if (!confirm(\`导入配置包含 \${countProv} 个供应商与 \${countModels} 个模型，覆盖当前 KV 配置？\`)) {
        return;
      }

      cfg = parsed;
      await persistConfig();
      toast('配置已导入', 'ok');
    } catch (err) {
      toast('导入失败: ' + err.message, 'err');
    }
  };
  reader.readAsText(file);
}

// ---- Raw JSON ------------------------------------------------------------
function formatRawJson() {
  const ta = document.getElementById('rawJsonText');
  try {
    const parsed = JSON.parse(ta.value);
    ta.value = JSON.stringify(parsed, null, 2);
    document.getElementById('rawJsonErr').style.display = 'none';
  } catch (e) {
    const errEl = document.getElementById('rawJsonErr');
    errEl.textContent = 'JSON 格式错误: ' + e.message;
    errEl.style.display = 'block';
  }
}

async function saveRawJson() {
  const ta = document.getElementById('rawJsonText');
  const errEl = document.getElementById('rawJsonErr');
  try {
    const parsed = JSON.parse(ta.value);
    errEl.style.display = 'none';
    cfg = parsed;
    await persistConfig();
  } catch (e) {
    errEl.textContent = 'JSON 格式解析失败: ' + e.message;
    errEl.style.display = 'block';
  }
}

async function persistConfig() {
  try {
    const res = await api('POST', '/api/config', cfg);
    cfgMeta = res;
    if (res?.config) {
      cfg = res.config;
    }
    renderAll();
    toast('配置已保存', 'ok');
    return true;
  } catch (e) {
    toast('保存失败: ' + (e?.message || e), 'err');
    return false;
  }
}

// ---- Init ----------------------------------------------------------------
window.addEventListener('DOMContentLoaded', () => {
  if (getKey()) {
    doLogin();
  } else {
    showLoginOverlay();
  }
});

</script>
</body>
</html>
`;
}

export function onRequestGet(context) {
  return new Response(pageHtml(), {
    status: 200,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "x-content-type-options": "nosniff",
      "x-frame-options": "DENY",
      "x-xss-protection": "1; mode=block",
      "referrer-policy": "strict-origin-when-cross-origin"
    },
  });
}

export function onRequestHead(context) {
  return onRequestGet(context);
}
