#!/usr/bin/env node
/**
 * build-admin.mjs — bundle admin.{html,css,js} into a single self-contained
 * edge function (edge-functions/admin.js) that returns the full HTML.
 *
 * Why: EdgeOne Makers projects don't auto-serve `public/` as static files.
 * The cleanest workaround is one edge function that returns the entire
 * admin page (CSS inlined as <style>, JS inlined as <script>).  This is
 * what static-site generators effectively do, just in reverse.
 *
 * Usage:  node scripts/build-admin.mjs
 *   Reads:   admin.html, admin.css, admin.js  (in repo root)
 *   Writes:  edge-functions/admin.js          (the bundled function)
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const htmlPath = join(root, 'admin.html');
const cssPath = join(root, 'admin.css');
const jsPath = join(root, 'admin.js');
const outPath = join(root, 'edge-functions', 'admin.js');

for (const p of [htmlPath, cssPath, jsPath]) {
  if (!existsSync(p)) {
    console.error(`Missing input: ${p}`);
    process.exit(1);
  }
}

const html = readFileSync(htmlPath, 'utf8');
const css = readFileSync(cssPath, 'utf8');
const js = readFileSync(jsPath, 'utf8');

// 1. Inline CSS: replace the <link rel="stylesheet" href="/admin.css"> with a <style>.
const htmlInlined = html.replace(
  /<link\s+rel="stylesheet"\s+href="\/admin\.css"\s*\/?>/,
  () => `<style>\n${css}\n</style>`
);
if (!htmlInlined.includes('<style>')) {
  console.error('admin.html did not contain the expected <link rel="stylesheet" href="/admin.css">; aborting.');
  process.exit(1);
}

// 2. Inline JS: replace the <script src="/admin.js"></script> with a <script>.
const htmlBundled = htmlInlined.replace(
  /<script\s+src="\/admin\.js"\s*><\/script>/,
  () => `<script>\n${js}\n</script>`
);
if (!htmlBundled.includes('<script>')) {
  console.error('admin.html did not contain the expected <script src="/admin.js"></script>; aborting.');
  process.exit(1);
}

// 3. Emit the edge function.  We escape the HTML for embedding inside a
//    JS template literal — but since the HTML doesn't contain ${ or `
//    we can keep it simple.  We do one defensive replace to escape any
//    accidental ${ occurrences in user-supplied content.
const safe = htmlBundled.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const banner =
  '/**\n' +
  ' * admin.js — Self-contained admin UI for EdgeOne Agent Relay.\n' +
  ' *\n' +
  ' *   Generated by scripts/build-admin.mjs from admin.{html,css,js}\n' +
  ' *   in the repo root.  Do not edit this file directly — edit the\n' +
  ' *   sources and re-run the build.\n' +
  ' *\n' +
  ' *   GET /admin     → returns the full admin HTML (CSS + JS inlined)\n' +
  ' *   GET /admin/    → same\n' +
  ' *   GET /admin.html → 301 to /admin (for old bookmarks)\n' +
  ' */\n\n';

const body =
  'function pageHtml() {\n' +
  '  return `' + safe + '`;\n' +
  '}\n\n' +
  'export function onRequestGet(context) {\n' +
  '  const path = new URL(context.request.url).pathname;\n' +
  '  if (path === "/admin.html" || path === "/admin/index.html") {\n' +
  '    return new Response(null, {\n' +
  '      status: 301,\n' +
  '      headers: { location: "/admin" },\n' +
  '    });\n' +
  '  }\n' +
  '  return new Response(pageHtml(), {\n' +
  '    status: 200,\n' +
  '    headers: {\n' +
  '      "content-type": "text/html; charset=utf-8",\n' +
  '      "cache-control": "no-store",\n' +
  '    },\n' +
  '  });\n' +
  '}\n';

writeFileSync(outPath, banner + body, 'utf8');
console.log(`Built ${outPath}  (${htmlBundled.length} bytes of HTML inlined)`);
