#!/usr/bin/env node
/**
 * build-admin.mjs — bundle modular admin.{html,css,js} into self-contained
 * edge functions and sync static assets:
 *   - edge-functions/index.js (serves GET / directly as admin dashboard)
 *   - edge-functions/admin.js (serves GET /admin or 301 redirects)
 *
 * Usage:  node scripts/build-admin.mjs
 *   Reads:   admin.html, admin.css, js/*.js (in agent-edgeone/ or shared/admin/)
 *   Writes:  admin.js, edge-functions/index.js, edge-functions/admin.js
 */
import { readFileSync, writeFileSync, existsSync, cpSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const sharedRoot = join(root, '..', 'shared', 'admin');

// 1. Sync shared/admin to vm-app/static ONLY (NEVER overwrite agent-edgeone!)
if (existsSync(sharedRoot)) {
  const sharedHtml = join(sharedRoot, 'admin.html');
  const sharedCss = join(sharedRoot, 'admin.css');
  const sharedJsDir = join(sharedRoot, 'js');

  const vmStatic = join(root, '..', 'vm-app', 'static');
  if (existsSync(vmStatic)) {
    if (existsSync(sharedHtml)) cpSync(sharedHtml, join(vmStatic, 'admin.html'));
    if (existsSync(sharedCss)) cpSync(sharedCss, join(vmStatic, 'admin.css'));
    if (existsSync(sharedJsDir)) cpSync(sharedJsDir, join(vmStatic, 'js'), { recursive: true });
    console.log(`Synced shared/admin to vm-app/static: ${vmStatic}`);
  }
}

const htmlPath = join(root, 'admin.html');
const cssPath = join(root, 'admin.css');
const jsPath = join(root, 'admin.js');

const indexPath = join(root, 'edge-functions', 'index.js');
const adminPath = join(root, 'edge-functions', 'admin.js');

if (!existsSync(htmlPath) || !existsSync(cssPath)) {
  console.error(`Missing input: ${htmlPath} or ${cssPath}`);
  process.exit(1);
}

const html = readFileSync(htmlPath, 'utf8');
const css = readFileSync(cssPath, 'utf8');

// 2. Read EdgeOne standalone JS
if (!existsSync(jsPath)) {
  console.error(`Missing input: ${jsPath}`);
  process.exit(1);
}
const bundledJs = readFileSync(jsPath, 'utf8');

// 3. Inline CSS: replace <link ...admin.css...> with <style>
const cssLinkRegex = /<link\b[^>]*href=["'][^"']*admin\.css[^"']*["'][^>]*\/?>/i;
if (!cssLinkRegex.test(html)) {
  console.error('FATAL BUILD ERROR: Could not find admin.css link tag in HTML!');
  process.exit(1);
}
const htmlInlinedCss = html.replace(cssLinkRegex, () => `<style>\n${css}\n</style>`);

// 4. Inline JS: replace modular <script src="/static/js/..."></script> or single <script src="...admin.js"> with single <script>
let htmlBundled = htmlInlinedCss;
const modularScriptRegex = /(?:<!--\s*Modular Scripts[^\n]*-->\s*)?(?:<script\b[^>]*src=["'][^"']*\/js\/[^"']+["'][^>]*>(?:\s*<\/script>)?\s*)+/i;
const singleScriptRegex = /<script\b[^>]*src=["'][^"']*admin\.js[^"']*["'][^>]*>(?:\s*<\/script>)?/i;

if (modularScriptRegex.test(htmlBundled)) {
  htmlBundled = htmlBundled.replace(modularScriptRegex, () => `<script>\n${bundledJs}\n</script>`);
} else if (singleScriptRegex.test(htmlBundled)) {
  htmlBundled = htmlBundled.replace(singleScriptRegex, () => `<script>\n${bundledJs}\n</script>`);
} else {
  // Fallback: append before </body>
  htmlBundled = htmlBundled.replace('</body>', `<script>\n${bundledJs}\n</script>\n</body>`);
}

// === 防线 2: 编译严格强断言 (Fail-Fast Gatekeeper) ===
if (!htmlBundled.includes('<style>') || !htmlBundled.includes(css.slice(0, 40))) {
  console.error('FATAL BUILD ERROR: CSS was not properly inlined into bundled HTML!');
  process.exit(1);
}
if (/<link\b[^>]*admin\.css/i.test(htmlBundled)) {
  console.error('FATAL BUILD ERROR: Residual <link rel="stylesheet"> detected in bundled HTML!');
  process.exit(1);
}
if (/<script\b[^>]*src=["'][^"']*(?:admin\.js|\/js\/)/i.test(htmlBundled)) {
  console.error('FATAL BUILD ERROR: Residual external <script src> detected in bundled HTML!');
  process.exit(1);
}

// 5. Emit edge functions
const safe = htmlBundled.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const banner =
  '/**\n' +
  ' * Self-contained admin UI for OCRProxy EdgeOne.\n' +
  ' *\n' +
  ' *   Generated by scripts/build-admin.mjs from modular admin sources\n' +
  ' *   Do not edit this file directly.\n' +
  ' */\n\n';

const functionCode =
  banner +
  'function pageHtml() {\n' +
  '  return `' + safe + '`;\n' +
  '}\n\n' +
  'export function onRequestGet(context) {\n' +
  '  return new Response(pageHtml(), {\n' +
  '    status: 200,\n' +
  '    headers: {\n' +
  '      "content-type": "text/html; charset=utf-8",\n' +
  '      "cache-control": "no-store",\n' +
  '      "x-content-type-options": "nosniff",\n' +
  '      "x-frame-options": "DENY",\n' +
  '      "x-xss-protection": "1; mode=block",\n' +
  '      "referrer-policy": "strict-origin-when-cross-origin"\n' +
  '    },\n' +
  '  });\n' +
  '}\n\n' +
  'export function onRequestHead(context) {\n' +
  '  return onRequestGet(context);\n' +
  '}\n';

const rootProject = join(root, '..');
const rootIndexPath = join(rootProject, 'edge-functions', 'index.js');
const rootAdminPath = join(rootProject, 'edge-functions', 'admin.js');

writeFileSync(indexPath, functionCode, 'utf8');
writeFileSync(adminPath, functionCode, 'utf8');
console.log(`Built ${indexPath} and ${adminPath} (${htmlBundled.length} bytes of HTML bundled)`);

if (existsSync(join(rootProject, 'edge-functions'))) {
  writeFileSync(rootIndexPath, functionCode, 'utf8');
  writeFileSync(rootAdminPath, functionCode, 'utf8');
  cpSync(join(root, 'edge-functions'), join(rootProject, 'edge-functions'), { recursive: true });
  console.log(`Synced all edge-functions to root: ${join(rootProject, 'edge-functions')}`);
}
