import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { createHash } from 'node:crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const sharedPresetsDir = join(__dirname, '../../shared/presets');

// Dynamically discover all json files except catalog.json
const presetFiles = readdirSync(sharedPresetsDir)
  .filter((f) => f.endsWith('.json') && f !== 'catalog.json')
  .sort();

const presets = presetFiles.map((file) => {
  const fullPath = join(sharedPresetsDir, file);
  return JSON.parse(readFileSync(fullPath, 'utf8'));
});

// Build catalog
const catalog = {
  version: '1.1.0',
  updated_at: new Date().toISOString(),
  providers: presets.map((p) => {
    const rulesStr = JSON.stringify(p.adapter_rules || {});
    const ruleHash = createHash('sha256').update(rulesStr).digest('hex').slice(0, 12);
    return {
      id: p.id,
      name: p.name,
      version: p.version || '1.0.0',
      rule_hash: ruleHash,
      protocol: p.protocol || 'openai',
      base_url: p.base_url || '',
      anthropic_base_url: p.anthropic_base_url || null,
      doc_url: p.doc_url || null,
      description: p.description || '',
      features: p.features || {},
      recommended_models_count: (p.recommended_models || []).length,
    };
  }),
};

// Write catalog.json to shared/presets/
const catalogPath = join(sharedPresetsDir, 'catalog.json');
writeFileSync(catalogPath, JSON.stringify(catalog, null, 2), 'utf8');
console.log(`Generated catalog at: ${catalogPath}`);

const content = `/**
 * presets/index.js — Pure JS Registry of Provider Presets (zero JSON import attribute dependency).
 * Auto-generated by scripts/build-presets.mjs from shared/presets/*.json
 */

export const CATALOG = ${JSON.stringify(catalog, null, 2)};

export const PRESETS = ${JSON.stringify(presets, null, 2)};

export const PRESET_MAP = Object.fromEntries(PRESETS.map((p) => [p.id, p]));

export function getPreset(id) {
  return PRESET_MAP[String(id).toLowerCase()] || null;
}
`;

const dest1 = join(__dirname, '../edge-functions/lib/presets/index.js');
const dest2 = join(__dirname, '../../edge-functions/lib/presets/index.js');

writeFileSync(dest1, content, 'utf8');
writeFileSync(dest2, content, 'utf8');
console.log(`Generated pure JS presets at: ${dest1} and ${dest2}`);
