#!/usr/bin/env node
/**
 * build-admin.mjs — bundle admin.{html,css,js} into self-contained
 * edge functions:
 *   - edge-functions/index.js (serves GET / directly as admin dashboard)
 *   - edge-functions/admin.js (serves GET /admin or 301 redirects)
 *
 * Usage:  node scripts/build-admin.mjs
 *   Reads:   admin.html, admin.css, admin.js  (in edgeone/)
 *   Writes:  edge-functions/index.js, edge-functions/admin.js
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const sharedAdminDir = join(root, '..', 'shared', 'admin');
const htmlPath = existsSync(join(sharedAdminDir, 'admin.html')) ? join(sharedAdminDir, 'admin.html') : join(root, 'admin.html');
const cssPath = existsSync(join(sharedAdminDir, 'admin.css')) ? join(sharedAdminDir, 'admin.css') : join(root, 'admin.css');
const jsPath = existsSync(join(sharedAdminDir, 'admin.js')) ? join(sharedAdminDir, 'admin.js') : join(root, 'admin.js');

const indexPath = join(root, 'edge-functions', 'index.js');
const adminPath = join(root, 'edge-functions', 'admin.js');

for (const p of [htmlPath, cssPath, jsPath]) {
  if (!existsSync(p)) {
    console.error(`Missing input: ${p}`);
    process.exit(1);
  }
}

const html = readFileSync(htmlPath, 'utf8');
const css = readFileSync(cssPath, 'utf8');
const js = readFileSync(jsPath, 'utf8');

// 1. Inline CSS: replace the <link rel="stylesheet" href="/admin.css"> with a <style>.
const htmlInlined = html.replace(
  /<link\s+rel="stylesheet"\s+href="\/admin\.css"\s*\/?>/,
  () => `<style>\n${css}\n</style>`
);
if (!htmlInlined.includes('<style>')) {
  console.error('admin.html did not contain the expected <link rel="stylesheet" href="/admin.css">; aborting.');
  process.exit(1);
}

// 2. Inline JS: replace the <script src="/admin.js"></script> with a <script>.
const htmlBundled = htmlInlined.replace(
  /<script\s+src="\/admin\.js"\s*><\/script>/,
  () => `<script>\n${js}\n</script>`
);
if (!htmlBundled.includes('<script>')) {
  console.error('admin.html did not contain the expected <script src="/admin.js"></script>; aborting.');
  process.exit(1);
}

// 3. Emit the edge function.
const safe = htmlBundled.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const banner =
  '/**\n' +
  ' * Self-contained admin UI for OCRProxy EdgeOne.\n' +
  ' *\n' +
  ' *   Generated by scripts/build-admin.mjs from admin.{html,css,js}\n' +
  ' *   Do not edit this file directly.\n' +
  ' */\n\n';

const functionCode =
  banner +
  'function pageHtml() {\n' +
  '  return `' + safe + '`;\n' +
  '}\n\n' +
  'export function onRequestGet(context) {\n' +
  '  return new Response(pageHtml(), {\n' +
  '    status: 200,\n' +
  '    headers: {\n' +
  '      "content-type": "text/html; charset=utf-8",\n' +
  '      "cache-control": "no-store",\n' +
  '      "x-content-type-options": "nosniff",\n' +
  '      "x-frame-options": "DENY",\n' +
  '      "x-xss-protection": "1; mode=block",\n' +
  '      "referrer-policy": "strict-origin-when-cross-origin"\n' +
  '    },\n' +
  '  });\n' +
  '}\n\n' +
  'export function onRequestHead(context) {\n' +
  '  return onRequestGet(context);\n' +
  '}\n';

const rootProject = join(root, '..');
const rootIndexPath = join(rootProject, 'edge-functions', 'index.js');
const rootAdminPath = join(rootProject, 'edge-functions', 'admin.js');

writeFileSync(indexPath, functionCode, 'utf8');
writeFileSync(adminPath, functionCode, 'utf8');
console.log(`Built ${indexPath} and ${adminPath} (${htmlBundled.length} bytes of HTML inlined)`);

if (existsSync(join(rootProject, 'edge-functions'))) {
  writeFileSync(rootIndexPath, functionCode, 'utf8');
  writeFileSync(rootAdminPath, functionCode, 'utf8');
  console.log(`Synced to root: ${rootIndexPath} and ${rootAdminPath}`);
}

