import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const sharedPresetsDir = join(__dirname, '../../shared/presets');

const presetIds = [
  'google',
  'sensenova',
  'stepfun',
  'siliconflow',
  'tokenrhythm',
  'deepseek',
  'openai',
  'agnes',
  'minimax',
  'bai',
  'amd',
];

const presets = presetIds.map((id) => {
  const file = join(sharedPresetsDir, `${id}.json`);
  return JSON.parse(readFileSync(file, 'utf8'));
});

const content = `/**
 * presets/index.js — Pure JS Registry of Provider Presets (zero JSON import attribute dependency).
 * Auto-generated by scripts/build-presets.mjs from shared/presets/*.json
 */

export const PRESETS = ${JSON.stringify(presets, null, 2)};

export const PRESET_MAP = Object.fromEntries(PRESETS.map((p) => [p.id, p]));

export function getPreset(id) {
  return PRESET_MAP[String(id).toLowerCase()] || null;
}
`;

const dest1 = join(__dirname, '../edge-functions/lib/presets/index.js');
const dest2 = join(__dirname, '../../edge-functions/lib/presets/index.js');

writeFileSync(dest1, content, 'utf8');
writeFileSync(dest2, content, 'utf8');
console.log(`Generated pure JS presets at: ${dest1} and ${dest2}`);
