/**
 * presets/index.js — Pure JS Registry of Provider Presets (zero JSON import attribute dependency).
 * Auto-generated by scripts/build-presets.mjs from shared/presets/*.json
 */

export const CATALOG = {
  "version": "1.1.0",
  "updated_at": "2026-09-19T06:48:21.996Z",
  "providers": [
    {
      "id": "agnes",
      "name": "Agnes AI (爱格尼斯)",
      "version": "1.2.0",
      "rule_hash": "aaa5a822991a",
      "protocol": "openai",
      "base_url": "https://apihub.agnes-ai.com/v1",
      "anthropic_base_url": null,
      "doc_url": "https://www.agnes-ai.com/en/docs/agnes-30-flash",
      "description": "Agnes AI 平台，支持 agnes-3.0-flash 等高并发轻量 Agent 模型，支持 chat_template_kwargs 思考扩展与 512k 上下文",
      "features": {
        "native_thinking": false,
        "chat_template_kwargs_thinking": true,
        "tools": true,
        "multimodal": true
      },
      "recommended_models_count": 3
    },
    {
      "id": "amd",
      "name": "AMD Radeon Cloud",
      "version": "1.1.0",
      "rule_hash": "d490d1ecb1e5",
      "protocol": "openai",
      "base_url": "https://developer.amd.com.cn/radeon/api/v1",
      "anthropic_base_url": "https://developer.amd.com.cn/radeon/api/v1",
      "doc_url": "https://amd-aim.github.io/radeon-cloud-docs/",
      "description": "AMD 官方开发者平台，基于高性能推理集群。网关已自动适配 reasoning_effort 深度思考、Anthropic output_config 与 system 消息置顶规整。",
      "features": {
        "native_thinking": true,
        "multimodal": false,
        "tools": true,
        "anthropic_messages": true
      },
      "recommended_models_count": 2
    },
    {
      "id": "bai",
      "name": "B.AI",
      "version": "1.3.0",
      "rule_hash": "fadedcc28148",
      "protocol": "openai",
      "base_url": "https://api.b.ai/v1",
      "anthropic_base_url": "https://api.b.ai/v1",
      "doc_url": "https://docs.b.ai/llmservice/api/#messages-api-anthropic-compatible",
      "description": "B.AI 统一大模型服务，原生兼容 OpenAI Chat Completions 与 Anthropic Messages 协议双通道。网关已专属适配 GLM 系列常开思考模型（自动将 medium 映射为 high，规避 400 校验异常）。",
      "features": {
        "native_thinking": true,
        "tools": true,
        "anthropic_messages": true
      },
      "recommended_models_count": 4
    },
    {
      "id": "deepseek",
      "name": "DeepSeek 官方开放平台",
      "version": "1.1.0",
      "rule_hash": "193068f4df5b",
      "protocol": "openai",
      "base_url": "https://api.deepseek.com/v1",
      "anthropic_base_url": null,
      "doc_url": "https://api-docs.deepseek.com",
      "description": "DeepSeek 官方 API，原生支持 reasoning_content 深度思考与前缀缓存",
      "features": {
        "native_thinking": true,
        "tools": true
      },
      "recommended_models_count": 2
    },
    {
      "id": "google",
      "name": "Google AI Studio (Gemini)",
      "version": "1.1.0",
      "rule_hash": "19fbf45af855",
      "protocol": "google_openai",
      "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
      "anthropic_base_url": null,
      "doc_url": null,
      "description": "Google 官方 Gemini 系列大模型，支持 Gemini 2.5 / 3 / 3.5+，内置 Thinking Matrix、深度 Schema 裁剪与思考预算自动提升",
      "features": {
        "native_thinking": true,
        "multimodal": true,
        "tools": true
      },
      "recommended_models_count": 4
    },
    {
      "id": "minimax",
      "name": "MiniMax",
      "version": "1.1.0",
      "rule_hash": "15e333efeb77",
      "protocol": "openai",
      "base_url": "https://api.minimaxi.com/v1",
      "anthropic_base_url": "https://api.minimaxi.com/anthropic",
      "doc_url": "https://platform.minimaxi.com/docs/api-reference/text-chat-anthropic",
      "description": "MiniMax 开放平台（国内官方订阅），支持 MiniMax-M3 系列，原生支持 OpenAI Completions 与 Anthropic Messages 双协议直通",
      "features": {
        "native_thinking": true,
        "multimodal": true,
        "tools": true,
        "anthropic_messages": true
      },
      "recommended_models_count": 1
    },
    {
      "id": "openai",
      "name": "OpenAI 官方 / 标准兼容中转",
      "version": "1.1.0",
      "rule_hash": "3ddc251503f8",
      "protocol": "openai",
      "base_url": "https://api.openai.com/v1",
      "anthropic_base_url": null,
      "doc_url": "https://platform.openai.com/docs",
      "description": "OpenAI 官方 API 或标准兼容中转网关，原生支持 reasoning_effort 思考控制与多模态",
      "features": {
        "native_thinking": true,
        "tools": true,
        "multimodal": true
      },
      "recommended_models_count": 4
    },
    {
      "id": "sensenova",
      "name": "商汤日日新 (SenseNova)",
      "version": "1.1.0",
      "rule_hash": "193068f4df5b",
      "protocol": "openai",
      "base_url": "https://token.sensenova.cn/v1",
      "anthropic_base_url": null,
      "doc_url": "https://platform.sensenova.cn/docs",
      "description": "商汤日日新大模型开放平台，支持 sensenova-6.8-flash-lite、deepseek-v4-flash、glm-5.2 等旗舰与轻量模型",
      "features": {
        "native_thinking": true,
        "multimodal": true,
        "tools": true
      },
      "recommended_models_count": 3
    },
    {
      "id": "siliconflow",
      "name": "硅基流动 (SiliconFlow)",
      "version": "1.1.0",
      "rule_hash": "193068f4df5b",
      "protocol": "openai",
      "base_url": "https://api.siliconflow.cn/v1",
      "anthropic_base_url": null,
      "doc_url": "https://docs.siliconflow.cn",
      "description": "硅基流动高并发推理平台，包含 DeepSeek-V3/R1、Qwen2.5 等海量开源模型",
      "features": {
        "native_thinking": true,
        "tools": true
      },
      "recommended_models_count": 3
    },
    {
      "id": "stepfun",
      "name": "阶跃星辰 (StepFun)",
      "version": "1.1.0",
      "rule_hash": "f7de5125e5e5",
      "protocol": "openai",
      "base_url": "https://api.stepfun.com/step_plan",
      "anthropic_base_url": null,
      "doc_url": "https://platform.stepfun.com/docs/zh/api-reference/chat/chat-completion-create",
      "description": "阶跃星辰大模型平台，支持 step-3.7-flash 等，已自动适配 reasoning_effort none->low 降级与 deepseek-style 思考格式注入",
      "features": {
        "native_thinking": true,
        "multimodal": true,
        "tools": true
      },
      "recommended_models_count": 2
    },
    {
      "id": "tokenrhythm",
      "name": "TokenRhythm",
      "version": "1.1.0",
      "rule_hash": "193068f4df5b",
      "protocol": "openai",
      "base_url": "https://tokenrhythm.studio/v1",
      "anthropic_base_url": null,
      "doc_url": "https://tokenrhythm.studio/docs/api-integration",
      "description": "TokenRhythm 聚合大模型路由网关，支持 deepseek-v4-flash, Claude, GPT 系列，自动适配 tool_choice 字符串转换与思考流提取",
      "features": {
        "native_thinking": true,
        "tools": true
      },
      "recommended_models_count": 3
    }
  ]
};

export const PRESETS = [
  {
    "id": "agnes",
    "name": "Agnes AI (爱格尼斯)",
    "version": "1.2.0",
    "protocol": "openai",
    "base_url": "https://apihub.agnes-ai.com/v1",
    "doc_url": "https://www.agnes-ai.com/en/docs/agnes-30-flash",
    "description": "Agnes AI 平台，支持 agnes-3.0-flash 等高并发轻量 Agent 模型，支持 chat_template_kwargs 思考扩展与 512k 上下文",
    "features": {
      "native_thinking": false,
      "chat_template_kwargs_thinking": true,
      "tools": true,
      "multimodal": true
    },
    "recommended_models": [
      {
        "name": "agnes-3.0-flash",
        "upstream_model": "agnes-3.0-flash",
        "description": "Agnes 3.0 Flash 全新一代旗舰开源推理模型 (512K 上下文)"
      },
      {
        "name": "agnes-2.5-flash",
        "upstream_model": "agnes-2.5-flash",
        "description": "Agnes 2.5 Flash 旗舰高速模型 (512K 上下文)"
      },
      {
        "name": "agnes-2.0-flash",
        "upstream_model": "agnes-2.0-flash",
        "description": "Agnes 2.0 Flash 兼容回退模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "chat_template_kwargs",
        "enable_key": "enable_thinking",
        "default_thinking": true
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": false,
        "rescue_from_text": true
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": [],
        "max_tokens_ceiling": 65536
      }
    }
  },
  {
    "id": "amd",
    "name": "AMD Radeon Cloud",
    "version": "1.1.0",
    "protocol": "openai",
    "base_url": "https://developer.amd.com.cn/radeon/api/v1",
    "anthropic_base_url": "https://developer.amd.com.cn/radeon/api/v1",
    "doc_url": "https://amd-aim.github.io/radeon-cloud-docs/",
    "description": "AMD 官方开发者平台，基于高性能推理集群。网关已自动适配 reasoning_effort 深度思考、Anthropic output_config 与 system 消息置顶规整。",
    "features": {
      "native_thinking": true,
      "multimodal": false,
      "tools": true,
      "anthropic_messages": true
    },
    "recommended_models": [
      {
        "name": "deepseek-v4-flash",
        "upstream_model": "DeepSeek-V4-Flash",
        "description": "DeepSeek V4 Flash 百万原生上下文智能体大模型 (网关已自动注入 reasoning_effort 开启深度思考)"
      },
      {
        "name": "qwen3.8-flash-next",
        "upstream_model": "Qwen3.8-Flash-Next",
        "description": "千问全新 QSA 稀疏注意力大模型 (26.2万上下文，网关已自动适配 system 消息置顶与安全思考级别)"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "effort_remapping",
        "default_effort": "medium",
        "supported_levels": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ],
        "model_rules": {
          "qwen": {
            "supported_levels": [
              "low",
              "medium"
            ],
            "level_fallback": {
              "high": "medium",
              "xhigh": "medium",
              "max": "medium"
            },
            "none_fallback": "low"
          }
        },
        "none_action": "omit",
        "strip_thinking": true
      },
      "messages": {
        "deny_developer_role": true,
        "system_first_only": true,
        "merge_system": true,
        "strip_empty": true
      },
      "anthropic": {
        "thinking_to_output_config": true,
        "default_effort": "medium",
        "strip_thinking": true,
        "model_rules": {
          "qwen": {
            "level_fallback": {
              "high": "medium",
              "xhigh": "medium",
              "max": "medium"
            }
          }
        }
      },
      "sanitization": {
        "strip_params": [
          "thinking",
          "chat_template_kwargs"
        ]
      },
      "response": {
        "reasoning_fields": [
          "reasoning",
          "reasoning_content"
        ],
        "reasoning_tokens_paths": [
          "completion_tokens_details.reasoning_tokens",
          "usage.reasoning_tokens"
        ]
      }
    }
  },
  {
    "id": "bai",
    "name": "B.AI",
    "version": "1.3.0",
    "protocol": "openai",
    "base_url": "https://api.b.ai/v1",
    "anthropic_base_url": "https://api.b.ai/v1",
    "doc_url": "https://docs.b.ai/llmservice/api/#messages-api-anthropic-compatible",
    "description": "B.AI 统一大模型服务，原生兼容 OpenAI Chat Completions 与 Anthropic Messages 协议双通道。网关已专属适配 GLM 系列常开思考模型（自动将 medium 映射为 high，规避 400 校验异常）。",
    "features": {
      "native_thinking": true,
      "tools": true,
      "anthropic_messages": true
    },
    "recommended_models": [
      {
        "name": "glm-5.3-flash",
        "upstream_model": "glm-5.3-flash",
        "description": "智谱 GLM 5.3 Flash 原生常开深度思考模型 (网关已自动适配 Hermes / OpenAI 思考档位)"
      },
      {
        "name": "qwen3.8-flash",
        "upstream_model": "qwen3.8-flash",
        "description": "千问 3.8 Flash 模型 (原生思考支持)"
      },
      {
        "name": "claude-3-5-sonnet",
        "upstream_model": "claude-3-5-sonnet",
        "description": "Claude 3.5 Sonnet 模型（B.AI 兼容端点）"
      },
      {
        "name": "deepseek-v3",
        "upstream_model": "deepseek-v3",
        "description": "DeepSeek V3 模型（B.AI 兼容端点）"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "effort_remapping",
        "supported_levels": [
          "none",
          "minimal",
          "low",
          "medium",
          "high",
          "max"
        ],
        "model_rules": {
          "glm": {
            "supported_levels": [
              "low",
              "high",
              "max"
            ],
            "level_fallback": {
              "medium": "high",
              "minimal": "low",
              "none": "low"
            },
            "none_action": "omit",
            "default_effort": "high"
          }
        }
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": false,
        "rescue_from_text": true
      },
      "sanitization": {
        "unsupported_params": []
      },
      "error_rules": [
        {
          "name": "credit_insufficient_balance",
          "match_status": 400,
          "match_keywords": [
            "credit",
            "balance",
            "insufficient",
            "欠费",
            "余额不足"
          ],
          "action": "quota_exhausted",
          "cooldown_sec": 1800,
          "failover": true
        }
      ],
      "timeout_rules": {
        "default_timeout_sec": 60,
        "models": {
          "glm-5.3-flash": 120,
          "glm-5.3": 120
        }
      }
    }
  },
  {
    "id": "deepseek",
    "name": "DeepSeek 官方开放平台",
    "version": "1.1.0",
    "protocol": "openai",
    "base_url": "https://api.deepseek.com/v1",
    "doc_url": "https://api-docs.deepseek.com",
    "description": "DeepSeek 官方 API，原生支持 reasoning_content 深度思考与前缀缓存",
    "features": {
      "native_thinking": true,
      "tools": true
    },
    "recommended_models": [
      {
        "name": "deepseek-chat",
        "upstream_model": "deepseek-chat",
        "description": "DeepSeek-V3 快速对话大模型"
      },
      {
        "name": "deepseek-reasoner",
        "upstream_model": "deepseek-reasoner",
        "description": "DeepSeek-R1 深度思考推理大模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough",
        "supported_levels": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "tools": {
        "normalize_choice_to_string": true,
        "strip_json_schema": false,
        "rescue_from_text": true
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      }
    }
  },
  {
    "id": "google",
    "name": "Google AI Studio (Gemini)",
    "version": "1.1.0",
    "protocol": "google_openai",
    "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
    "description": "Google 官方 Gemini 系列大模型，支持 Gemini 2.5 / 3 / 3.5+，内置 Thinking Matrix、深度 Schema 裁剪与思考预算自动提升",
    "features": {
      "native_thinking": true,
      "multimodal": true,
      "tools": true
    },
    "recommended_models": [
      {
        "name": "gemini-3.5-flash",
        "upstream_model": "gemini-3.5-flash",
        "description": "最新高性价比推理模型 (支持 low/medium/high 思考等级)"
      },
      {
        "name": "gemini-3.5-pro",
        "upstream_model": "gemini-3.5-pro",
        "description": "最新旗舰强推理模型 (支持 low/high 思考等级)"
      },
      {
        "name": "gemini-2.5-flash",
        "upstream_model": "gemini-2.5-flash",
        "description": "经典多模态快速模型"
      },
      {
        "name": "gemini-2.5-pro",
        "upstream_model": "gemini-2.5-pro",
        "description": "经典多模态深度思考模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "gemini_thinking_matrix",
        "none_action": "include_thoughts_false",
        "headroom_elevation": true,
        "model_matrix": {
          "flash": [
            "minimal",
            "low",
            "medium",
            "high"
          ],
          "pro": [
            "low",
            "high"
          ]
        }
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": true,
        "deep_schema_sanitization": true,
        "rescue_from_text": true
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      }
    }
  },
  {
    "id": "minimax",
    "name": "MiniMax",
    "version": "1.1.0",
    "protocol": "openai",
    "base_url": "https://api.minimaxi.com/v1",
    "anthropic_base_url": "https://api.minimaxi.com/anthropic",
    "doc_url": "https://platform.minimaxi.com/docs/api-reference/text-chat-anthropic",
    "description": "MiniMax 开放平台（国内官方订阅），支持 MiniMax-M3 系列，原生支持 OpenAI Completions 与 Anthropic Messages 双协议直通",
    "features": {
      "native_thinking": true,
      "multimodal": true,
      "tools": true,
      "anthropic_messages": true
    },
    "recommended_models": [
      {
        "name": "MiniMax-M3",
        "upstream_model": "MiniMax-M3",
        "description": "MiniMax-M3 多模态通用旗舰模型（支持超长思考与图片理解，原生兼容 Messages）"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "minimax_adaptive",
        "default_type": "adaptive",
        "enable_reasoning_split": true
      },
      "anthropic": {
        "thinking_to_adaptive": true
      },
      "case_sensitive_models": {
        "minimax-m3": "MiniMax-M3"
      },
      "sanitization": {
        "strip_params": [
          "output_config"
        ]
      },
      "response": {
        "reasoning_fields": [
          "reasoning_split",
          "reasoning_content",
          "reasoning"
        ]
      }
    }
  },
  {
    "id": "openai",
    "name": "OpenAI 官方 / 标准兼容中转",
    "version": "1.1.0",
    "protocol": "openai",
    "base_url": "https://api.openai.com/v1",
    "doc_url": "https://platform.openai.com/docs",
    "description": "OpenAI 官方 API 或标准兼容中转网关，原生支持 reasoning_effort 思考控制与多模态",
    "features": {
      "native_thinking": true,
      "tools": true,
      "multimodal": true
    },
    "recommended_models": [
      {
        "name": "gpt-4o",
        "upstream_model": "gpt-4o",
        "description": "OpenAI GPT-4o 旗舰全能大模型"
      },
      {
        "name": "gpt-4o-mini",
        "upstream_model": "gpt-4o-mini",
        "description": "OpenAI GPT-4o-mini 高性价比快速模型"
      },
      {
        "name": "o3-mini",
        "upstream_model": "o3-mini",
        "description": "OpenAI 最新 o3-mini 快速推理思考模型"
      },
      {
        "name": "o1",
        "upstream_model": "o1",
        "description": "OpenAI o1 深度思考推理旗舰模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough",
        "supported_levels": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": false,
        "rescue_from_text": true
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      }
    }
  },
  {
    "id": "sensenova",
    "name": "商汤日日新 (SenseNova)",
    "version": "1.1.0",
    "protocol": "openai",
    "base_url": "https://token.sensenova.cn/v1",
    "doc_url": "https://platform.sensenova.cn/docs",
    "description": "商汤日日新大模型开放平台，支持 sensenova-6.8-flash-lite、deepseek-v4-flash、glm-5.2 等旗舰与轻量模型",
    "features": {
      "native_thinking": true,
      "multimodal": true,
      "tools": true
    },
    "recommended_models": [
      {
        "name": "sensenova-6.8-flash-lite",
        "upstream_model": "sensenova-6.8-flash-lite",
        "description": "商汤轻量级多模态智能体模型，高并发低延迟"
      },
      {
        "name": "deepseek-v4-flash",
        "upstream_model": "deepseek-v4-flash",
        "description": "1M 超长上下文深度思考模型"
      },
      {
        "name": "glm-5.2",
        "upstream_model": "GLM-5.2",
        "description": "智谱/商汤最新 GLM-5.2 旗舰推理大模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough",
        "supported_levels": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "tools": {
        "normalize_choice_to_string": true,
        "strip_json_schema": false,
        "rescue_from_text": true
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      }
    }
  },
  {
    "id": "siliconflow",
    "name": "硅基流动 (SiliconFlow)",
    "version": "1.1.0",
    "protocol": "openai",
    "base_url": "https://api.siliconflow.cn/v1",
    "doc_url": "https://docs.siliconflow.cn",
    "description": "硅基流动高并发推理平台，包含 DeepSeek-V3/R1、Qwen2.5 等海量开源模型",
    "features": {
      "native_thinking": true,
      "tools": true
    },
    "recommended_models": [
      {
        "name": "deepseek-ai/DeepSeek-V3",
        "upstream_model": "deepseek-ai/DeepSeek-V3",
        "description": "DeepSeek-V3 全尺寸旗舰模型"
      },
      {
        "name": "deepseek-ai/DeepSeek-R1",
        "upstream_model": "deepseek-ai/DeepSeek-R1",
        "description": "DeepSeek-R1 全尺寸深度思考模型"
      },
      {
        "name": "Qwen/Qwen2.5-72B-Instruct",
        "upstream_model": "Qwen/Qwen2.5-72B-Instruct",
        "description": "通义千问 72B Instruct 指令模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough",
        "supported_levels": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "tools": {
        "normalize_choice_to_string": true,
        "strip_json_schema": false,
        "rescue_from_text": true
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      }
    }
  },
  {
    "id": "stepfun",
    "name": "阶跃星辰 (StepFun)",
    "version": "1.1.0",
    "protocol": "openai",
    "base_url": "https://api.stepfun.com/step_plan",
    "doc_url": "https://platform.stepfun.com/docs/zh/api-reference/chat/chat-completion-create",
    "description": "阶跃星辰大模型平台，支持 step-3.7-flash 等，已自动适配 reasoning_effort none->low 降级与 deepseek-style 思考格式注入",
    "features": {
      "native_thinking": true,
      "multimodal": true,
      "tools": true
    },
    "recommended_models": [
      {
        "name": "step-3.7-flash",
        "upstream_model": "step-3.7-flash",
        "description": "阶跃最新闪电高速推理大模型 (支持 low/medium/high 思考)"
      },
      {
        "name": "step-3.5-flash",
        "upstream_model": "step-3.5-flash",
        "description": "阶跃 Step-3.5 高性价比推理模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "effort_remapping",
        "param_name": "reasoning_effort",
        "supported_levels": [
          "low",
          "medium",
          "high"
        ],
        "none_fallback": "low",
        "inject_params": {
          "reasoning_format": "deepseek-style"
        }
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": false,
        "rescue_from_text": true
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      },
      "response": {
        "reasoning_fields": [
          "reasoning",
          "reasoning_content"
        ]
      }
    }
  },
  {
    "id": "tokenrhythm",
    "name": "TokenRhythm",
    "version": "1.1.0",
    "protocol": "openai",
    "base_url": "https://tokenrhythm.studio/v1",
    "doc_url": "https://tokenrhythm.studio/docs/api-integration",
    "description": "TokenRhythm 聚合大模型路由网关，支持 deepseek-v4-flash, Claude, GPT 系列，自动适配 tool_choice 字符串转换与思考流提取",
    "features": {
      "native_thinking": true,
      "tools": true
    },
    "recommended_models": [
      {
        "name": "deepseek-v4-flash",
        "upstream_model": "deepseek-v4-flash",
        "description": "DeepSeek V4 Flash 旗舰模型"
      },
      {
        "name": "claude-3-5-sonnet-20241022",
        "upstream_model": "claude-3-5-sonnet-20241022",
        "description": "Claude 3.5 Sonnet 强编程模型"
      },
      {
        "name": "gpt-4o",
        "upstream_model": "gpt-4o",
        "description": "OpenAI GPT-4o 旗舰全能模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough",
        "supported_levels": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "tools": {
        "normalize_choice_to_string": true,
        "strip_json_schema": false,
        "rescue_from_text": true
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      }
    }
  }
];

export const PRESET_MAP = Object.fromEntries(PRESETS.map((p) => [p.id, p]));

export function getPreset(id) {
  const key = String(id || '').toLowerCase().trim();
  return PRESET_MAP[key] || PRESET_MAP[key.replace(/[.\-_]/g, '')] || null;
}
