/**
 * presets/index.js — Pure JS Registry of Provider Presets (zero JSON import attribute dependency).
 * Auto-generated by scripts/build-presets.mjs from shared/presets/*.json
 */

export const CATALOG = {
  "version": "1.1.0",
  "updated_at": "2026-10-09T15:07:05.998Z",
  "providers": [
    {
      "id": "agnes",
      "name": "Agnes AI",
      "version": "1.4.0",
      "rule_hash": "fefc72d3505b",
      "protocol": "openai",
      "base_url": "https://apihub.agnes-ai.com/v1",
      "anthropic_base_url": "https://apihub.agnes-ai.com/v1",
      "doc_url": "https://www.agnes-ai.com/zh-Hans/docs/agnes-30-flash",
      "description": "Agnes AI 平台，支持 agnes-3.0-flash 等高并发轻量 Agent 模型，原生直通 512k 上下文",
      "features": {
        "native_thinking": true,
        "tools": true,
        "multimodal": true,
        "anthropic_messages": true
      },
      "recommended_models_count": 3
    },
    {
      "id": "amd",
      "name": "AMD Radeon Cloud",
      "version": "1.2.0",
      "rule_hash": "147db7965508",
      "protocol": "openai",
      "base_url": "https://developer.amd.com.cn/radeon/api/v1",
      "anthropic_base_url": "https://developer.amd.com.cn/radeon/api/v1",
      "doc_url": "https://amd-aim.github.io/radeon-cloud-docs/",
      "description": "AMD 官方开发者平台，基于高性能推理集群。原生直通深度思考，自动适配 system 消息置顶规整",
      "features": {
        "native_thinking": true,
        "multimodal": false,
        "tools": true,
        "anthropic_messages": true
      },
      "recommended_models_count": 2
    },
    {
      "id": "bai",
      "name": "B.AI",
      "version": "1.4.0",
      "rule_hash": "7a4a9eed8e00",
      "protocol": "openai",
      "base_url": "https://api.b.ai/v1",
      "anthropic_base_url": "https://api.b.ai/v1",
      "doc_url": "https://docs.b.ai/llmservice/api/#messages-api-anthropic-compatible",
      "description": "B.AI 统一大模型服务，原生兼容 OpenAI Chat Completions 与 Anthropic Messages 协议双通道直通透传",
      "features": {
        "native_thinking": true,
        "tools": true,
        "anthropic_messages": true
      },
      "recommended_models_count": 4
    },
    {
      "id": "cline",
      "name": "Cline",
      "version": "1.1.0",
      "rule_hash": "287adac94c15",
      "protocol": "openai",
      "base_url": "https://api.cline.bot/api/v1",
      "anthropic_base_url": null,
      "doc_url": "https://docs.cline.bot/api/overview",
      "description": "Cline 官方大模型 API，基于 OpenRouter 聚合架构，支持 Claude、GPT-4o、Gemini 2.5、Muse Spark 等多厂商模型。网关已自动适配客户端受限模型别名映射与原生直通。",
      "features": {
        "native_thinking": true,
        "tools": true,
        "multimodal": true
      },
      "recommended_models_count": 7
    },
    {
      "id": "deepseek",
      "name": "DeepSeek 官方开放平台",
      "version": "1.2.0",
      "rule_hash": "61ae3a7b32fb",
      "protocol": "openai",
      "base_url": "https://api.deepseek.com/v1",
      "anthropic_base_url": null,
      "doc_url": "https://api-docs.deepseek.com",
      "description": "DeepSeek 官方 API，原生支持 reasoning_content 深度思考与前缀缓存",
      "features": {
        "native_thinking": true,
        "tools": true
      },
      "recommended_models_count": 2
    },
    {
      "id": "google",
      "name": "Google AI Studio",
      "version": "1.2.0",
      "rule_hash": "f87bea8c1551",
      "protocol": "google_openai",
      "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
      "anthropic_base_url": null,
      "doc_url": "https://ai.google.dev/gemini-api/docs/openai",
      "description": "Google 官方 Gemini 系列大模型，支持 Gemini 2.5 / 3 / 3.5+，内置 Thinking Matrix、深度 Schema 裁剪与思考预算自动提升",
      "features": {
        "native_thinking": true,
        "multimodal": true,
        "tools": true
      },
      "recommended_models_count": 5
    },
    {
      "id": "minimax",
      "name": "MiniMax",
      "version": "1.3.0",
      "rule_hash": "dc0aae66c67c",
      "protocol": "openai",
      "base_url": "https://api.minimaxi.com/v1",
      "anthropic_base_url": "https://api.minimaxi.com/anthropic",
      "doc_url": "https://platform.minimax.cn/docs/api-reference/text-chat-openai",
      "description": "MiniMax 开放平台（国内），MiniMax-M3 / M3.1-Flash-Preview，原生 OpenAI Chat Completions 与 Anthropic Messages 双协议直通",
      "features": {
        "native_thinking": true,
        "multimodal": true,
        "tools": true,
        "anthropic_messages": true
      },
      "recommended_models_count": 2
    },
    {
      "id": "nvidia",
      "name": "NVIDIA NIM",
      "version": "2.0.0",
      "rule_hash": "187af2f5f93d",
      "protocol": "openai",
      "base_url": "https://integrate.api.nvidia.com/v1",
      "anthropic_base_url": null,
      "doc_url": "https://docs.api.nvidia.com/",
      "description": "NVIDIA NIM 官方加速平台（build.nvidia.com 免费领取 nvapi- Key，无需绑卡；免费档约 40 RPM / 每日 1 万请求）。注意模型按账号单独激活，404 即该 Key 未开通该模型；流式推理返回 reasoning_content，已加固自动关流防护",
      "features": {
        "multimodal": true,
        "native_thinking": true,
        "tools": true
      },
      "recommended_models_count": 6
    },
    {
      "id": "openai",
      "name": "OpenAI 官方",
      "version": "1.2.0",
      "rule_hash": "61ae3a7b32fb",
      "protocol": "openai",
      "base_url": "https://api.openai.com/v1",
      "anthropic_base_url": null,
      "doc_url": "https://platform.openai.com/docs",
      "description": "OpenAI 官方 API 或标准兼容中转网关，纯中转零损耗极速透传，原生支持 reasoning_effort 思考控制与多模态",
      "features": {
        "native_thinking": true,
        "tools": true,
        "multimodal": true
      },
      "recommended_models_count": 4
    },
    {
      "id": "opencode",
      "name": "OpenCode Zen",
      "version": "2.0.0",
      "rule_hash": "e1aa35db8ce1",
      "protocol": "openai",
      "base_url": "https://opencode.ai/zen/v1",
      "anthropic_base_url": null,
      "doc_url": "https://opencode.ai/docs/zen/",
      "description": "OpenCode Zen 官方托管模型（opencode.ai/zen 登录领取 Key，纯 OpenAI 协议直通透传）。免费档模型限时免费，按账号/IP 计每日限额；超限返回 429 FreeUsageLimitError。注意：免费模型原则上仅限 OpenCode 客户端内调用，第三方直连可能触发 403 FreeTierError。",
      "features": {
        "multimodal": true,
        "native_thinking": true,
        "tools": true
      },
      "recommended_models_count": 8
    },
    {
      "id": "openrouter",
      "name": "OpenRouter",
      "version": "1.0.0",
      "rule_hash": "3aefdebb947c",
      "protocol": "openai",
      "base_url": "https://openrouter.ai/api/v1",
      "anthropic_base_url": "https://openrouter.ai/api/v1",
      "doc_url": "https://openrouter.ai/docs/api/reference/overview",
      "description": "OpenRouter 全球模型聚合网关，原生支持 OpenAI 与 Anthropic 双协议。免费档（:free 后缀模型）：20 RPM；每日 50 请求（openrouter.ai 账户累计消费 ≥$10 后提至 1000/日）。注册无需绑卡（sk-or- 开头 Key）。",
      "features": {
        "anthropic_messages": true,
        "multimodal": true,
        "native_thinking": true,
        "tools": true
      },
      "recommended_models_count": 7
    },
    {
      "id": "sensenova",
      "name": "商汤日日新",
      "version": "1.3.0",
      "rule_hash": "0cf60ddb3bd5",
      "protocol": "openai",
      "base_url": "https://token.sensenova.cn/v1",
      "anthropic_base_url": "https://token.sensenova.cn/v1",
      "doc_url": "https://platform.sensenova.cn/docs",
      "description": "商汤日日新大模型开放平台，支持 sensenova-6.8-flash-lite、deepseek-v4-flash、glm-5.2 等旗舰与轻量模型",
      "features": {
        "native_thinking": true,
        "multimodal": true,
        "tools": true,
        "anthropic_messages": true
      },
      "recommended_models_count": 3
    },
    {
      "id": "siliconflow",
      "name": "硅基流动",
      "version": "1.2.0",
      "rule_hash": "61ae3a7b32fb",
      "protocol": "openai",
      "base_url": "https://api.siliconflow.cn/v1",
      "anthropic_base_url": null,
      "doc_url": "https://docs.siliconflow.cn",
      "description": "硅基流动高并发推理平台，包含 DeepSeek-V3/R1、Qwen2.5 等海量开源模型",
      "features": {
        "native_thinking": true,
        "tools": true
      },
      "recommended_models_count": 3
    },
    {
      "id": "stepfun",
      "name": "阶跃星辰",
      "version": "1.2.0",
      "rule_hash": "ff735ef0f91a",
      "protocol": "openai",
      "base_url": "https://api.stepfun.com/step_plan",
      "anthropic_base_url": null,
      "doc_url": "https://platform.stepfun.com/docs/zh/api-reference/chat/chat-completion-create",
      "description": "阶跃星辰大模型平台，支持 step-3.7-flash、step-3.5-flash 等，原生 OpenAI 协议直通透传",
      "features": {
        "native_thinking": true,
        "multimodal": true,
        "tools": true
      },
      "recommended_models_count": 2
    },
    {
      "id": "tokenrhythm",
      "name": "TokenRhythm",
      "version": "1.2.0",
      "rule_hash": "61ae3a7b32fb",
      "protocol": "openai",
      "base_url": "https://tokenrhythm.studio/v1",
      "anthropic_base_url": null,
      "doc_url": "https://tokenrhythm.studio/docs/api-integration",
      "description": "TokenRhythm 聚合大模型路由网关，支持 deepseek-v4-flash, Claude, GPT 系列，原生协议直通透传",
      "features": {
        "native_thinking": true,
        "tools": true
      },
      "recommended_models_count": 3
    },
    {
      "id": "vertex",
      "name": "Google Vertex AI",
      "version": "1.1.0",
      "rule_hash": "1128b7ad5ca0",
      "protocol": "vertex_openai",
      "base_url": "https://aiplatform.googleapis.com/v1beta1/projects/{project_id}/locations/global/endpoints/openapi",
      "anthropic_base_url": null,
      "doc_url": "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/start/openai?hl=zh-cn",
      "description": "Google Cloud Vertex AI 官方大模型端点。凭证、Project ID 与服务区域在新增 Key 时强绑定，自动规整 google/ 前缀与思考等级配置",
      "features": {
        "native_thinking": true,
        "multimodal": true,
        "tools": true,
        "require_project_id": true,
        "require_location": true
      },
      "recommended_models_count": 1
    }
  ]
};

export const PRESETS = [
  {
    "id": "agnes",
    "name": "Agnes AI",
    "version": "1.4.0",
    "protocol": "openai",
    "base_url": "https://apihub.agnes-ai.com/v1",
    "doc_url": "https://www.agnes-ai.com/zh-Hans/docs/agnes-30-flash",
    "description": "Agnes AI 平台，支持 agnes-3.0-flash 等高并发轻量 Agent 模型，原生直通 512k 上下文",
    "features": {
      "native_thinking": true,
      "tools": true,
      "multimodal": true,
      "anthropic_messages": true
    },
    "recommended_models": [
      {
        "name": "agnes-3.0-flash",
        "upstream_model": "agnes-3.0-flash",
        "description": "Agnes 3.0 Flash 全新一代旗舰开源推理模型 (512K 上下文)"
      },
      {
        "name": "agnes-2.5-flash",
        "upstream_model": "agnes-2.5-flash",
        "description": "Agnes 2.5 Flash 旗舰高速模型 (512K 上下文)"
      },
      {
        "name": "agnes-2.0-flash",
        "upstream_model": "agnes-2.0-flash",
        "description": "Agnes 2.0 Flash 兼容回退模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough"
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": false,
        "rescue_from_text": false
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": [],
        "max_tokens_ceiling": 65536
      }
    },
    "anthropic_base_url": "https://apihub.agnes-ai.com/v1"
  },
  {
    "id": "amd",
    "name": "AMD Radeon Cloud",
    "version": "1.2.0",
    "protocol": "openai",
    "base_url": "https://developer.amd.com.cn/radeon/api/v1",
    "anthropic_base_url": "https://developer.amd.com.cn/radeon/api/v1",
    "doc_url": "https://amd-aim.github.io/radeon-cloud-docs/",
    "description": "AMD 官方开发者平台，基于高性能推理集群。原生直通深度思考，自动适配 system 消息置顶规整",
    "features": {
      "native_thinking": true,
      "multimodal": false,
      "tools": true,
      "anthropic_messages": true
    },
    "recommended_models": [
      {
        "name": "deepseek-v4-flash",
        "upstream_model": "DeepSeek-V4-Flash",
        "description": "DeepSeek V4 Flash 百万原生上下文智能体大模型 (原生深度思考)"
      },
      {
        "name": "qwen3.8-flash-next",
        "upstream_model": "Qwen3.8-Flash-Next",
        "description": "千问全新 QSA 稀疏注意力大模型 (26.2万上下文，网关已自动适配 system 消息置顶)"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough"
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": false,
        "rescue_from_text": false
      },
      "messages": {
        "deny_developer_role": true,
        "system_first_only": true,
        "merge_system": true,
        "strip_empty": true
      },
      "sanitization": {
        "strip_params": [
          "thinking",
          "chat_template_kwargs"
        ]
      }
    }
  },
  {
    "id": "bai",
    "name": "B.AI",
    "version": "1.4.0",
    "protocol": "openai",
    "base_url": "https://api.b.ai/v1",
    "anthropic_base_url": "https://api.b.ai/v1",
    "doc_url": "https://docs.b.ai/llmservice/api/#messages-api-anthropic-compatible",
    "description": "B.AI 统一大模型服务，原生兼容 OpenAI Chat Completions 与 Anthropic Messages 协议双通道直通透传",
    "features": {
      "native_thinking": true,
      "tools": true,
      "anthropic_messages": true
    },
    "recommended_models": [
      {
        "name": "glm-5.3-flash",
        "upstream_model": "glm-5.3-flash",
        "description": "智谱 GLM 5.3 Flash 原生常开深度思考模型"
      },
      {
        "name": "qwen3.8-flash",
        "upstream_model": "qwen3.8-flash",
        "description": "千问 3.8 Flash 模型 (原生思考支持)"
      },
      {
        "name": "claude-3-5-sonnet",
        "upstream_model": "claude-3-5-sonnet",
        "description": "Claude 3.5 Sonnet 模型（B.AI 兼容端点）"
      },
      {
        "name": "deepseek-v3",
        "upstream_model": "deepseek-v3",
        "description": "DeepSeek V3 模型（B.AI 兼容端点）"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough"
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": false,
        "rescue_from_text": false
      },
      "sanitization": {
        "unsupported_params": []
      },
      "error_rules": [
        {
          "name": "credit_insufficient_balance",
          "match_status": 400,
          "match_keywords": [
            "credit",
            "balance",
            "insufficient",
            "欠费",
            "余额不足"
          ],
          "action": "quota_exhausted",
          "cooldown_sec": 1800,
          "failover": true
        }
      ],
      "timeout_rules": {
        "default_timeout_sec": 60,
        "models": {
          "glm-5.3-flash": 120,
          "glm-5.3": 120
        }
      }
    }
  },
  {
    "id": "cline",
    "name": "Cline",
    "version": "1.1.0",
    "protocol": "openai",
    "base_url": "https://api.cline.bot/api/v1",
    "doc_url": "https://docs.cline.bot/api/overview",
    "description": "Cline 官方大模型 API，基于 OpenRouter 聚合架构，支持 Claude、GPT-4o、Gemini 2.5、Muse Spark 等多厂商模型。网关已自动适配客户端受限模型别名映射与原生直通。",
    "features": {
      "native_thinking": true,
      "tools": true,
      "multimodal": true
    },
    "recommended_models": [
      {
        "name": "meta/muse-spark-1.3-contributor",
        "upstream_model": "meta/muse-spark-1.3-contributor",
        "description": "Muse Spark 1.3 强推理模型 (已做客户端别名适配)"
      },
      {
        "name": "meta/muse-spark-1.3",
        "upstream_model": "meta/muse-spark-1.3",
        "description": "Muse Spark 1.3 经典轻量模型"
      },
      {
        "name": "nvidia/nemotron-3.5-lightning:free",
        "upstream_model": "nvidia/nemotron-3.5-lightning:free",
        "description": "Nvidia Nemotron 3.5 高速免费模型"
      },
      {
        "name": "google/gemma-4-26b-a4b-it:free",
        "upstream_model": "google/gemma-4-26b-a4b-it:free",
        "description": "Google Gemma 4 免费轻量模型"
      },
      {
        "name": "anthropic/claude-sonnet-4-6",
        "upstream_model": "anthropic/claude-sonnet-4-6",
        "description": "Claude Sonnet 4.6 旗舰编程模型"
      },
      {
        "name": "openai/gpt-4o",
        "upstream_model": "openai/gpt-4o",
        "description": "OpenAI GPT-4o 旗舰全能模型"
      },
      {
        "name": "deepseek/deepseek-chat",
        "upstream_model": "deepseek/deepseek-chat",
        "description": "DeepSeek V3 极速推理模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough",
        "supported_levels": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "model_alias": {
        "cline-free/muse-spark-1.3-contributor": "meta/muse-spark-1.3-contributor",
        "cline-free/muse-spark-1.3": "meta/muse-spark-1.3",
        "cline-free/muse-spark-1.2-contributor": "meta/muse-spark-1.2-contributor"
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": false,
        "rescue_from_text": false
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      },
      "error_rules": [
        {
          "name": "upstream_rate_limited",
          "match_status": 500,
          "match_keywords": [
            "429",
            "rate-limited",
            "upstream_provider_shared_pool"
          ],
          "action": "failover",
          "cooldown_sec": 60,
          "failover": true
        }
      ]
    }
  },
  {
    "id": "deepseek",
    "name": "DeepSeek 官方开放平台",
    "version": "1.2.0",
    "protocol": "openai",
    "base_url": "https://api.deepseek.com/v1",
    "doc_url": "https://api-docs.deepseek.com",
    "description": "DeepSeek 官方 API，原生支持 reasoning_content 深度思考与前缀缓存",
    "features": {
      "native_thinking": true,
      "tools": true
    },
    "recommended_models": [
      {
        "name": "deepseek-chat",
        "upstream_model": "deepseek-chat",
        "description": "DeepSeek-V3 快速对话大模型"
      },
      {
        "name": "deepseek-reasoner",
        "upstream_model": "deepseek-reasoner",
        "description": "DeepSeek-R1 深度思考推理大模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough",
        "supported_levels": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": false,
        "rescue_from_text": false
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      }
    }
  },
  {
    "id": "google",
    "name": "Google AI Studio",
    "version": "1.2.0",
    "protocol": "google_openai",
    "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
    "description": "Google 官方 Gemini 系列大模型，支持 Gemini 2.5 / 3 / 3.5+，内置 Thinking Matrix、深度 Schema 裁剪与思考预算自动提升",
    "features": {
      "native_thinking": true,
      "multimodal": true,
      "tools": true
    },
    "recommended_models": [
      {
        "name": "gemini-3.8-flash",
        "upstream_model": "gemini-3.8-flash",
        "description": "最新 Flash（thinking_level minimal/low/medium/high）"
      },
      {
        "name": "gemini-3.5-flash",
        "upstream_model": "gemini-3.5-flash",
        "description": "高性价比 Flash"
      },
      {
        "name": "gemini-3.1-pro",
        "upstream_model": "gemini-3.1-pro",
        "description": "旗舰 Pro（thinking_level low/medium/high，不可关闭思考）"
      },
      {
        "name": "gemini-2.5-flash",
        "upstream_model": "gemini-2.5-flash",
        "description": "经典 Flash（thinking_budget，可关闭思考）"
      },
      {
        "name": "gemini-2.5-pro",
        "upstream_model": "gemini-2.5-pro",
        "description": "经典 Pro（thinking_budget）"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "gemini_thinking_matrix",
        "none_action": "include_thoughts_false",
        "headroom_elevation": true,
        "model_matrix": {
          "flash": [
            "minimal",
            "low",
            "medium",
            "high"
          ],
          "pro": [
            "low",
            "medium",
            "high"
          ]
        }
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": true,
        "deep_schema_sanitization": true,
        "rescue_from_text": true
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      }
    },
    "doc_url": "https://ai.google.dev/gemini-api/docs/openai"
  },
  {
    "id": "minimax",
    "name": "MiniMax",
    "version": "1.3.0",
    "protocol": "openai",
    "base_url": "https://api.minimaxi.com/v1",
    "anthropic_base_url": "https://api.minimaxi.com/anthropic",
    "doc_url": "https://platform.minimax.cn/docs/api-reference/text-chat-openai",
    "description": "MiniMax 开放平台（国内），MiniMax-M3 / M3.1-Flash-Preview，原生 OpenAI Chat Completions 与 Anthropic Messages 双协议直通",
    "features": {
      "native_thinking": true,
      "multimodal": true,
      "tools": true,
      "anthropic_messages": true
    },
    "recommended_models": [
      {
        "name": "MiniMax-M3",
        "upstream_model": "MiniMax-M3",
        "description": "多模态旗舰（文本/图片/视频），OpenAI 端默认 adaptive 思考"
      },
      {
        "name": "MiniMax-M3.1-Flash-Preview",
        "upstream_model": "MiniMax-M3.1-Flash-Preview",
        "description": "1M 上下文、强制思考、reasoning_effort low~max（目前仅 M Plan / MiniMax Code 可用）"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough",
        "supported_levels": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "case_sensitive_models": {
        "minimax-m3": "MiniMax-M3",
        "minimax-m3.1-flash-preview": "MiniMax-M3.1-Flash-Preview"
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": false,
        "rescue_from_text": false
      },
      "sanitization": {
        "strip_params": [
          "output_config"
        ]
      }
    }
  },
  {
    "adapter_rules": {
      "error_rules": [
        {
          "action": "failover",
          "cooldown_sec": 3600,
          "failover": true,
          "match_keywords": [
            "not found for account",
            "function",
            "not found"
          ],
          "match_status": 404,
          "name": "model_not_activated_for_account"
        },
        {
          "action": "failover",
          "cooldown_sec": 90,
          "failover": true,
          "match_keywords": [
            "rate limit",
            "too many requests",
            "429"
          ],
          "match_status": 429,
          "name": "free_tier_rate_limited"
        }
      ],
      "reasoning": {
        "strategy": "openai_passthrough",
        "supported_levels": [
          "none",
          "low",
          "medium",
          "high",
          "max"
        ]
      },
      "sanitization": {
        "unsupported_params": []
      },
      "timeout_rules": {
        "default_timeout_sec": 60
      },
      "tools": {
        "normalize_choice_to_string": true,
        "rescue_from_text": false,
        "strip_json_schema": false
      },
      "user_tracking": {
        "passthrough_user": true
      }
    },
    "anthropic_base_url": null,
    "base_url": "https://integrate.api.nvidia.com/v1",
    "description": "NVIDIA NIM 官方加速平台（build.nvidia.com 免费领取 nvapi- Key，无需绑卡；免费档约 40 RPM / 每日 1 万请求）。注意模型按账号单独激活，404 即该 Key 未开通该模型；流式推理返回 reasoning_content，已加固自动关流防护",
    "doc_url": "https://docs.api.nvidia.com/",
    "features": {
      "multimodal": true,
      "native_thinking": true,
      "tools": true
    },
    "id": "nvidia",
    "name": "NVIDIA NIM",
    "protocol": "openai",
    "recommended_models": [
      {
        "description": "120B MoE 旗舰，通用/coding 全能主力",
        "name": "nemotron-3-super-120b",
        "upstream_model": "nvidia/nemotron-3-super-120b-a12b"
      },
      {
        "description": "30B 极速闪电推理模型，低延迟高性价比",
        "name": "nemotron-3.5-lightning",
        "upstream_model": "nvidia/nemotron-3.5-lightning-30b-a3b"
      },
      {
        "description": "Kimi K3 视觉+推理，256K 上下文，支持 reasoning_effort",
        "name": "kimi-k3",
        "upstream_model": "moonshotai/kimi-k3"
      },
      {
        "description": "DeepSeek V4 Flash 变体，快速通用",
        "name": "deepseek-v4-flash",
        "upstream_model": "deepseek-ai/deepseek-v4-flash-0731"
      },
      {
        "description": "Agentic coding 小快模型",
        "name": "laguna-xs-2.1",
        "upstream_model": "poolside/laguna-xs-2.1"
      },
      {
        "description": "Llama 3.2 11B Vision，极速图文+函数调用",
        "name": "llama-3.2-11b-vision",
        "upstream_model": "meta/llama-3.2-11b-vision-instruct"
      }
    ],
    "version": "2.0.0"
  },
  {
    "id": "openai",
    "name": "OpenAI 官方",
    "version": "1.2.0",
    "protocol": "openai",
    "base_url": "https://api.openai.com/v1",
    "doc_url": "https://platform.openai.com/docs",
    "description": "OpenAI 官方 API 或标准兼容中转网关，纯中转零损耗极速透传，原生支持 reasoning_effort 思考控制与多模态",
    "features": {
      "native_thinking": true,
      "tools": true,
      "multimodal": true
    },
    "recommended_models": [
      {
        "name": "gpt-4o",
        "upstream_model": "gpt-4o",
        "description": "OpenAI GPT-4o 旗舰全能大模型"
      },
      {
        "name": "gpt-4o-mini",
        "upstream_model": "gpt-4o-mini",
        "description": "OpenAI GPT-4o-mini 高性价比快速模型"
      },
      {
        "name": "o3-mini",
        "upstream_model": "o3-mini",
        "description": "OpenAI 最新 o3-mini 快速推理思考模型"
      },
      {
        "name": "o1",
        "upstream_model": "o1",
        "description": "OpenAI o1 深度思考推理旗舰模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough",
        "supported_levels": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": false,
        "rescue_from_text": false
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      }
    }
  },
  {
    "adapter_rules": {
      "error_rules": [
        {
          "action": "quota_exhausted",
          "cooldown_sec": 1800,
          "failover": true,
          "match_keywords": [
            "FreeTierError",
            "free tier",
            "within OpenCode"
          ],
          "match_status": 403,
          "name": "zen_free_tier_forbidden"
        },
        {
          "action": "failover",
          "cooldown_sec": 300,
          "failover": true,
          "match_keywords": [
            "FreeUsageLimitError",
            "daily free usage limit",
            "Rate limit exceeded"
          ],
          "match_status": 429,
          "name": "zen_daily_free_limit"
        }
      ],
      "reasoning": {
        "strategy": "openai_passthrough"
      },
      "sanitization": {
        "unsupported_params": []
      },
      "timeout_rules": {
        "default_timeout_sec": 60
      },
      "tools": {
        "normalize_choice_to_string": false,
        "rescue_from_text": false,
        "strip_json_schema": false
      },
      "user_tracking": {
        "passthrough_user": true
      }
    },
    "base_url": "https://opencode.ai/zen/v1",
    "description": "OpenCode Zen 官方托管模型（opencode.ai/zen 登录领取 Key，纯 OpenAI 协议直通透传）。免费档模型限时免费，按账号/IP 计每日限额；超限返回 429 FreeUsageLimitError。注意：免费模型原则上仅限 OpenCode 客户端内调用，第三方直连可能触发 403 FreeTierError。",
    "doc_url": "https://opencode.ai/docs/zen/",
    "features": {
      "multimodal": true,
      "native_thinking": true,
      "tools": true
    },
    "id": "opencode",
    "name": "OpenCode Zen",
    "protocol": "openai",
    "recommended_models": [
      {
        "description": "Zen 免费全能 stealth 模型（限时免费）",
        "name": "big-pickle",
        "upstream_model": "big-pickle"
      },
      {
        "description": "Zen 免费 stealth 模型，零数据保留",
        "name": "space-bunny-free",
        "upstream_model": "space-bunny-free"
      },
      {
        "description": "阶跃 Step 5 Preview 免费版，零数据保留",
        "name": "step-5-preview-free",
        "upstream_model": "step-5-preview-free"
      },
      {
        "description": "LongCat 2.5 Preview 免费版，零数据保留",
        "name": "longcat-2.5-preview-free",
        "upstream_model": "longcat-2.5-preview-free"
      },
      {
        "description": "小米 MiMo V2.6 Flash 免费版",
        "name": "mimo-v2.6-flash-free",
        "upstream_model": "mimo-v2.6-flash-free"
      },
      {
        "description": "Ling 3.1 Flash 免费版",
        "name": "ling-3.1-flash-free",
        "upstream_model": "ling-3.1-flash-free"
      },
      {
        "description": "Nemotron 3 Ultra 免费试用（NVIDIA 通道，请勿传输机密数据）",
        "name": "nemotron-3-ultra-free",
        "upstream_model": "nemotron-3-ultra-free"
      },
      {
        "description": "Nemotron 3.5 Lightning 免费试用（NVIDIA 通道）",
        "name": "nemotron-3.5-lightning-free",
        "upstream_model": "nemotron-3.5-lightning-free"
      }
    ],
    "version": "2.0.0"
  },
  {
    "adapter_rules": {
      "error_rules": [
        {
          "action": "failover",
          "cooldown_sec": 120,
          "failover": true,
          "match_keywords": [
            "rate limit",
            "rate_limit",
            "free-models-per-day",
            "free_models_per_day",
            "Rate limit exceeded"
          ],
          "match_status": 429,
          "name": "free_tier_rate_limited"
        },
        {
          "action": "quota_exhausted",
          "cooldown_sec": 1800,
          "failover": true,
          "match_keywords": [
            "credit",
            "balance",
            "insufficient",
            "402"
          ],
          "match_status": 402,
          "name": "negative_credit_balance"
        }
      ],
      "inject_headers": {
        "HTTP-Referer": "https://github.com/khc8655/ocrproxy",
        "X-Title": "OCRProxy"
      },
      "reasoning": {
        "strategy": "openai_passthrough",
        "supported_levels": [
          "none",
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "sanitization": {
        "unsupported_params": []
      },
      "timeout_rules": {
        "default_timeout_sec": 60
      },
      "tools": {
        "normalize_choice_to_string": false,
        "rescue_from_text": false,
        "strip_json_schema": false
      },
      "user_tracking": {
        "passthrough_user": true
      }
    },
    "anthropic_base_url": "https://openrouter.ai/api/v1",
    "base_url": "https://openrouter.ai/api/v1",
    "description": "OpenRouter 全球模型聚合网关，原生支持 OpenAI 与 Anthropic 双协议。免费档（:free 后缀模型）：20 RPM；每日 50 请求（openrouter.ai 账户累计消费 ≥$10 后提至 1000/日）。注册无需绑卡（sk-or- 开头 Key）。",
    "doc_url": "https://openrouter.ai/docs/api/reference/overview",
    "features": {
      "anthropic_messages": true,
      "multimodal": true,
      "native_thinking": true,
      "tools": true
    },
    "id": "openrouter",
    "name": "OpenRouter",
    "protocol": "openai",
    "recommended_models": [
      {
        "description": "免费档最强 coding 模型（262K 上下文）",
        "name": "qwen3-coder:free",
        "upstream_model": "qwen/qwen3-coder:free"
      },
      {
        "description": "Agentic coding 专用模型（262K 上下文）",
        "name": "laguna-s-2.1:free",
        "upstream_model": "poolside/laguna-s-2.1:free"
      },
      {
        "description": "550B MoE 免费推理/调度模型（1M 上下文）",
        "name": "nemotron-3-ultra:free",
        "upstream_model": "nvidia/nemotron-3-ultra-550b-a55b:free"
      },
      {
        "description": "30B MoE 轻量 coding 模型（256K 上下文）",
        "name": "north-mini-code:free",
        "upstream_model": "cohere/north-mini-code:free"
      },
      {
        "description": "120B MoE 多智能体吞吐模型（1M 上下文）",
        "name": "nemotron-3-super:free",
        "upstream_model": "nvidia/nemotron-3-super-120b-a12b:free"
      },
      {
        "description": "Google 多模态轻量模型（262K 上下文）",
        "name": "gemma-4-26b:free",
        "upstream_model": "google/gemma-4-26b-a4b-it:free"
      },
      {
        "description": "动态路由：自动选择当前可用的免费模型（兜底用）",
        "name": "openrouter-free-router",
        "upstream_model": "openrouter/free"
      }
    ],
    "version": "1.0.0"
  },
  {
    "id": "sensenova",
    "name": "商汤日日新",
    "version": "1.3.0",
    "protocol": "openai",
    "base_url": "https://token.sensenova.cn/v1",
    "doc_url": "https://platform.sensenova.cn/docs",
    "description": "商汤日日新大模型开放平台，支持 sensenova-6.8-flash-lite、deepseek-v4-flash、glm-5.2 等旗舰与轻量模型",
    "features": {
      "native_thinking": true,
      "multimodal": true,
      "tools": true,
      "anthropic_messages": true
    },
    "recommended_models": [
      {
        "name": "sensenova-6.8-flash-lite",
        "upstream_model": "sensenova-6.8-flash-lite",
        "description": "商汤轻量级多模态智能体模型，高并发低延迟"
      },
      {
        "name": "deepseek-v4-flash",
        "upstream_model": "deepseek-v4-flash",
        "description": "1M 超长上下文深度思考模型"
      },
      {
        "name": "glm-5.2",
        "upstream_model": "glm-5.2",
        "description": "智谱/商汤最新 GLM-5.2 旗舰推理大模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough",
        "supported_levels": [
          "none",
          "low",
          "medium",
          "high",
          "max"
        ]
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": false,
        "rescue_from_text": false
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      }
    },
    "anthropic_base_url": "https://token.sensenova.cn/v1"
  },
  {
    "id": "siliconflow",
    "name": "硅基流动",
    "version": "1.2.0",
    "protocol": "openai",
    "base_url": "https://api.siliconflow.cn/v1",
    "doc_url": "https://docs.siliconflow.cn",
    "description": "硅基流动高并发推理平台，包含 DeepSeek-V3/R1、Qwen2.5 等海量开源模型",
    "features": {
      "native_thinking": true,
      "tools": true
    },
    "recommended_models": [
      {
        "name": "deepseek-ai/DeepSeek-V3",
        "upstream_model": "deepseek-ai/DeepSeek-V3",
        "description": "DeepSeek-V3 全尺寸旗舰模型"
      },
      {
        "name": "deepseek-ai/DeepSeek-R1",
        "upstream_model": "deepseek-ai/DeepSeek-R1",
        "description": "DeepSeek-R1 全尺寸深度思考模型"
      },
      {
        "name": "Qwen/Qwen2.5-72B-Instruct",
        "upstream_model": "Qwen/Qwen2.5-72B-Instruct",
        "description": "通义千问 72B Instruct 指令模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough",
        "supported_levels": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": false,
        "rescue_from_text": false
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      }
    }
  },
  {
    "id": "stepfun",
    "name": "阶跃星辰",
    "version": "1.2.0",
    "protocol": "openai",
    "base_url": "https://api.stepfun.com/step_plan",
    "doc_url": "https://platform.stepfun.com/docs/zh/api-reference/chat/chat-completion-create",
    "description": "阶跃星辰大模型平台，支持 step-3.7-flash、step-3.5-flash 等，原生 OpenAI 协议直通透传",
    "features": {
      "native_thinking": true,
      "multimodal": true,
      "tools": true
    },
    "recommended_models": [
      {
        "name": "step-3.7-flash",
        "upstream_model": "step-3.7-flash",
        "description": "阶跃最新闪电高速推理大模型"
      },
      {
        "name": "step-3.5-flash",
        "upstream_model": "step-3.5-flash",
        "description": "阶跃 Step-3.5 高性价比推理模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough"
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": false,
        "rescue_from_text": false
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      }
    }
  },
  {
    "id": "tokenrhythm",
    "name": "TokenRhythm",
    "version": "1.2.0",
    "protocol": "openai",
    "base_url": "https://tokenrhythm.studio/v1",
    "doc_url": "https://tokenrhythm.studio/docs/api-integration",
    "description": "TokenRhythm 聚合大模型路由网关，支持 deepseek-v4-flash, Claude, GPT 系列，原生协议直通透传",
    "features": {
      "native_thinking": true,
      "tools": true
    },
    "recommended_models": [
      {
        "name": "deepseek-v4-flash",
        "upstream_model": "deepseek-v4-flash",
        "description": "DeepSeek V4 Flash 旗舰模型"
      },
      {
        "name": "claude-3-5-sonnet-20241022",
        "upstream_model": "claude-3-5-sonnet-20241022",
        "description": "Claude 3.5 Sonnet 强编程模型"
      },
      {
        "name": "gpt-4o",
        "upstream_model": "gpt-4o",
        "description": "OpenAI GPT-4o 旗舰全能模型"
      }
    ],
    "adapter_rules": {
      "reasoning": {
        "strategy": "openai_passthrough",
        "supported_levels": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": false,
        "rescue_from_text": false
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      }
    }
  },
  {
    "id": "vertex",
    "name": "Google Vertex AI",
    "version": "1.1.0",
    "protocol": "vertex_openai",
    "base_url": "https://aiplatform.googleapis.com/v1beta1/projects/{project_id}/locations/global/endpoints/openapi",
    "doc_url": "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/start/openai?hl=zh-cn",
    "description": "Google Cloud Vertex AI 官方大模型端点。凭证、Project ID 与服务区域在新增 Key 时强绑定，自动规整 google/ 前缀与思考等级配置",
    "features": {
      "native_thinking": true,
      "multimodal": true,
      "tools": true,
      "require_project_id": true,
      "require_location": true
    },
    "recommended_models": [
      {
        "name": "gemini-3.8-flash",
        "upstream_model": "google/gemini-3.8-flash",
        "description": "最新高性能推理模型 (官方 OpenAI 端点强制要求 google/ 前缀)"
      }
    ],
    "adapter_rules": {
      "model_alias": {
        "gemini-3.8-flash": "google/gemini-3.8-flash"
      },
      "ensure_google_prefix": true,
      "reasoning": {
        "strategy": "gemini_thinking_matrix",
        "none_action": "include_thoughts_false",
        "headroom_elevation": true,
        "model_matrix": {
          "flash": [
            "minimal",
            "low",
            "medium",
            "high"
          ],
          "pro": [
            "low",
            "medium",
            "high"
          ]
        },
        "thought_tag_marker": true
      },
      "tools": {
        "normalize_choice_to_string": false,
        "strip_json_schema": true,
        "deep_schema_sanitization": true,
        "rescue_from_text": true
      },
      "user_tracking": {
        "passthrough_user": true
      },
      "sanitization": {
        "unsupported_params": []
      }
    }
  }
];

export const PRESET_MAP = Object.fromEntries(PRESETS.map((p) => [p.id, p]));

export function getPreset(id) {
  const key = String(id || '').toLowerCase().trim();
  return PRESET_MAP[key] || PRESET_MAP[key.replace(/[.\-_]/g, '')] || null;
}
